### ISSUE TITLE
是否存在内存泄漏，还是设计如此？

### ISSUE THREAD

**Issue by jiasongs** [tigerAndBull/TABAnimated#100]
经测试，使用自定义View的时候，自定义View的内存并没有被释放。
以下是操作步骤：
1、打开Demo中自定义UIView示例
2、选择普通View进入界面
3、等加载完之后，返回到上一层
4、`TestHeadView`这个类里的dealloc并没有触发
以下是Demo，代码在`ViewExampleViewController`
[TABAnimatedDemo.zip](https://github.com/tigerAndBull/TABAnimated/files/5093494/TABAnimatedDemo.zip)

**Comment by jiasongs** [comment]
`TABAnimatedProductImpl`类中有个`targetViewArray`属性
<img width="355" alt="图片" src="https://user-images.githubusercontent.com/22904757/90583044-d08d7e80-e201-11ea-9ba0-abbcc7a808a8.png">
此做法会让`targetView`与`TABAnimatedProductImpl`实例互相持有，导致循环引用。
解除循环引用的办法有两个：
1、调用下`destory`方法，让`targetViewArray`清空，但是我在demo里没有见到调用的地方。
2、`targetViewArray`使用`NSPointerArray`的`NSPointerFunctionsWeakMemory`模式初始化。

**Comment by tigerAndBull** [comment]
这个情况会在自定义view被塞进生产队列时触发，需要处理

**Comment by tigerAndBull** [comment]
v2.4.6已修复，请确认。

**Comment by tigerAndBull** [comment]
@jiasongs 新版本做了修复，需要你验证下。

**Comment by jiasongs** [comment]
> @jiasongs 新版本做了修复，需要你验证下。

没有问题

**Comment by tigerAndBull** [comment]
2.4.7更换成了NSPointerArray
