### ISSUE TITLE
奔溃

### ISSUE THREAD

**Issue by ZClee128** [tigerAndBull/TABAnimated#101]
请求完数据出现奔溃现象
- (void)_productWithTargetView:(UIView *)targetView isCard:(BOOL)isCard这个方法
![image](https://user-images.githubusercontent.com/18162711/91036340-bdcbdd00-e639-11ea-8f72-808b15f22f35.png)
请看下，这个问题很严重

**Comment by tigerAndBull** [comment]
图片加载不了

**Comment by ZClee128** [comment]
就是奔溃到我复制的那个bughttps://user-images.githubusercontent.com/18162711/91036340-bdcbdd00-e639-11ea-8f72-808b15f22f35.png

**Comment by ZClee128** [comment]
https://user-images.githubusercontent.com/18162711/91036340-bdcbdd00-e639-11ea-8f72-808b15f22f35.png

**Comment by tigerAndBull** [comment]
提供具体堆栈

**Comment by ZClee128** [comment]
不是必现的，偶尔出现，这个堆栈信息没有，全局断点就到这里，我看不到信息

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/91037617-e48b1300-e63b-11ea-8c2e-65464e1a5552.png)
又出现了

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/91037754-24ea9100-e63c-11ea-9ba6-984807d9625c.png)
结合qmui使用

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/91037813-3cc21500-e63c-11ea-8d4a-d53830e90ab8.png)

**Comment by ZClee128** [comment]
这些堆栈够了吧，现在出现频率还挺高，希望大神解决下

**Comment by tigerAndBull** [comment]
暂时没有时间，处理不了

**Comment by ZClee128** [comment]
这么尴尬，那等你有时间

**Comment by tigerAndBull** [comment]
v2.4.6已修复，请确认。

**Comment by tigerAndBull** [comment]
@ZClee128 新版本做了修复，需要你验证下。

**Comment by ZClee128** [comment]
我这边更新了最新版本，目前好像没出现了，应该是解决了，如果再出问题，我再激活这个bug咯
