### ISSUE TITLE
xib不在mainBundle就无法使用

### ISSUE THREAD

**Issue by jnckjian** [tigerAndBull/TABAnimated#102]
关键代码把[NSBundle mainBundle]替换成[NSBundle bundleForClass: class]，什么时候更新一下？

**Comment by jnckjian** [comment]
关键代码把[NSBundle mainBundle]替换成[NSBundle bundleForClass: class]

**Comment by tigerAndBull** [comment]
v2.4.6已修复，请确认。

**Comment by jnckjian** [comment]
think
