### ISSUE TITLE
swift如何调用manager.animation(0).height(12).width(110);

### ISSUE THREAD

**Issue by NimoZone** [tigerAndBull/TABAnimated#104]
请问swift怎么使用manager.animation(0).height(12).width(110);

**Comment by mrtian2016** [comment]
去找其他issue

**Comment by tigerAndBull** [comment]
看下 #64

**Comment by NimoZone** [comment]
> 看下[＃64](https://github.com/tigerAndBull/TABAnimated/issues/64)

3QU
