### ISSUE TITLE
求教swift调用时,链式语法如何玩哦?

### ISSUE THREAD

**Issue by crazypoo** [tigerAndBull/TABAnimated#105]
求教swift调用时,链式语法如何玩哦?

**Comment by tigerAndBull** [comment]
看下＃64



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FrokingMonkey <notifications@github.com&gt;
发送时间: 2020年9月7日 13:47
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 求教swift调用时,链式语法如何玩哦? (#105)





 
求教swift调用时,链式语法如何玩哦?

**Comment by crazypoo** [comment]
没有64哦
