### ISSUE TITLE
求教，tableviewcell 设置缩进怎么只第一条生效

### ISSUE THREAD

**Issue by ieliwb** [tigerAndBull/TABAnimated#106]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-12 at 13 43 50](https://user-images.githubusercontent.com/2177409/92988449-34a01b80-f4fe-11ea-8b19-3a074380ee2c.png)

UITableViewCell通过下面的设置了内部缩进，弄圆角卡片效果，怎么骨架屏只第一条是正常的，后面的失效了，见上图

2.4.3好像是好的，后面几个更新版本都不正常，大佬是改了什么东西，可以修复下吗

- (void)setFrame:(CGRect)frame
{
    frame.size.height -= 12;
    frame.origin.x += 12;
    frame.origin.y += 12;
    frame.size.width -= 24;
    [super setFrame:frame];
}

**Comment by tigerAndBull** [comment]
你先用旧版吧，我看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tigerAndBull/TABAnimated"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月12日(星期六) 中午1:48
收件人:&nbsp;"tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tigerAndBull/TABAnimated] 求教，tableviewcell 设置缩进怎么只第一条生效 (#106)





 

 
UITableViewCell通过下面的设置了内部缩进，弄圆角卡片效果，怎么骨架屏只第一条是正常的，后面的失效了，见上图
 
2.4.3好像是好的，后面几个更新版本都不正常，大佬是改了什么东西，可以修复下吗
  
(void)setFrame:(CGRect)frame
 {
 frame.size.height -= 12;
 frame.origin.x += 12;
 frame.origin.y += 12;
 frame.size.width -= 24;
 [super setFrame:frame];
 }

**Comment by ieliwb** [comment]
好的，谢谢，更正一下，2.2.5版本是好的，2.3.0+好像都不正常

**Comment by tigerAndBull** [comment]
好的，我看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tigerAndBull/TABAnimated"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月12日(星期六) 下午3:18
收件人:&nbsp;"tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com&gt;;
抄送:&nbsp;"安文虎"<1429299849@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tigerAndBull/TABAnimated] 求教，tableviewcell 设置缩进怎么只第一条生效 (#106)





 
好的，谢谢，更正一下，2.2.5版本是好的，2.3.0+好像都不正常

**Comment by zhangyanlf** [comment]
请问这个问题现在解决了吗 ？ 我用的2.4.9有这个问题   但用2.2.5后 2.4.9设置的样式会出现问题。大佬能在新版本解决这个问吗 ？

**Comment by janicezhw** [comment]
> 好的，谢谢，更正一下，2.2.5版本是好的，2.3.0+好像不太正常

你解决了吗？ 我也遇到这个问题

**Comment by ieliwb** [comment]
> > 好的，谢谢，更正一下，2.2.5版本是好的，2.3.0+好像不太正常
> 
> 你解决了吗？ 我也遇到这个问题

没有，将就凑合着用，哎

**Comment by janicezhw** [comment]
> > > 好的，谢谢，更正一下，2.2.5版本是好的，2.3.0+好像不太正常
> > 
> > 
> > 你解决了吗？ 我也遇到这个问题
> 
> 没有，将就凑合着用，哎

https://github.com/Juanpe/SkeletonView  我试了试这个库，Swift的，没出现这个问题，效果还可以的。你也可以试试。

**Comment by tigerAndBull** [comment]
2.2.5之后，采用完全复用机制，不支持重写frame的cell集成骨架屏，后续也不会做处理。
