### ISSUE TITLE
iOS14，占位图下标错误

### ISSUE THREAD

**Issue by NimoZone** [tigerAndBull/TABAnimated#107]
TABAnimated2.4.5，iOS14上面占位图下标错误
在i0S14上占位图下标是0，而14以下的系统是3
截图地址：[http://chuantu.xyz/t6/741/1600400080x-1404750038.png](url)

**Comment by tigerAndBull** [comment]
图片看不了，提供具体的demo

**Comment by tigerAndBull** [comment]
用一下最新master分支的代码看看

**Comment by laurivers** [comment]
请看一下是不是和这个问题重复 #96 @NimoZone

**Comment by tigerAndBull** [comment]
> 请看一下是不是和这个问题重复 #96 @NimoZone

2.4.7已经改了
