### ISSUE TITLE
UILabel换行重叠

### ISSUE THREAD

**Issue by lumianie** [tigerAndBull/TABAnimated#108]
第一个UILabel设置numberOfLines = 2,下一个UIlabel距离它底部一定距离，使用默认动画就会出现第一个Label的第二行和第二个label重叠的情况
![IMG_40892C034725-1](https://user-images.githubusercontent.com/15768042/93729434-081f8a00-fbf7-11ea-846d-43feb8f9633f.jpeg)

**Comment by tigerAndBull** [comment]
符合预期，需要手动调整


------------------ 原始邮件 ------------------
发件人: lumianie <notifications@github.com&gt;
发送时间: 2020年9月21日 10:42
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] UILabel换行重叠 (#108)
