### ISSUE TITLE
使用这个框架，发现没有显示出来的cell在滑动的过程中会有一个阴影背景消失的情况，这种情况能避免么

### ISSUE THREAD

**Issue by forestfsl** [tigerAndBull/TABAnimated#109]

**Comment by tigerAndBull** [comment]
提供具体场景



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 冯宋林 <notifications@github.com&gt;
发送时间: 2020年9月22日 14:40
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 使用这个框架，发现没有显示出来的cell在滑动的过程中会有一个阴影背景消失的情况，这种情况能避免么 (#109)

**Comment by forestfsl** [comment]
首页界面是一个tableView，tableView里面有10个cell，cell中嵌套collectionView，没有获取到图片数据的时候，骨架图正常显示，拿到数据之后刷新页面，前面3个cell在手机上面能直接看到，没有一个阴影的，但是滑到第四个cell的时候，阴影闪了一下，然后消失了，数据能正常显示，不知道这个背景阴影是动画还是什么东西，能关闭么

**Comment by laurivers** [comment]
麻烦看一下是不是和 #96 重复的问题 @forestfsl

**Comment by tigerAndBull** [comment]
这个问题目前是否有新的进展？
