### ISSUE TITLE
debug模式跑代码，TAB动画加载出现，没有任何问题，打包ipa装包后，TAB动画只有第一次进入VC时出现，后面都不出来啦

### ISSUE THREAD

**Issue by honers** [tigerAndBull/TABAnimated#110]
TAB版本：2.4.7
复现率：100%
描述：debug模式跑代码，TAB动画加载出现，没有任何问题，打包ipa后装机，在对应界面TAB动画只有第一次进入出现，然后退出进入，不会再出现

**Comment by tigerAndBull** [comment]
为什么关闭了？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: honers <notifications@github.com&gt;
发送时间: 2020年9月24日 11:26
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] debug模式跑代码，TAB动画加载出现，没有任何问题，打包ipa装包后，TAB动画只有第一次进入VC时出现，后面都不出来啦 (#110)





 
Closed #110.
