### ISSUE TITLE
2.4.7cell自适应问题

### ISSUE THREAD

**Issue by SunQiDreamer** [tigerAndBull/TABAnimated#111]
适配ios14,更新了2.4.7，cell自适应出现了问题，cell都是44了，cell里面又套了一层view,然后再布局的其他控件

**Comment by tigerAndBull** [comment]
> 适配ios14,更新了2.4.7，cell自适应出现了问题，cell都是44了，cell里面又套了一层view,然后再布局的其他控件

是2.4.7导致了自适应高度问题，还是iOS14

**Comment by tigerAndBull** [comment]
内部自测是没啥问题的，需要你提供具体的环境，最好有demo。
