### ISSUE TITLE
swift多section设置animatedCount无效

### ISSUE THREAD

**Issue by RedBluePeas** [tigerAndBull/TABAnimated#112]
感谢您的三方，很好用
项目使用swift，在最新的2.4.7版本中，遇到多section设置animatedCount无效的问题，期望获得您的帮助，以下是demo
[TestTABAnimated.zip](https://github.com/tigerAndBull/TABAnimated/files/5353047/TestTABAnimated.zip)

**Comment by tigerAndBull** [comment]
使用方式不当，当section > 1 时必须使用代理配置高度

```
func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 130
    }
```

![image](https://user-images.githubusercontent.com/28705454/95578092-de26ee00-0a65-11eb-99a1-a411d2aefc1d.png)
![image](https://user-images.githubusercontent.com/28705454/95578104-e2eba200-0a65-11eb-88e6-5f1fd52e43cb.png)

**Comment by RedBluePeas** [comment]
感谢您的解答，不过不好意思，我的疑问是多section设置animatedCount无效，我设置了animatedCount是1，但是动画中显示的cell出现了很多，我重新上传了代码，帮忙再看看？
[TestTABAnimated 2.zip](https://github.com/tigerAndBull/TABAnimated/files/5356107/TestTABAnimated.2.zip)

```
tableView.tabAnimated = TABTableAnimated(cellClassArray: [TestTableViewCell.self, TestTableViewCell.self], 
cellHeightArray: [130, 130], animatedCount: [1, 1])
tableView.tab_startAnimation()
```
![image](https://user-images.githubusercontent.com/18361763/95605851-1ccf9f00-0a8c-11eb-8a7d-45b229437b05.png)

**Comment by tigerAndBull** [comment]
因为tableView的estimatedRowHeight为-1，造成了一个错误判断。
在未发布版本前，你需要使用这个本地版本
[TABAnimated.zip](https://github.com/tigerAndBull/TABAnimated/files/5356339/TABAnimated.zip)

**Comment by tigerAndBull** [comment]
刚刚推送了修复版本到master，如果你需要pod版本，需要等待2.2.8发布。

**Comment by RedBluePeas** [comment]
2.4.8发布吧？

**Comment by tigerAndBull** [comment]
暂时不会



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by tigerAndBull** [comment]
你可以将tableView的estimatedRowHeight设置为0，就不会出错了，也不需要升级

**Comment by RedBluePeas** [comment]
恩，非常感谢
