### ISSUE TITLE
2.4.7使用tableview会闪退，使用2.2.5不会有问题

### ISSUE THREAD

**Issue by Alamoalone** [tigerAndBull/TABAnimated#114]
#import "IndexHeaderCell.h"
#import "IndexListCell.h"

static NSString * IndexHeaderCellId = @"IndexHeaderCell";
static NSString * IndexListCellId = @"IndexListCell";
@interface IndexRootVC ()<UITableViewDataSource,UITableViewDelegate>

@property (nonatomic, strong) UITableView * orderListTableView;
@property (nonatomic, strong) NSMutableArray * listArr;

@end

@implementation IndexRootVC

- (void)viewDidLoad {
    [super viewDidLoad];
    [self.view addSubview:self.orderListTableView];
    [self.orderListTableView tab_startAnimationWithCompletion:^{
        [self refreshData];
    }];
}

- (void)reloadNetWork{
    [self refreshData];
}

#pragma mark 设置导航栏
- (void)setUpNaviView{
    self.isShowNavi = NO;
    self.isShowBack = NO;
    self.naviTypeCode = 0;
    self.vcTitle = @"";
}

#pragma mark Lazyload
- (NSMutableArray *)listArr{
    if (!_listArr) {
        _listArr = [NSMutableArray array];
    }
    return _listArr;
}

- (UITableView *)orderListTableView{
    if (!_orderListTableView) {
        _orderListTableView = [[UITableView alloc]initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, [AAUtils contentHeight] - 49) style:UITableViewStylePlain];
        _orderListTableView.delegate = self;
        _orderListTableView.dataSource = self;
        _orderListTableView.separatorStyle = UITableViewCellSeparatorStyleNone;
        _orderListTableView.backgroundColor = [UIColor whiteColor];
        _orderListTableView.showsVerticalScrollIndicator = NO;
        _orderListTableView.estimatedSectionFooterHeight = 0;
        _orderListTableView.estimatedSectionHeaderHeight = 0;
        _orderListTableView.tabAnimated = [TABTableAnimated animatedWithCellClassArray:@[[IndexHeaderCell class],[IndexListCell class]] cellHeightArray:@[@145,@64] animatedCountArray:@[@1,@10]];
//        _orderListTableView.mj_header = [AARefreshHeader headerWithRefreshingTarget:self refreshingAction:@selector(refreshData)];
//        _orderListTableView.mj_footer = [AARefreshFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreData)];
    }
    return _orderListTableView;
}

#pragma mark UITableViewDataSource
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView{
    return 2;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
    if (section == 0) {
        return 1;
    }
    return self.listArr.count;
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    if (indexPath.section == 0) {
        return 145;
    }
    return 64;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{
    if (indexPath.section == 0) {
        IndexHeaderCell * headerCell = [tableView dequeueReusableCellWithIdentifier:IndexHeaderCellId forIndexPath:indexPath];
        if (!headerCell) {
            NSArray *cellArray = [[NSBundle mainBundle] loadNibNamed:@"IndexHeaderCell" owner:self options:nil];
            headerCell = [cellArray objectAtIndex:0];
        }
        return headerCell;
    }
    IndexListCell * listCell = [tableView dequeueReusableCellWithIdentifier:IndexListCellId forIndexPath:indexPath];
    if (!listCell) {
        NSArray *cellArray = [[NSBundle mainBundle] loadNibNamed:@"IndexListCell" owner:self options:nil];
        listCell = [cellArray objectAtIndex:0];
    }
    return listCell;
}

#pragma mark UITableViewDelegate
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
    
}

#pragma mark 网络请求
- (void)refreshData{
    [self listDataRequestWithIsRefresh:YES];
}

- (void)loadMoreData{
    [self listDataRequestWithIsRefresh:NO];
}

- (void)listDataRequestWithIsRefresh:(BOOL)isRefresh{
    [self.listArr removeAllObjects];
    // 模拟数据
    for (int i = 0; i < 20; i ++) {
        [self.listArr addObject:@"test"];
    }
    
    // 停止动画,并刷新数据
    [self.orderListTableView tab_endAnimationEaseOut];
}
代码如上

**Comment by Alamoalone** [comment]
控制台报错如下
![Uploading image.png…]()

**Comment by tigerAndBull** [comment]
图片无效，请提供具体复现场景。
