### ISSUE TITLE
与第三方库QMUI冲突问题

### ISSUE THREAD

**Issue by ZClee128** [tigerAndBull/TABAnimated#121]
![image](https://user-images.githubusercontent.com/18162711/99358246-34e6d980-28e8-11eb-9ccb-03a0923f37d1.png)
出现这个问题

**Comment by tigerAndBull** [comment]
截图我看一下怎么用的


------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月17日 15:19
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 新版本问题2.4.9 (#121)

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/99359173-9b202c00-28e9-11eb-85af-5c18da68d1b9.png)

**Comment by tigerAndBull** [comment]
你把断点走到底，截图我看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月17日 15:29
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 新版本问题2.4.9 (#121)

**Comment by tigerAndBull** [comment]
把断点走到底，然后截图控制台log


------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月17日 15:29
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 新版本问题2.4.9 (#121)

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/99360317-5d240780-28eb-11eb-8769-8ac5ad827706.png)
![image](https://user-images.githubusercontent.com/18162711/99360353-6c0aba00-28eb-11eb-9f53-8c96f73e028e.png)

**Comment by tigerAndBull** [comment]
你先降级吧，我排查下


------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月17日 15:42
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 新版本问题2.4.9 (#121)

**Comment by tigerAndBull** [comment]
其他版本没问题？确认一下




------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月17日 15:42
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 新版本问题2.4.9 (#121)

**Comment by ZClee128** [comment]
好的

**Comment by ZClee128** [comment]
其他版本也有问题，2.4.7之前用这个版本的，不过升级到ios14，好像就有问题了

**Comment by ZClee128** [comment]
奇怪了，我线上的包居然没有问题，但是本地跑的包就有问题

**Comment by ZClee128** [comment]
大概什么时候可以定位到问题呢

**Comment by tigerAndBull** [comment]
还没看，看看是否是第三个方冲突导致



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月17日 16:04
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 新版本问题2.4.9 (#121)





 
大概什么时候可以定位到问题呢

**Comment by ZClee128** [comment]
我感觉是，我还用了腾讯的qmui框架

**Comment by tigerAndBull** [comment]
保持交流，这个问题要查清楚

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月17日 16:06
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 新版本问题2.4.9 (#121)





 
我感觉是，我还用了腾讯的qmui框架

**Comment by ZClee128** [comment]
好的

**Comment by tigerAndBull** [comment]
似乎是QMUI的冲突，你可以试试移除测试一下
![image](https://user-images.githubusercontent.com/28705454/99365569-6f557400-28f2-11eb-8031-5df577bdc7b9.png)

**Comment by ZClee128** [comment]
移除工程量有的大，基类都继承他了

**Comment by tigerAndBull** [comment]
好的，我来测试一下

**Comment by tigerAndBull** [comment]
稍微读了一下QMUI的源码，发现QMUI对于UITableView高度相关的，有管理你tableView代理的痕迹，应该有关系。

**Comment by tigerAndBull** [comment]
你的tableView的基类是QMUI的？还是用了UITableView+QMUI分类？还是用了QMUITableViewController？

**Comment by tigerAndBull** [comment]
我需要复现一下你的场景，你可以跟我详细说明一下

**Comment by ZClee128** [comment]
UITableView+QMUI用了这个

**Comment by ZClee128** [comment]
你没有问题吗

**Comment by ZClee128** [comment]
我用的tableview是继承QMUITableView这个，其他没有，然后就简单的注册了列表，然后就我截图的加载方式

**Comment by ZClee128** [comment]
QMUIKit (4.2.1)版本号用的是这个

**Comment by ZClee128** [comment]
大神怎么样了，有解决办法吗

**Comment by tigerAndBull** [comment]
别急，今明两天看下




------------------ 原始邮件 ------------------
发件人: ZClee <notifications@github.com&gt;
发送时间: 2020年11月20日 18:05
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 与第三方库QMUI冲突问题 (#121)





 
大神怎么样了，有解决办法吗

**Comment by tigerAndBull** [comment]
我用的4.1.3无法复现，因为我的电脑配置比较低，目前更新最新系统太卡了，我降级了，4.2.1最近应该没法看了。

**Comment by tigerAndBull** [comment]
如果有问题你就下掉这个库吧，应该还是hook多次的问题。如果是这个问题，也是没办法解决的，hook的第三方库只能二选一

**Comment by ZClee128** [comment]
哦，好的

**Comment by lanligang** [comment]
我，觉得应该是两个第三方对代理的重复hook 出现的问题，也就是说用A进行一次hook 后不能再使用B进行hook 否则会出现问题。只能按作者说的 二选一。

**Comment by lanligang** [comment]
我看到有很多hook 来做的，是不是可以这样做，在动画的时候和动画结束后进行切换代理来实现，这样就避免了不必要的  因为hook 导致的其他想hook 的不能用的问题

**Comment by tigerAndBull** [comment]
不可以



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by lanligang** [comment]
@tigerAndBull  hook  使用 Aspects  这个插件进行操作是否可以避免呢？使用最新版本的。

**Comment by tigerAndBull** [comment]
还有冲突吗？

**Comment by tigerAndBull** [comment]
v2.5.2已适配第三方库，如QMUI，RxSwift.
