### ISSUE TITLE
目前骨架屏是不是还不能直接支持瀑布流模式的样式。

### ISSUE THREAD

**Issue by weizhangCoder** [tigerAndBull/TABAnimated#122]
目前骨架屏是不是还不能直接支持瀑布流模式的样式。有没有比较好的解决办法

**Comment by tigerAndBull** [comment]
可以支持，但是需要考虑一下interface的形态。
你的瀑布流是用的某个轮子，还是自己写的？

**Comment by tigerAndBull** [comment]
正常的逻辑下，骨架屏不识别布局计算规则，是可以实现的

**Comment by weizhangCoder** [comment]
瀑布流用的是LMJVerticalFlowLayout 这个轮子。如果退而求其次，骨架屏不展示瀑布流，展示一个2边相等的cell 感觉也是可以的.我用这个方法试了下。+ (instancetype)animatedWithCellClass:(Class)cellClass
                             cellSize:(CGSize)cellSize; 直接奔溃在我的LMJVerticalFlowLayout 这个方法里面了
<img width="710" alt="image" src="https://user-images.githubusercontent.com/11644326/100214148-790e5580-2f4a-11eb-8254-09e252ae790a.png">

**Comment by tigerAndBull** [comment]
崩不崩的不是问题所在。
如果是退而求其次，你可以在动画前使用UICollectionFlowLayout，在动画结束后使用LMJVerticalFlowLayout。

**Comment by tigerAndBull** [comment]
这是新的瀑布流方案，还未发布，你可以看一下这个demo，能满足预期不
[TABAnimatedDemo-master.zip](https://github.com/tigerAndBull/TABAnimated/files/5727780/TABAnimatedDemo-master.zip)

**Comment by tigerAndBull** [comment]
2.5.1已支持
