### ISSUE TITLE
swift 中使用remove 没有作用, 移除不了

### ISSUE THREAD

**Issue by cleven1** [tigerAndBull/TABAnimated#123]
### New Issue Checklist

* [x] I have read the [Documentation](https://github.com/tigerAndBull/TABAnimated/tree/master/Documents)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/TABAnimated/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          iOS
 Platform Version       14.0
 TABAnimated Version     2.4.7
 Xcode Version          Xcode 12

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by tigerAndBull** [comment]
能提供具体的测试demo吗，swift我们会测试的比较少

**Comment by cleven1** [comment]
collectionView.tabAnimated?.adjustBlock = { [weak self] manager in
                guard let self = self, let animation = manager.animation() else { return }
                animation(1)?.width()(self.skeletonTitleW)
                animation(2)?.width()(self.skeletonDetailW)
                animation(3)?.width()(0.1)
                animation(4)?.width()(0.1)
            }

我现在是使用width==0.1来移除

**Comment by cleven1** [comment]
在swift中除了initWithShimmerAnimated有动画效果外, 其它的都没有动画效果,都是静止的,  这个是什么原因呢???

**Comment by tigerAndBull** [comment]
提供具体demo，否则无法定位



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cleven <notifications@github.com&gt;
发送时间: 2020年12月8日 16:02
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] swift 中使用remove 没有作用, 移除不了 (#123)





 
在swift中除了initWithShimmerAnimated有动画效果外, 其它的都没有动画效果,都是静止的,  这个是什么原因呢???

**Comment by tigerAndBull** [comment]
记录：今天又有人反馈这个问题了，抽时间看下

**Comment by shxlxa** [comment]
我也遇到了swift中不能移除的问题，就是常规的tableview

**Comment by tigerAndBull** [comment]
写法不对,
这样写
$0.animation()?(0)?.remove()()
@shxlxa @cleven1
