### ISSUE TITLE
改变_tableView.tableHeaderView 里面的元素颜色，没有效果。

### ISSUE THREAD

**Issue by weizhangCoder** [tigerAndBull/TABAnimated#124]
按照文档里面说的方式添加了tableHeaderView 的骨架屏回调，但是改变颜色不管用，用的是demo tableView里面第二个修改的
<img width="780" alt="image" src="https://user-images.githubusercontent.com/11644326/100971825-9d81b780-3572-11eb-80f2-e9c6579dfac0.png">

**Comment by tigerAndBull** [comment]
发现是新版本bug，不好意思。

**Comment by tigerAndBull** [comment]
需要确认2.5.1是否生效

**Comment by zxd2997910686** [comment]
我下载最新的设置颜色也不起作用，这个需要适配app的多主题应该怎么设置

**Comment by tigerAndBull** [comment]
tabAnimated.tabHeaderAnimated
