### ISSUE TITLE
无法修改元素颜色

### ISSUE THREAD

**Issue by weizhangCoder** [tigerAndBull/TABAnimated#125]
<img width="804" alt="WeChatb6d8b667a11835912876b6cea459911f" src="https://user-images.githubusercontent.com/11644326/100982017-877bf300-3582-11eb-931e-54a62317d0d4.png">（修改后的效果）
<img width="689" alt="WeChat22c43c81884afeed138d987116b2dac5" src="https://user-images.githubusercontent.com/11644326/100982091-9c588680-3582-11eb-96e3-4b0d02cd51b2.png">（代码效果）

修改的颜色有问题

**Comment by tigerAndBull** [comment]
嵌套视图是指内部存在UITableView和UICollectionView



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weizhang <notifications@github.com&gt;
发送时间: 2020年12月3日 16:13
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 想改变tableView 的tableHeaderView（这个里面有嵌套视图）里面子控件的颜色，有问题 (#125)

**Comment by weizhangCoder** [comment]
但修改的15和8 只是添加在tableHeaderView上面了。没有添加在嵌套的UICollectionView里面，修改的颜色8 边框会变，15 的四个角颜色会变。

**Comment by tigerAndBull** [comment]
可能是堆叠了，方便提供一份demo吗？

**Comment by weizhangCoder** [comment]
我这个控件，里面有点多，还不太好拆出一份demo ,我试了下。你项目中简单是可以改变颜色的。我再自己调试下

**Comment by tigerAndBull** [comment]
我的意思有可能存在层级覆盖


------------------ 原始邮件 ------------------
发件人: weizhang <notifications@github.com&gt;
发送时间: 2020年12月7日 14:40
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 想改变tableView 的tableHeaderView（这个里面有嵌套视图）里面子控件的颜色，有问题 (#125)





 
我这个控件，里面有点多，还不太好拆出一份demo ,我试了下。你项目中简单是可以改变颜色的。我再自己调试下

**Comment by weizhangCoder** [comment]
大概摸索出来一点原因了在这记录下。
1 第一个问题，demo里面自定义View的豆瓣展示效果，如果是闪光灯模式，改变元素的颜色不起作用
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/11644326/101731427-9587c180-3af6-11eb-99d8-39d3227ad5f0.png">

2 第二个问题，是下面创建动画的写法和第一个写法有什么区别，感觉是一样的，但是用起来不一样，
<img width="797" alt="image" src="https://user-images.githubusercontent.com/11644326/101731996-763d6400-3af7-11eb-9d06-4c843cea9e79.png">

这2个是自己做实验得出的结论，请教下这个问题出在哪里。

**Comment by tigerAndBull** [comment]
1. 闪光灯是覆盖动画，不支持改颜色，仅支持调深浅度，无法从灰色变成蓝色，绿色等等。
2. 两种只是优先级有区别，不能改变颜色大概率还是上面的原因

**Comment by weizhangCoder** [comment]
感谢作者，回复太快了，我还说删除了，在测试准确点在写上去，就得到答案了，
 如果全局写成 这个闪光灯类型。
 [[TABAnimated sharedAnimated] initWithShimmerAnimated];
再次设置更高优先级的类型的时候。  都是失效的。
TABViewAnimated *viewAnimated = TABViewAnimated.new;
 viewAnimated.superAnimationType = TABAnimationTypeDrop;

**Comment by tigerAndBull** [comment]
viewAnimated.superAnimationType = TABAnimationTypeDrop;
superAnimationType的动画类型是另一个枚举。

**Comment by weizhangCoder** [comment]
确实用错类别的。大意了。那问题就明白了，我刚开始用的就是闪光灯的类型，所以改不了颜色。

**Comment by tigerAndBull** [comment]
PS: 如果想在使用闪光灯，局部可以修改颜色，可以这么做：
animation(x).withoutAnimation().color(xxx);

**Comment by weizhangCoder** [comment]
收到，试了下可以的。当时用一个图片给代替了。
