### ISSUE TITLE
2.4.9版本 真机上显示没有问题，模拟器显示没有移除元素。

### ISSUE THREAD

**Issue by weizhangCoder** [tigerAndBull/TABAnimated#126]
看记录2.4.8 有一个manager.animationsWithIndexs(2,3,4,5,6,7,8,10,9,11,12).remove(); 这个属性，不能生效，在2.4.9显示修复了，在真机上尝试是可以的，但是模拟器上依然是显示不能移除。

模拟器 测试结果，单个移除，没有问题
<img width="365" alt="WeChat3d766fb6837a7f5dd9cf401d9b2b5376" src="https://user-images.githubusercontent.com/11644326/101318077-adfba000-389a-11eb-946a-7ff08aecba80.png">

统一移除，真机上测试没有问题，模拟器显示有问题
 manager.animationsWithIndexs(2,3,4,5,6,7,8,10,9,11,12).remove();

<img width="370" alt="WeChat92282e683326e41a16a5a9edc2a82aca" src="https://user-images.githubusercontent.com/11644326/101318262-003cc100-389b-11eb-9336-ea16929fc898.png">

**Comment by tigerAndBull** [comment]
我测试是有效的，复现不了

**Comment by tigerAndBull** [comment]
如果这个接口用起来有问题，建议换成单个的，或者适用过滤条件快速过滤。

**Comment by weizhangCoder** [comment]
好
