### ISSUE TITLE
2.4.9修改的TABTableAnimated文件，导致崩溃

### ISSUE THREAD

**Issue by powfulhong** [tigerAndBull/TABAnimated#127]
2.4.9版本修改的TABTableAnimated文件中的方法
\- (NSInteger)tab_tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section，
先执行了NSInteger originCount = [self tab_tableView:tableView numberOfRowsInSection:section];
假如我自己的section是动态的，由array确定，而numberOfRows又用到该array，这里就可能会出现数组越界的崩溃

**Comment by tigerAndBull** [comment]
假设你数组是动态的，那么返回数为0，为什么会崩溃呢？

**Comment by powfulhong** [comment]
如果只是用array.count，是不会崩溃，但如果用到类似array[section]来获取其他信息，就可能出现越界

**Comment by tigerAndBull** [comment]
那是你的逻辑不够严谨，这个你需要自行处理

**Comment by powfulhong** [comment]
不对啊，numberOfSectionsInTableView中是由sectionArray决定个数，sectionArray是动态设定的，里面存储一些信息用来确定这个section的row的个数，那numberOfRowsInSection就得用这个sectionArray[section]来获取吧。。

**Comment by tigerAndBull** [comment]
你是崩溃在什么地方？你自己的函数里吧？

**Comment by powfulhong** [comment]
崩溃在NSInteger originCount = [self tab_tableView:tableView numberOfRowsInSection:section];这里调用的是我这边的numberOfRowsInSection，但这个方法里有用到sectionArray[section]，骨架的时候，sectionArray还是空的，但我设置的animatedSectionCount=3，所以越界了

**Comment by tigerAndBull** [comment]
2.6.1 fix
