### ISSUE TITLE
今天下载的2.5.1版本tableview创建 刷新cell 的代理和cell高度的代理不走,其他代理可以调用,所有的demo的展示都刷新不了数据,现在不知道怎么使用了

### ISSUE THREAD

**Issue by 15949893621** [tigerAndBull/TABAnimated#130]
### New Issue Checklist

* [ ] I have read the [Documentation](https://github.com/tigerAndBull/TABAnimated/tree/master/Documents)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/TABAnimated/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. iOS / macOS
 Platform Version        | e.g. 12.0 / 10.14.0
 TABAnimated Version      | e.g. 5.0.0 / 4.4.0
 Xcode Version           | e.g. Xcode 11 / Xcode 10
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by tigerAndBull** [comment]
demo有异常吗



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by 15949893621** [comment]
是的 我运行的就是demo,没有数据出现,3秒后还是一片空白,断点查看 就是代理没有走,,是需要使用方法交换吗?可是你们的demo里没有一个有写到这个的,所有的展示demo都刷不出数据了

**Comment by tigerAndBull** [comment]
那就降级用2.5.0



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by tigerAndBull** [comment]
这不是2.5.1的bug，是2.5.2_dev的bug，已修复了，你拉去最新的master代码即可。
pod上的2.5.1不会被影响。

**Comment by 15949893621** [comment]
好的谢谢
