### ISSUE TITLE
卡片式卡片背景不显示问题

### ISSUE THREAD

**Issue by kai-liu** [tigerAndBull/TABAnimated#131]
demo中子视图直接添加到cell上没问题，但是添加到cell.contentView上，卡片背景就不显示了，但用xib只能添加到contenView上，openAnimationTag开启后，添加到contenView的卡片view没有任何下标显示

tableView.tabAnimated.adjustBlock使用时，有个别控件不显示，就算block不做任何操作也一样

**Comment by tigerAndBull** [comment]
提供异常环境，卡片实现有很多种，如果你实现卡片的方式不规范，并不一定适配到你实现卡片的方式

**Comment by tigerAndBull** [comment]
请提供对应的卡片实现方式，否则这个问题即将关闭。

**Comment by tigerAndBull** [comment]
该issue未得到足够信息已关闭，如果后续提供足够信息可以重新打开。
