### ISSUE TITLE
编译时候出现这个问题怎么破

### ISSUE THREAD

**Issue by 295060456** [tigerAndBull/TABAnimated#135]
/Users/jobs/Desktop/科研/TABAnimated-master/TABAnimatedDemo/TABAnimatedDemo.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'TABKit.framework' was built for iOS + iOS Simulator.

**Comment by tigerAndBull** [comment]
这个链接应该可以解决你的问题。
https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built
