### ISSUE TITLE
cell在初始化的时候需要同时初始化控件，否则没有骨架效果

### ISSUE THREAD

**Issue by 295060456** [tigerAndBull/TABAnimated#136]
直接上干货：
我的tableviewcell.m的写法是：
@implementation MKRankTBVCell

+(instancetype)cellWithTableView:(UITableView *)tableView{
    MKRankTBVCell *cell = (MKRankTBVCell *)[tableView dequeueReusableCellWithIdentifier:ReuseIdentifier];
    if (!cell) {
        cell = [[MKRankTBVCell alloc] initWithStyle:UITableViewCellStyleSubtitle
                                    reuseIdentifier:ReuseIdentifier];
//        [UIView cornerCutToCircleWithView:cell andCornerRadius:6];
    }return cell;
}

-(void)richElementsInCellWithModel:(MKRankListModel *_Nullable)model{

}

@end

外界调用：

- (UITableViewCell *)tableView:(UITableView *)tableView
         cellForRowAtIndexPath:(NSIndexPath *)indexPath{
    MKRankTBVCell *tableViewCell = [MKRankTBVCell cellWithTableView:tableView];
    [tableViewCell richElementsInCellWithModel:rankListModel];
    return tableViewCell;
}
##### 以上写法不出效果 #######
而你的正确的写法
需要监听cell里面的
- (instancetype)initWithStyle:(UITableViewCellStyle)style
              reuseIdentifier:(NSString *)reuseIdentifier 方法。意思就是我必须一开始就进init，我很好理解，因为你要约束嘛，几个控件，大概轮廓啊这些；

而且有预估值，必须实现此代理方法：
- (CGFloat)tableView:(UITableView *)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath *)indexPath {
    return 100;
}

#######以上结论亲测有效############

但是我想说，如果按照我那种构架模式，我是有数据，或者在恰当的时候再创建cell的子控件，加载时机的问题，我应该怎么调整？

目前可行的办法就是：

+(instancetype)cellWithTableView:(UITableView *)tableView{
    MKRankTBVCell *cell = (MKRankTBVCell *)[tableView dequeueReusableCellWithIdentifier:ReuseIdentifier];
    if (!cell) {
        cell = [[MKRankTBVCell alloc] initWithStyle:UITableViewCellStyleSubtitle
                                    reuseIdentifier:ReuseIdentifier];
//        [UIView cornerCutToCircleWithView:cell andCornerRadius:6];
    }return cell;
}

- (instancetype)initWithStyle:(UITableViewCellStyle)style
              reuseIdentifier:(NSString *)reuseIdentifier {
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    if (self) {
        [self richElementsInCellWithModel:nil];
    }return self;
}
 
但我并不想这样。我不想在init方法里面创建控件。

**Comment by 295060456** [comment]
哎，不实现
(CGFloat)tableView:(UITableView *)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath *)indexPath {
return 100;
}也可以。但是在某些情况下不行，必须实现，说实在，我讨厌预估值这么个玩意儿

**Comment by tigerAndBull** [comment]
需要在初始化的时候，初始化控件，才可以动态查询到你的控件内容，并且自动化生成
