### ISSUE TITLE
请问能不能添加一个通过AnimationTag来过滤的功能

### ISSUE THREAD

**Issue by evan1009** [tigerAndBull/TABAnimated#137]

**Comment by tigerAndBull** [comment]
目前版本有过滤功能



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by evan1009** [comment]
如果视图比较多，想去掉一些视图，如果用size来过滤的话有些过滤不了

**Comment by tigerAndBull** [comment]
tag过滤？那就是预处理回调里remove



发自我的iPhone


------------------ 原始邮件 ------------------
