### ISSUE TITLE
使用后没有效果

### ISSUE THREAD

**Issue by jolincheng** [tigerAndBull/TABAnimated#138]
PPMainMessageListView *messageView = [[PPMainMessageListView alloc] initWithParentVc:self];
    [self.view addSubview:messageView];
    self.messageView = messageView;
   
    messageView.tabAnimated = TABViewAnimated.new;
    messageView.tabAnimated.containNestAnimation = YES;
    
    
    PPWeakObj(self);
    [messageView tab_startAnimationWithCompletion:^{
        PPStrongObj(self);
        //        [self.manager pp_getNewData];
    }];

上面是控制器的代码

下面是视图的代码

   self.tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[PPConversationMessageListCell class] 
   cellHeight:PPWidth(61) animatedCount:5];

    self.tableView.tabAnimated.animatedBackgroundColor = PPColor(0xffffff);
    self.tableView.tabAnimated.superAnimationType = TABViewSuperAnimationTypeShimmer;
    
    self.tableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
        
    };

**Comment by tigerAndBull** [comment]
只绑定tableView，由tableView开关



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by jolincheng** [comment]
不行，我一开始就是在视图里面的tableview加动画，但是不行，所以我看了说明就弄成这样，也还是不行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tigerAndBull <notifications@github.com&gt;
发送时间: 2021年2月24日 21:15
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: HurryUpCheng <574581685@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 主控制器添加了一个视图,在视图上添加了uitableview,设置了视图的containNestAnimation=yes还是没有动画 (#138)





 只绑定tableView，由tableView开关 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------

**Comment by tigerAndBull** [comment]
1. 检查AppDelegate中是否进行了初始化操作
2. 检查使用版本号是否正确，以及podfile语法 podfile语法强调： 'TABAnimated','~> 1.0.0' 这个意思是pod下来的是 >= 1.0.0的版本， 如果最新是1.0.8，且1.0.0是稳定版本，也会pod下来1.0.8
3. 检查使用流程是否有误，自身代码是否有误
4. 如果你是动态section，请必须指定animatedSectionCount

何为动态section？

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return self.dataArray.count;
}
5. cell中控件必须在init系列方法中初始化
