### ISSUE TITLE
NSInternalInconsistencyException

### ISSUE THREAD

**Issue by VaeBean** [tigerAndBull/TABAnimated#140]
### Issue Info

 Platform Name           | iOS 
 Platform Version        | 12.0
 TABAnimated Version      | e.g. 2.5.2
 Xcode Version           | e.g. Xcode 12.4
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps
Array bound, please check it carefully.

-------------------------------------
Description:

0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | +[_CFXNotificationTokenRegistration keyCallbacks]
3 Foundation | -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
4 TABAnimated | __32-[TABComponentManager animation]_block_invoke + 224
5 TDemo | __31-[UMHomeVC classTableView]_block_invoke_2 + 2640
6 TABAnimated | -[TABAnimatedChainManagerImpl chainAdjustWithArray:adjustBlock:animatedColor:] + 168
7 TABAnimated | -[TABAnimatedProductImpl _chainAdjustWithArray:tabAnimated:targetClass:] + 332
8 TABAnimated | -[TABAnimatedProductImpl _productWithTargetView:isCard:] + 656
9 TABAnimated | __60-[TABAnimatedProductImpl _productWithView:needReset:isCard:]_block_invoke + 496
10 libdispatch.dylib | __dispatch_call_block_and_release + 24
11 libdispatch.dylib | __dispatch_client_callout + 16
12 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$armv81 + 1012
13 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation | ___CFRunLoopRun + 1964
15 CoreFoundation | CFRunLoopRunSpecific + 436
16 GraphicsServices | GSEventRunModal + 100
17 UIKitCore | UIApplicationMain + 212
18 TDemo | main + 172
19 libdyld.dylib | _start + 4

**Comment by tigerAndBull** [comment]
使用index预处理回调越界了，在正式环境有兜底，在本地的话，你自己看下是不是使用了错误的index





发自我的iPhone


------------------ Original ------------------
From: LQJ ***@***.***&gt;
Date: Fri,Mar 19,2021 3:56 PM
To: tigerAndBull/TABAnimated ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [tigerAndBull/TABAnimated] NSInternalInconsistencyException (#140)





 
NSInternalInconsistencyException
 
Issue Info
 
Platform Name           | iOS
 Platform Version        | 12.0
 TABAnimated Version      | e.g. 2.5.2
 Xcode Version           | e.g. Xcode 12.4
 Repro rate              | e.g. all the time (100%)
 
Issue Description and Steps
 
Array bound, please check it carefully.
 
 
Description:
    0&nbsp;CoreFoundation ___exceptionPreprocess&nbsp;+&nbsp;228 
    1&nbsp;libobjc.A.dylib objc_exception_throw&nbsp;+&nbsp;56 
  2&nbsp;CoreFoundation +[_CFXNotificationTokenRegistration keyCallbacks] 
  3&nbsp;Foundation -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]&nbsp;+&nbsp;112 
  4&nbsp;TABAnimated __32-[TABComponentManager animation]_block_invoke&nbsp;+&nbsp;224 
  5&nbsp;TDemo __31-[UMHomeVC classTableView]_block_invoke_2&nbsp;+&nbsp;2640 
  6&nbsp;TABAnimated -[TABAnimatedChainManagerImpl chainAdjustWithArray:adjustBlock:animatedColor:]&nbsp;+&nbsp;168 
  7&nbsp;TABAnimated -[TABAnimatedProductImpl _chainAdjustWithArray:tabAnimated:targetClass:]&nbsp;+&nbsp;332 
  8&nbsp;TABAnimated -[TABAnimatedProductImpl _productWithTargetView:isCard:]&nbsp;+&nbsp;656 
  9&nbsp;TABAnimated __60-[TABAnimatedProductImpl _productWithView:needReset:isCard:]_block_invoke&nbsp;+&nbsp;496 
  10&nbsp;libdispatch.dylib __dispatch_call_block_and_release&nbsp;+&nbsp;24 
  11&nbsp;libdispatch.dylib __dispatch_client_callout&nbsp;+&nbsp;16 
  12&nbsp;libdispatch.dylib __dispatch_main_queue_callback_4CF$VARIANT$armv81&nbsp;+&nbsp;1012 
  13&nbsp;CoreFoundation _CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE&nbsp;+&nbsp;12 
  14&nbsp;CoreFoundation ___CFRunLoopRun&nbsp;+&nbsp;1964 
  15&nbsp;CoreFoundation CFRunLoopRunSpecific&nbsp;+&nbsp;436 
  16&nbsp;GraphicsServices GSEventRunModal&nbsp;+&nbsp;100 
  17&nbsp;UIKitCore UIApplicationMain&nbsp;+&nbsp;212 
  18&nbsp;TDemo main&nbsp;+&nbsp;172 
  19&nbsp;libdyld.dylib _start&nbsp;+&nbsp;4

**Comment by VaeBean** [comment]
我也清楚问题所在，也临时修复了问题，但我发现只有在12.0会出现越界，而别的系统版本不会，so...

**Comment by tigerAndBull** [comment]
我有时间看下



发自我的iPhone


------------------ Original ------------------
From: LQJ ***@***.***&gt;
Date: Mon, Mar 22, 2021 5:50 PM
To: tigerAndBull/TABAnimated ***@***.***&gt;
Cc: tigerAndBull ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [tigerAndBull/TABAnimated] NSInternalInconsistencyException (#140)





 
我也清楚问题所在，也临时修复了问题，但我发现只有在12.0会出现越界，而别的系统版本不会，so...

**Comment by tigerAndBull** [comment]
能够提供一下这个cell？

**Comment by tigerAndBull** [comment]
2.6.0已修复
