### ISSUE TITLE
实现了tableview的代理方法,tableView.tabAnimated也必须要实现相应的方法？

### ISSUE THREAD

**Issue by DotaAntiMagic** [tigerAndBull/TABAnimated#141]
你好,tableview实现了viewForHeaderInSection,heightForHeaderInSection,heightForFooterInSection但是没有实现viewForFooterInSection,现在用这个骨架框架必须要实现addFooterViewClass,不然就会崩溃,有没有办法tableview实现了header或者footer的代理,但是tableView.tabAnimated不需要再初始化addHeaderViewClass或者addFooterViewClass?

**Comment by tigerAndBull** [comment]
不需要，这个master的代码为了兼容QMUI，但是没有完善，已经回滚了，重新尝试使用2.5.1即可

**Comment by DotaAntiMagic** [comment]
我用的就是2.5.1的版本,现在就是tableview里面实现了viewForHeaderInSection,heightForHeaderInSection,heightForFooterInSection,然后    _tableView.tabAnimated =[TABTableAnimated animatedWithCellClass:[testCell class] cellHeight:40];
    _tableView.tabAnimated.animatedSectionCount = 2;
    _tableView.tabAnimated.animatedCount = 4;
    [self.tableView tab_startAnimationWithCompletion:^{
    }];
    _tableView.tabAnimated.superAnimationType = TABViewSuperAnimationTypeShimmer;
    [self.tableView tab_startAnimation];
运行直接就崩溃了
![image](https://user-images.githubusercontent.com/13567812/111970216-05660900-8b36-11eb-9df3-abea329a75e1.png)
![image](https://user-images.githubusercontent.com/13567812/111970251-0e56da80-8b36-11eb-8cc6-180148ef40a1.png)

**Comment by DotaAntiMagic** [comment]
> 不需要，这个master的代码为了兼容QMUI，但是没有完善，已经回滚了，重新尝试使用2.5.1即可

**Comment by DotaAntiMagic** [comment]
找到原因了,是我代码本身的原因,不好意思
