### ISSUE TITLE
急急急!!!!  今晚上线  项目用了你的框架,,,tableiview的 style 设置的sectionview不吸顶了

### ISSUE THREAD

**Issue by ke112** [tigerAndBull/TABAnimated#145]
tableview style 初始化时  设置的 UITableViewStylePlain,,然后在

- (void)scrollViewDidScroll:(UIScrollView *)scrollView{
    CGFloat offy = scrollView.contentOffset.y;
    self.offy = offy;
    CGFloat alpha = MIN(offy/self.searchView.height, 1);
//    NSLog(@"alpha : %.2f",alpha);
    self.searchView.backgroundColor = [[UIColor whiteColor] colorWithAlphaComponent:alpha];
    
    BOOL isBlackModel = offy >= self.searchView.height;
    self.searchView.isBlackModel = isBlackModel;
    if (isBlackModel) {
        [UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleDefault;
    } else {
        [UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleLightContent;
    }
    if (offy < self.headerView.height-kNavAndStatusHight-20) {
        self.tableView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
    } else {
        self.tableView.contentInset = UIEdgeInsetsMake(self.searchView.height, 0, 0, 0);
    }
    
}

现在这个delegate 都不可以走了...请问是为什么

**Comment by tigerAndBull** [comment]
待会发个补丁包给你

**Comment by tigerAndBull** [comment]
你的场景有点特殊，动画运行中是否需要吸顶？
我可能还需要多给你配置参数

**Comment by ke112** [comment]
在滚动过程中,需要根据偏移量设置  tableview的 contentInset , 但是现在 - (void)scrollViewDidScroll:(UIScrollView *)scrollView  代理方法就不走,不知道怎么回事 ,是不是得掉你的某个 代理方法,同系统这个代理方法 ?

**Comment by tigerAndBull** [comment]
OK了。用github最新的develop分支代码

**Comment by ke112** [comment]
好的,谢谢

**Comment by ke112** [comment]
可以了 老大 !!!   🐂  B      pod 可以更新吗

**Comment by ke112** [comment]
<img width="795" alt="WX20210414-172638@2x" src="https://user-images.githubusercontent.com/45870862/114687719-99e31600-9d46-11eb-9568-2d55cc0d23ee.png">

![IMG_0294](https://user-images.githubusercontent.com/45870862/114687887-c1d27980-9d46-11eb-9d88-973f74d3919e.PNG)


请问我这么写,, 为什么会变成这样,不应该只加载cell吗  而且固定的3个就可以了, headerview 都替我加载了

**Comment by tigerAndBull** [comment]
api里有showHeaderView



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: don ***@***.***&gt;
发送时间: 2021年4月14日 17:29
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Assign ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] 急急急!!!!  今晚上线  项目用了你的框架,,,tableiview的 style 设置的sectionview不吸顶了 (#145)





 

 

 
请问我这么写,, 为什么会变成这样,不应该只加载cell吗  而且固定的3个就可以了, headerview 都替我加载了

**Comment by tigerAndBull** [comment]
2.5.4已修复，如有问题，可以重新打开。
