### ISSUE TITLE
使用自定义patternImage  Color的时候Crash

### ISSUE THREAD

**Issue by wyxuan** [tigerAndBull/TABAnimated#147]
在需要自定义加载占位图时
let color = UIColor.init(patternImage: image)
manager.animation()?(0)?.color()(color)
在iOS11以下会crash，模拟器上是没问题。但是在bugly平台上会定位到[UIColor encodeWithCoder:] 貌似是canLoadAgain缓存的时候图片颜色NSKeyedArchiver的问题。看看是不是这个地方的问题
+ (void)writeToFileWithData:(id)data filePath:(NSString *)filePath {
    if (@available(iOS 11.0, *)) {
        NSData *newData = [NSKeyedArchiver archivedDataWithRootObject:data requiringSecureCoding:YES error:NULL];
        if (newData) {
            [newData writeToFile:filePath atomically:YES];
        }
    }else {
        [NSKeyedArchiver archiveRootObject:data toFile:filePath];
    }
}

**Comment by tigerAndBull** [comment]
patternImage是UIImage？

**Comment by tigerAndBull** [comment]
自定义加载占位图: 用placeHolder()
