### ISSUE TITLE
baseComponentArrayiOS12越界问题

### ISSUE THREAD

**Issue by XoFeng** [tigerAndBull/TABAnimated#148]
baseComponentArray  iOS14要比iOS12多一个数据源, 目前检查是cell的contentview的原因 iOS12没有计算contentview

**Comment by tigerAndBull** [comment]
竟然，我记得应该适配过……
可以用最新版，根据变量名获取



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XoFeng ***@***.***&gt;
发送时间: 2021年4月29日 14:17
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] baseComponentArrayiOS12越界问题 (#148)





 
baseComponentArray  iOS14要比iOS12多一个数据源, 目前检查是cell的contentview的原因 iOS12没有计算contentview

**Comment by tigerAndBull** [comment]
可否提供具体场景，这个应该是适配过。

**Comment by tigerAndBull** [comment]
是xib吗？
已发现xib的子视图宽度和父视图相等的bug，2.5.8已修复。
