### ISSUE TITLE
objc_allocateClassPair之后不调用objc_registerClassPair会存在问题的，另外集成了RXSwift之后有问题

### ISSUE THREAD

**Issue by duzhongjieqiji** [tigerAndBull/TABAnimated#149]
问题一：
objc_allocateClassPair之后不调用objc_registerClassPair 某种情况下会crash报错objc[75964]: no class for metaclass
<img width="708" alt="image" src="https://user-images.githubusercontent.com/14856412/116661663-669bba80-a9c7-11eb-9ba7-c5bede328f32.png">

问题二:
集成了RXSwift之后有问题
<img width="653" alt="image" src="https://user-images.githubusercontent.com/14856412/116660943-4ae3e480-a9c6-11eb-8403-53a26781f45e.png">
希望看一下是否能兼容？

**Comment by dreamguagua** [comment]
我也遇到这问题

**Comment by tigerAndBull** [comment]
> 我也遇到这问题

如果是问题1，master已修复

**Comment by dreamguagua** [comment]
> > 我也遇到这问题
> 
> 如果是问题1，master已修复

我是swift调用的，报 objc[62033]: no class for metaclass 0x600001057540   2.5.6版本

**Comment by tigerAndBull** [comment]
> > > 我也遇到这问题
> > 
> > 
> > 如果是问题1，master已修复
> 
> 我是swift调用的，报 objc[62033]: no class for metaclass 0x600001057540 2.5.6版本

master代码已经修复，没有发布pod

**Comment by dreamguagua** [comment]
> > 我也遇到这问题
> 
> 如果是问题1，master已修复

ok，试了一下可以了，多谢大神，期待pod更新ing。  还有，效果可以只用于cell不用于header吗orz?
