### ISSUE TITLE
与RxSwift 列表使用会Crash

### ISSUE THREAD

**Issue by gitchenyuke** [tigerAndBull/TABAnimated#150]
![image](https://user-images.githubusercontent.com/37723856/117793646-ff132400-b27e-11eb-91b6-dfce950d7b3e.png)

![image](https://user-images.githubusercontent.com/37723856/117793300-ac396c80-b27e-11eb-8bbe-519e361f2834.png)

**Comment by tigerAndBull** [comment]
不兼容RxSwift
