### ISSUE TITLE
UITableViewAutomaticDimension,动态高度怎么设置

### ISSUE THREAD

**Issue by axinger** [tigerAndBull/TABAnimated#151]
作者你好,咨询一下
UITableView 动态高度怎么设置啊,因为在初始化时候,必须传值 cellHeight:
UITableViewAutomaticDimension 
```
_tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[TestTableViewCell class] cellHeight:100];
```
用UITableViewAutomaticDimension 无效
```
_tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[TestTableViewCell class] cellHeight:UITableViewAutomaticDimension];
```
以下为demo修改后代码
在TestTableViewCell中
```
    [self.statusBtn mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.mas_equalTo(self.gameImg.mas_right).mas_offset(15);
        make.top.mas_equalTo(self.timeLab.mas_bottom).mas_offset(10);
        make.width.mas_offset(70);
        make.height.mas_offset(20);
        
        make.bottom.equalTo(self.contentView.mas_bottom).mas_equalTo(-60);
    }];
```
在OneSectionViewController中
```
_tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[TestTableViewCell class] cellHeight:UITableViewAutomaticDimension];
```
``
-(CGFloat )tableView:(UITableView *)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath *)indexPath{
    return UITableViewAutomaticDimension;
}
-(CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    return UITableViewAutomaticDimension;
}
```

**Comment by tigerAndBull** [comment]
动态高度场景：在骨架屏可运行的indexPath中切为固定高度，在骨架屏结束后恢复原状。
