### ISSUE TITLE
Thread 1: "Array bound, please check it carefully." 数组越界崩溃

### ISSUE THREAD

**Issue by IDwuqing** [tigerAndBull/TABAnimated#152]
### New Issue Checklist

* [x] I have read the [Documentation](https://github.com/tigerAndBull/TABAnimated/tree/master/Documents)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/TABAnimated/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 13.6.1 或以上版本
 TABAnimated Version      | 2.5.1
 Xcode Version           |  Xcode 12.4
 Repro rate              |  sometimes 10%
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

- (TABBaseComponentBlock _Nullable)animation {
    __weak typeof(self) weakSelf = self;
    return ^TABBaseComponent *(NSInteger index) {
        if (index >= weakSelf.components.count) {
#ifdef DEBUG
            NSAssert(NO, @"Array bound, please check it carefully.");
#else
            TABComponentLayer *layer = TABComponentLayer.new;
            layer.loadStyle = TABViewLoadAnimationRemove;
            return [TABBaseComponent componentWithLayer:layer manager:weakSelf];
#endif
        }
        return weakSelf.components[index];
    };
}
*** Assertion failure in -[TABComponentManager animation], TABComponentManager.m:48 
Thread 1: "Array bound, please check it carefully."
这个方法 NSAssert(NO, @"Array bound, please check it carefully.");断言这里崩溃 index为3 components数组0元素

**Comment by tigerAndBull** [comment]
这个断言的意思是index溢出，试试更新下最新版本试试？

**Comment by mancongiOS** [comment]
我也有一个这样的崩溃。 不过是我自己的使用问题。 

问题代码： manager.animation(2).line(3);
数组中只有两个元素，却取index 为 2的元素。所以...

**Comment by tigerAndBull** [comment]
从0开始，这是常识


------------------ 原始邮件 ------------------
发件人: mancongiOS ***@***.***&gt;
发送时间: 2021年5月31日 10:41
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] Thread 1: "Array bound, please check it carefully." 数组越界崩溃 (#152)





 
我也有一个这样的崩溃。 不过是我自己的使用问题。
 
问题代码： manager.animation(2).line(3);
 数组中只有两个元素，却取index 为 2的元素。所以...
