### ISSUE TITLE
UICollectionView部分代理无法响应（TABCollectionAnimated.m）

### ISSUE THREAD

**Issue by mengshun** [tigerAndBull/TABAnimated#153]
作者大大， 你好， 我在使用的时候遇到了 UICollectionView 的部分代理无法响应的问题， 最后排查了一下，觉得可能是这里的问题， 请作者大大确认下：
[TABCollectionAnimated.m](https://github.com/tigerAndBull/TABAnimated/blob/26fd562fc7a1442413d90eba8df7c89c6de45ccf/TABAnimatedDemo/TABAnimated/Control/TABCollectionAnimated.m)
第329， 330行，
@selector(collectionView:didEndDisplayingCell:forElementKind:)  ->  @selector(collectionView:didEndDisplayingCell:forItemAtIndexPath:)

@selector(tab_collectionView:didEndDisplayingCell:forElementKind:) -> @selector(tab_collectionView:didEndDisplayingCell:forItemAtIndexPath:)

第323， 324， 335，336也是同样的问题， 少了后面的 atIndexPath，

请确认下，3Q

**Comment by tigerAndBull** [comment]
是bug，下一个版本修复。

**Comment by tigerAndBull** [comment]
2.5.7已修复，如有问题重新打开此issue
