### ISSUE TITLE
瀑布流不按照规定的selector设计导致奔溃

### ISSUE THREAD

**Issue by weizhangCoder** [tigerAndBull/TABAnimated#155]
### New Issue Checklist

* [ ] I have read the [Documentation](https://github.com/tigerAndBull/TABAnimated/tree/master/Documents)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/TABAnimated/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. iOS / macOS
 Platform Version        | e.g.  10.15.7
 TABAnimated Version      | e.g. 2.5.7
 Xcode Version           | e.g. Xcode 11 

由2.4.9版本升级到2.5.7 版本，直接报错。
<img width="738" alt="libc++abi dylib terminating with uncaught exception of type NSException" src="https://user-images.githubusercontent.com/11644326/122156079-db08bb00-ce9a-11eb-9e9e-c5611027be3c.png">

我的代码里是有这个方法的，我的类名被修改了。找到了修改的版本记录。希望作者可以看一下
<img width="1118" alt="if (isFirstLoad) {" src="https://user-images.githubusercontent.com/11644326/122156216-228f4700-ce9b-11eb-8841-8b911d8d28a9.png">

**Comment by weizhangCoder** [comment]
> 你这个方法不符合规范，2.4.9也会崩溃

我看了一下。2.4.9版本没有这块代码。这样它的类名变了，直接报找不到对应的代理方法了。我目前是用在UICollectionView里面然后用了一个LMJVerticalFlowLayout 做了一个瀑布流的布局，就出现这样找不到我瀑布流的代理方法了。

**Comment by tigerAndBull** [comment]
这代码是新增的，没有问题。
你这个瀑布流实现的selector不符合规范，旧的代码也会有问题。

**Comment by weizhangCoder** [comment]
> 这代码是新增的，没有问题。
> 你这个瀑布流实现的selector不符合规范，旧的代码也会有问题。

是这样的，瀑布流这个demo是新增的，我就必须写成TABAnimatedWaterFallLayout这样的，并完成一些代理。因为项目中以前写好了自己的flowLayout。所以我的项目是瀑布流的效果，但是不太想用瀑布流的骨架屏，想用正常collectionView 的骨架屏完成。这样好像不行，就会报出我第一次截图的错误。我这是瀑布流的布局，但依然还是想用正常collectionView的骨架屏是不行吗？

**Comment by weizhangCoder** [comment]
> 这代码是新增的，没有问题。
> 你这个瀑布流实现的selector不符合规范，旧的代码也会有问题。

瀑布流的关键代码是不是就是这几句。`      CGFloat height = CardCollectionViewCell.cellSize.height;
        NSArray <NSNumber *>* heightArray = @[@(height), @(height), @(height), @(height), @(height), @(height), @(height), @(height),@(height),@(height),@(height),@(height),@(height)];
        TABCollectionAnimated *tabAnimated =
        [TABCollectionAnimated animatedWaterFallLayoutWithCellClass:CardCollectionViewCell.class
                                                        heightArray:heightArray
                                                          heightSel:@selector(waterFallLayout:heightForItemAtIndex:itemWidth:)];`
如果我目前是没有显示出来，我正在找原因，如果我是多个不同的cell 我应该怎么写。

**Comment by weizhangCoder** [comment]
> 这代码是新增的，没有问题。
> 你这个瀑布流实现的selector不符合规范，旧的代码也会有问题。

没有把代码全部过一遍，发现只要是瀑布流，好像就必须TABAnimatedWaterFallLayout 用这个，如果不配合试用的话，用自己写的UICollectionViewLayout 好像是不行的。确认下是不是这样的

**Comment by tigerAndBull** [comment]
没有这种说法，你在启动动画周期使用UICollectionFlowLayout就行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weizhang ***@***.***&gt;
发送时间: 2021年6月21日 16:57
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] 2.4.9版本升级到2.5.7版本奔溃 (#155)

**Comment by weizhangCoder** [comment]
> 没有这种说法，你在启动动画周期使用UICollectionFlowLayout就行 发自我的iPhone
> […](#)

我把你的demo里面的换掉
<img width="810" alt="image" src="https://user-images.githubusercontent.com/11644326/122736645-d422e380-d2b2-11eb-834a-edc28c3fde7a.png">
然后写了对应的代理。
<img width="814" alt="image" src="https://user-images.githubusercontent.com/11644326/122736806-fb79b080-d2b2-11eb-932b-80d2f7bb45b4.png">
就直接报错了
<img width="923" alt="image" src="https://user-images.githubusercontent.com/11644326/122736894-0e8c8080-d2b3-11eb-90ba-4cf42b59023a.png">

**Comment by tigerAndBull** [comment]
已沟通确认。
目前版本瀑布流实现的，返回高度的selector参数需要和demo上的一致，命名可以不同，否则会有这种情况。
