### ISSUE TITLE
 xib  中有多个cell 就会发生崩溃

### ISSUE THREAD

**Issue by YueWangChina** [tigerAndBull/TABAnimated#158]
https://blog.csdn.net/kepoon/article/details/52302862
 如上述文章这种情况，大佬看看

**Comment by tigerAndBull** [comment]
请提供具体信息

**Comment by YueWangChina** [comment]
![1625734545398](https://user-images.githubusercontent.com/19685741/124893933-c3da6a80-e00d-11eb-945c-c83bfae08206.jpg)
![1625734554258](https://user-images.githubusercontent.com/19685741/124893943-c76df180-e00d-11eb-9fda-99c9afc4be6d.jpg)

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'invalid nib registered for identifier (tab_SGMineDetailsItem) - nib must contain exactly one top level object which must be a UITableViewCell instance'
这是错误信息
还是说我没使用正确？

**Comment by YueWangChina** [comment]
大佬 群号发一下   二维码失效了

**Comment by tigerAndBull** [comment]
你需要自己处理，我会为你注册一个tab_xxx的id。xib不允许两个id同时存在

**Comment by tigerAndBull** [comment]
nib must contain exactly one top level object which must be a UITableViewCell instance

**Comment by YueWangChina** [comment]
view = [(UITableView *)controlView dequeueReusableCellWithIdentifier:identifier forIndexPath:indexPath];
            ((UITableViewCell *)view).selectionStyle = UITableViewCellSelectionStyleNone;
同一个xib类  多种cell   ，不会进行注册，   拿不到cell   所以这个view =nil

**Comment by YueWangChina** [comment]
没思路了，有人知道这怎么解决嘛？

**Comment by tigerAndBull** [comment]
不会注册就不可以使用这个库，你可以使用别的cell/UITableVieweCell，通过adjustBlock进行个性化设置。

**Comment by kkkelicheng** [comment]
> view = [(UITableView *)controlView dequeueReusableCellWithIdentifier:identifier forIndexPath:indexPath]; ((UITableViewCell *)view).selectionStyle = UITableViewCellSelectionStyleNone; 同一个xib类 多种cell ，不会进行注册， 拿不到cell 所以这个view =nil

复用的时候，应该说的是nib文件只能有一个顶级的object，并且是UITableViewCell类型的

**Comment by kkkelicheng** [comment]
> https://blog.csdn.net/kepoon/article/details/52302862 如上述文章这种情况，大佬看看

复用的时候，应该说的是nib文件只能有一个顶级的object，并且是UITableViewCell类型的
