### ISSUE TITLE
UICollectionView中使用row横向布局，设定一行5个row，但执行完骨架动画后，一行变为了4个row

### ISSUE THREAD

**Issue by yyks999** [tigerAndBull/TABAnimated#159]
UICollectionView中使用row横向布局，设定一行5个row，但执行完骨架动画后，一行变为了4个row，是不是哪里配置的问题

使用版本：2.5.8
Demo：https://github.com/yyks999/TABAnimatedTest

![Simulator Screen Shot - iPhone 12 - 2021-07-21 at 10 00 58](https://user-images.githubusercontent.com/4744650/126418862-d851aa94-8d7b-42c7-8d56-3d79336143dd.png)

![Simulator Screen Shot - iPhone 12 - 2021-07-21 at 10 00 59](https://user-images.githubusercontent.com/4744650/126418885-f98c31c5-7a6e-4214-85b6-31ec057bf9ac.png)

![Simulator Screen Shot - iPhone 12 - 2021-07-21 at 10 01 01](https://user-images.githubusercontent.com/4744650/126418905-e758d6cb-b00e-4cf2-b9d0-fca2b74e78de.png)

**Comment by tigerAndBull** [comment]
请提供图片，没有时间打开电脑看代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MelodyK ***@***.***&gt;
发送时间: 2021年7月21日 09:45
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] UICollectionView中使用row横向布局，设定一行5个row，但执行完骨架动画后，一行变为了4个row (#159)





 
UICollectionView中使用row横向布局，设定一行5个row，但执行完骨架动画后，一行变为了4个row，是不是哪里配置的问题
 
Demo:https://github.com/yyks999/TABAnimatedTest

**Comment by yyks999** [comment]
图片已上传，麻烦有空的时候再帮看下

**Comment by tigerAndBull** [comment]
没有看到，请直接发到这个问题里



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MelodyK ***@***.***&gt;
发送时间: 2021年7月21日 10:49
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] UICollectionView中使用row横向布局，设定一行5个row，但执行完骨架动画后，一行变为了4个row (#159)





 
图片已上传，麻烦有空的时候再帮看下

**Comment by yyks999** [comment]
就是传到问题里的呀，看不到吗

**Comment by yyks999** [comment]
问题已解决，代码布局写法的问题。
