### ISSUE TITLE
TableView的contentInset失效

### ISSUE THREAD

**Issue by Lr-me** [tigerAndBull/TABAnimated#16]
作者请教一下，设置了tableView的animatdStyle后最初设置的contentInset没效果了
![snip20190224_1](https://user-images.githubusercontent.com/22276967/53300670-8124f700-3885-11e9-8948-57511d762528.png)

**Comment by tigerAndBull** [comment]
> 作者请教一下，设置了tableView的animatdStyle后最初设置的contentInset没效果了
> ![snip20190224_1](https://user-images.githubusercontent.com/22276967/53300670-8124f700-3885-11e9-8948-57511d762528.png)

你好，说明一下具体使用场景，
加群更快解决：304543771

**Comment by tigerAndBull** [comment]
> 作者请教一下，设置了tableView的animatdStyle后最初设置的contentInset没效果了
> ![snip20190224_1](https://user-images.githubusercontent.com/22276967/53300670-8124f700-3885-11e9-8948-57511d762528.png)

因太久没有收到demo或者反馈，暂时关闭。
