### ISSUE TITLE
UICollectionViewDelegateFlowLayout中有些方法不会被回调

### ISSUE THREAD

**Issue by dongdong945** [tigerAndBull/TABAnimated#160]
- (CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section;

这两个函数并不会被回调到，而去掉骨架屏的相关代码，就会被回调到

版本：2.5.9
直接运行TABAnimatedDemo，在TestCollectionViewCollection.m中
- (CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section
下断点就能复现

**Comment by tigerAndBull** [comment]
有时间处理下，你可以先在TABCollectionAnimated模仿其他函数进行切换管理

**Comment by tigerAndBull** [comment]
2.6.0 fix
