### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by qinling01** [tigerAndBull/TABAnimated#165]
![image](https://user-images.githubusercontent.com/17538968/127998645-836d2381-c2e7-4f50-8963-c8286ddd41da.png)

**Comment by tigerAndBull** [comment]
你这个类没有实现didHighlightRowAtIndexPath:这个代理？

**Comment by qinling01** [comment]
必须实现这个代理吗？

**Comment by tigerAndBull** [comment]
没有规定，你不实现不会走这个代理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 秦灵 ***@***.***&gt;
发送时间: 2021年8月4日 10:16
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Assign ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] 崩溃 (#165)





 
必须实现这个代理吗？

**Comment by qinling01** [comment]
但是现在问题就暴露出来了，我没实现这个方法，TABTableAnimated会给我抛出异常，不仅仅限于didHighlightRowAtIndexPath，包括tableview的scrollViewDidScroll以及其他的回调，没有实现的都会造成程序崩溃

**Comment by tigerAndBull** [comment]
哦，没有用最新版本，更新一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 秦灵 ***@***.***&gt;
发送时间: 2021年8月4日 11:22
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Assign ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] 崩溃 (#165)





 
但是现在问题就暴露出来了，我没实现这个方法，TABTableAnimated会给我抛出异常，不仅仅限于didHighlightRowAtIndexPath，包括tableview的scrollViewDidScroll以及其他的回调，没有实现的都会造成程序崩溃

**Comment by qinling01** [comment]
但是现在这个问题就暴露了，我没有实现这个方法，TABTableAnimated就会抛出异常，不仅仅限于didHighlightRowAtIndexPath，包括tableview的scrollViewD ScrollViewD Scroll以及其他的对话，没有实现的全部导致程序崩溃，我现在用的版本是2.5.9
，这不是最新的吗？

**Comment by tigerAndBull** [comment]
提供具体现场demo吧，正常情况下没有遇到这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 秦灵 ***@***.***&gt;
发送时间: 2021年8月4日 11:24
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Assign ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] 崩溃 (#165)





 
但是现在这个问题就暴露了，我没有实现这个方法，TABTableAnimated就会抛出异常，不仅仅限于didHighlightRowAtIndexPath，包括tableview的scrollViewD ScrollViewD Scroll以及其他的对话，没有实现的全部导致程序崩溃，我现在用的版本是2.5.9
 ，这不是最新的吗？

**Comment by qinling01** [comment]
这个问题出现在首次启用TABTableAnimated时，不是每次都会出现

**Comment by tigerAndBull** [comment]
所以你反馈信息不到位啊，请提供demo我协助你处理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 秦灵 ***@***.***&gt;
发送时间: 2021年8月4日 11:26
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Assign ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] 崩溃 (#165)





 
这个问题出现在首次启用TABTableAnimated时，不是每次都会出现

**Comment by qinling01** [comment]
偶发性的问题，还没找到重现方式

**Comment by DragonXXL** [comment]
2.5.9 我这也必崩溃，比如第一个tableVIew 实现了一个代理  加载第二没有实现第一个tableVIew的代理 也会去call交互方法，回退版本就好了一样的代码

`- (nullable UIView *)tab_tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
    
    TABTableAnimated *tabAnimated = tableView.tabAnimated;
    id oldDelegate = tabAnimated.oldDelegate;
    SEL sel = @selector(tableView:viewForHeaderInSection:);
    
    if (!tabAnimated.isAnimating) {
        return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
    }
    
    NSInteger index = [tabAnimated getHeaderIndexWithIndex:section];
    if (index < 0) {
       该行崩溃 return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
    }
    
    Class class = tabAnimated.headerClassArray[index];
    
    UIView *hfView;
    TABAnimatedProductOrigin origin = [class isSubclassOfClass:[UITableViewHeaderFooterView class]] ? TABAnimatedProductOriginTableHeaderFooterViewCell : TABAnimatedProductOriginTableHeaderFooterView;
    hfView = [tabAnimated.producter productWithControlView:tableView currentClass:class indexPath:nil origin:origin];
    
    return hfView;
}`
报错如下
 -[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0
2021-08-24 14:25:19.388531+0800 RainbowChat4i[4532:867227] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0'
*** First throw call stack:

**Comment by LoSenTrad** [comment]
我也是这个报错 
NSInteger index = [tabAnimated getHeaderIndexWithIndex:section];
if (index < 0) {
   该行崩溃 return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
}

**Comment by tigerAndBull** [comment]
> 我这也必崩溃，比如第一个tableVIew 实现了一个代理 加载第二没有实现第一个tableVIew的代理 也会去call交互方法，回退版本就好了一样的代码
> 目前回退2.5.6版本 不崩溃了，目测2.5.7版本开始有这个问题
> 
> ```
> - (nullable UIView *)tab_tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
> 
> TABTableAnimated *tabAnimated = tableView.tabAnimated;
> id oldDelegate = tabAnimated.oldDelegate;
> SEL sel = @selector(tableView:viewForHeaderInSection:);
> 
> if (!tabAnimated.isAnimating) {
>     return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> }
> 
> NSInteger index = [tabAnimated getHeaderIndexWithIndex:section];
> if (index < 0) {
>    该行崩溃 return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> }
> 
> Class class = tabAnimated.headerClassArray[index];
> 
> UIView *hfView;
> TABAnimatedProductOrigin origin = [class isSubclassOfClass:[UITableViewHeaderFooterView class]] ? TABAnimatedProductOriginTableHeaderFooterViewCell : TABAnimatedProductOriginTableHeaderFooterView;
> hfView = [tabAnimated.producter productWithControlView:tableView currentClass:class indexPath:nil origin:origin];
> 
> return hfView;
> ```
> 
> }`
> 实际是另一个tableView实现骨架图在它之前实现过这个代理报错如下
> -[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0
> 2021-08-24 14:25:19.388531+0800 RainbowChat4i[4532:867227] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0'
> *** First throw call stack:

2.5.7采用了切换代理管理数据源的方式，抛弃了旧版本的method swizzling方式。
这个地方index < 0，则交由原代理处理。似乎是在选择原代理上出现了问题，可以进一步反馈你的使用场景给我，或者加我微信：_tigerAndBull。

**Comment by DragonXXL** [comment]
谢谢你的回复。 是的，index < 0，交由原代理处理，但当前原代理没有实现这个代理方法，实际是另一个table的代理方法，莫明其妙的当前table.的tabAnimated对象居然也会去call另一个table的代理方法，感觉被继承过去了。场景是一个分类页面有两个table，左边一个分类、右边是一个分类内容。我周末有时间再研究一下

**Comment by DragonXXL** [comment]
谢谢你的回复。 是的，index < 0，交由原代理处理，但当前原代理没有实现这个代理方法，实际是另一个table的代理方法，莫明其妙的当前table.的tabAnimated对象居然也会去call另一个table的代理方法，感觉被继承过去了。场景是一个分类页面有两个table，左边一个分类、右边是一个分类内容。我周末有时间再研究一下

**Comment by DragonXXL** [comment]
> > 我这也必崩溃，比如第一个tableVIew 实现了一个代理 加载第二没有实现第一个tableVIew的代理 也会去call交互方法，回退版本就好了一样的代码
> > 目前回退2.5.6版本 不崩溃了，目测2.5.7版本开始有这个问题
> > ```
> > - (nullable UIView *)tab_tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
> > 
> > TABTableAnimated *tabAnimated = tableView.tabAnimated;
> > id oldDelegate = tabAnimated.oldDelegate;
> > SEL sel = @selector(tableView:viewForHeaderInSection:);
> > 
> > if (!tabAnimated.isAnimating) {
> >     return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> > }
> > 
> > NSInteger index = [tabAnimated getHeaderIndexWithIndex:section];
> > if (index < 0) {
> >    该行崩溃 return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> > }
> > 
> > Class class = tabAnimated.headerClassArray[index];
> > 
> > UIView *hfView;
> > TABAnimatedProductOrigin origin = [class isSubclassOfClass:[UITableViewHeaderFooterView class]] ? TABAnimatedProductOriginTableHeaderFooterViewCell : TABAnimatedProductOriginTableHeaderFooterView;
> > hfView = [tabAnimated.producter productWithControlView:tableView currentClass:class indexPath:nil origin:origin];
> > 
> > return hfView;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }`
> > 实际是另一个tableView实现骨架图在它之前实现过这个代理报错如下
> > -[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0
> > 2021-08-24 14:25:19.388531+0800 RainbowChat4i[4532:867227] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0'
> > *** First throw call stack:
> 
> 2.5.7采用了切换代理管理数据源的方式，抛弃了旧版本的method swizzling方式。
> 这个地方index < 0，则交由原代理处理。似乎是在选择原代理上出现了问题，可以进一步反馈你的使用场景给我，或者加我微信：_tigerAndBull。

谢谢你的回复。 是的，index < 0，交由原代理处理，但当前原代理没有实现这个代理方法，实际是另一个table的代理方法，莫明其妙的当前table.的tabAnimated对象居然也会去call另一个table的代理方法，感觉被继承过去了。场景是一个分类页面有两个table，左边一个分类、右边是一个分类内容。我周末有时间再研究一下

**Comment by tigerAndBull** [comment]
> > > 我这也必崩溃，比如第一个tableVIew 实现了一个代理 加载第二没有实现第一个tableVIew的代理 也会去call交互方法，回退版本就好了一样的代码
> > > 目前回退2.5.6版本 不崩溃了，目测2.5.7版本开始有这个问题
> > > ```
> > > - (nullable UIView *)tab_tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
> > > 
> > > TABTableAnimated *tabAnimated = tableView.tabAnimated;
> > > id oldDelegate = tabAnimated.oldDelegate;
> > > SEL sel = @selector(tableView:viewForHeaderInSection:);
> > > 
> > > if (!tabAnimated.isAnimating) {
> > >     return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> > > }
> > > 
> > > NSInteger index = [tabAnimated getHeaderIndexWithIndex:section];
> > > if (index < 0) {
> > >    该行崩溃 return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> > > }
> > > 
> > > Class class = tabAnimated.headerClassArray[index];
> > > 
> > > UIView *hfView;
> > > TABAnimatedProductOrigin origin = [class isSubclassOfClass:[UITableViewHeaderFooterView class]] ? TABAnimatedProductOriginTableHeaderFooterViewCell : TABAnimatedProductOriginTableHeaderFooterView;
> > > hfView = [tabAnimated.producter productWithControlView:tableView currentClass:class indexPath:nil origin:origin];
> > > 
> > > return hfView;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }`
> > > 实际是另一个tableView实现骨架图在它之前实现过这个代理报错如下
> > > -[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0
> > > 2021-08-24 14:25:19.388531+0800 RainbowChat4i[4532:867227] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0'
> > > *** First throw call stack:
> > 
> > 
> > 2.5.7采用了切换代理管理数据源的方式，抛弃了旧版本的method swizzling方式。
> > 这个地方index < 0，则交由原代理处理。似乎是在选择原代理上出现了问题，可以进一步反馈你的使用场景给我，或者加我微信：_tigerAndBull。
> 
> 谢谢你的回复。 是的，index < 0，交由原代理处理，但当前原代理没有实现这个代理方法，实际是另一个table的代理方法，莫明其妙的当前table.的tabAnimated对象居然也会去call另一个table的代理方法，感觉被继承过去了。场景是一个分类页面有两个table，左边一个分类、右边是一个分类内容。我周末有时间再研究一下

有一个要求不要共享tabAnimated对象，因为tabAnimated会保存旧的代理，如果这两个tableView的代理是同一个对象，则都会转发给这个对象

**Comment by DragonXXL** [comment]
> > > > 我这也必崩溃，比如第一个tableVIew 实现了一个代理 加载第二没有实现第一个tableVIew的代理 也会去call交互方法，回退版本就好了一样的代码
> > > > 目前回退2.5.6版本 不崩溃了，目测2.5.7版本开始有这个问题
> > > > ```
> > > > - (nullable UIView *)tab_tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
> > > > 
> > > > TABTableAnimated *tabAnimated = tableView.tabAnimated;
> > > > id oldDelegate = tabAnimated.oldDelegate;
> > > > SEL sel = @selector(tableView:viewForHeaderInSection:);
> > > > 
> > > > if (!tabAnimated.isAnimating) {
> > > >     return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> > > > }
> > > > 
> > > > NSInteger index = [tabAnimated getHeaderIndexWithIndex:section];
> > > > if (index < 0) {
> > > >    该行崩溃 return ((UIView * (*)(id, SEL, UITableView *, NSInteger))objc_msgSend)((id)oldDelegate, sel, tableView, section);
> > > > }
> > > > 
> > > > Class class = tabAnimated.headerClassArray[index];
> > > > 
> > > > UIView *hfView;
> > > > TABAnimatedProductOrigin origin = [class isSubclassOfClass:[UITableViewHeaderFooterView class]] ? TABAnimatedProductOriginTableHeaderFooterViewCell : TABAnimatedProductOriginTableHeaderFooterView;
> > > > hfView = [tabAnimated.producter productWithControlView:tableView currentClass:class indexPath:nil origin:origin];
> > > > 
> > > > return hfView;
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > }`
> > > > 实际是另一个tableView实现骨架图在它之前实现过这个代理报错如下
> > > > -[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0
> > > > 2021-08-24 14:25:19.388531+0800 RainbowChat4i[4532:867227] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MHyLeftMenuTable tableView:viewForHeaderInSection:]: unrecognized selector sent to instance 0x132bc23d0'
> > > > *** First throw call stack:
> > > 
> > > 
> > > 2.5.7采用了切换代理管理数据源的方式，抛弃了旧版本的method swizzling方式。
> > > 这个地方index < 0，则交由原代理处理。似乎是在选择原代理上出现了问题，可以进一步反馈你的使用场景给我，或者加我微信：_tigerAndBull。
> > 
> > 
> > 谢谢你的回复。 是的，index < 0，交由原代理处理，但当前原代理没有实现这个代理方法，实际是另一个table的代理方法，莫明其妙的当前table.的tabAnimated对象居然也会去call另一个table的代理方法，感觉被继承过去了。场景是一个分类页面有两个table，左边一个分类、右边是一个分类内容。我周末有时间再研究一下
> 
> 有一个要求不要共享tabAnimated对象，因为tabAnimated会保存旧的代理，如果这两个tableView的代理是同一个对象，则都会转发给这个对象

这两个table的代理共享一个父类baseView，代理对象都是继承baseView实例化的子类MHyLeftMenuTable和MHyListTable。这样会影响吗？

**Comment by Li-Qun** [comment]
本人复现了 这个代理方法方法传递错误的问题 ，尤其是模拟弱网情况测试 在类目下面反复切换列表 必现！！！collectionView
代理方法错乱崩溃，2.6.0 最新版本！！！！请求作者 给一下解决方案

**Comment by tigerAndBull** [comment]
> 本人复现了 这个代理方法方法传递错误的问题 ，尤其是模拟弱网情况测试 在类目下面反复切换列表 必现！！！collectionView
> 
> 代理方法错乱崩溃，2.6.0 最新版本！！！！请求作者 给一下解决方案 @tigerAndBull 

请描述清楚，带上代码图文，骨架屏和网络无关，只是说弱网下容易命中某个case

**Comment by Li-Qun** [comment]
作者你好:和 DragonXXL commented 25 days ago 错误 一致，参考DragonXXL 已退版本2.5.6。
错误是一致的错误：可选的代理方法 一个列表实现，另一个列表没实现，在当前正在展示骨架屏的时候，切换到另一个页面，这样代理方法就带到了另一个页面 ，导致闪退。

**Comment by tigerAndBull** [comment]
> exception

可以加保护，不过我还是没有理解为什么会被转发到无效的sel。你加我wx：_tigerAndBull

**Comment by Li-Qun** [comment]
在2.5.6版本 几个顶部tab 的骨架效果已经end 情况 在一个列表内进行加载更多  然后点击状态栏自动回滚顶部时候闪退。。。这个是报错的具体新信息
程序即将关闭...
2021-09-26 09:57:21.223759+0800 Kongfz[50121:16570349] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2021-09-26 09:57:21.223910+0800 Kongfz[50121:16570349] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2021-09-26 09:57:21.235802+0800 Kongfz[50121:16570349] [Bugly]  Trapped uncaught exception 'NSInvalidArgumentException', reason: '-[KFZSearchCommodityView scrollViewShouldScrollToTop:]: unrecognized selector sent to instance 0x7fbec6c942c0' 
(
	"0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242",
	"1   libobjc.A.dylib                     0x00007fff20177f78 objc_exception_throw + 48",
	"2   CoreFoundation                      0x00007fff20448c6f +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0",
	"3   UIKitCore                           0x00007fff246a2414 -[UIResponder doesNotRecognizeSelector:] + 292",
	"4   CoreFoundation                      0x00007fff2043e3f0 ___forwarding___ + 859",
	"5   CoreFoundation                      0x00007fff20440698 _CF_forwarding_prep_0 + 120",
	"6   TABAnimated                         0x000000010e065eb1 -[TABFormAnimated tab_scrollViewDidScrollToTop:] + 177",
	"7   UIKitCore                           0x00007fff24b57ac5 -[UIScrollView _scrollViewAnimationEnded:finished:] + 252",
	"8   UIKitCore                           0x00007fff24b57cfb -[UIScrollView animator:stopAnimation:fraction:] + 60",
	"9   UIKitCore                           0x00007fff23b143c1 -[UIAnimator stopAnimation:] + 377",
	"10  UIKitCore                           0x00007fff23b14a6e -[UIAnimator _advanceAnimationsOfType:withTimestamp:] + 269",
	"11  QuartzCore                          0x00007fff2790440d _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 755",
	"12  QuartzCore                          0x00007fff279e8a7c _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 639",
	"13  CoreFoundation                      0x00007fff2037670c __CFMachPortPerform + 157",
	"14  CoreFoundation                      0x00007fff203a913d __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41",
	"15  CoreFoundation                      0x00007fff203a84de __CFRunLoopDoSource1 + 614",
	"16  CoreFoundation                      0x00007fff203a29ba __CFRunLoopRun + 2353",
	"17  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567",
	"18  GraphicsServices                    0x00007fff2b793db3 GSEventRunModal + 139",
	"19  UIKitCore                           0x00007fff2466d40f -[UIApplication _run] + 912",
	"20  UIKitCore                           0x00007fff24672320 UIApplicationMain + 101",
	"21  Kongfz                              0x000000010838d828 main + 168",
	"22  libdyld.dylib                       0x00007fff20257409 start + 1",
)

**Comment by tigerAndBull** [comment]
@Li-Qun @DragonXXL @LoSenTrad @qinling01 
targetContolName不唯一导致, 2.6.2 fixed
