### ISSUE TITLE
Crash 原因我不知道是什么

### ISSUE THREAD

**Issue by Aynnor** [tigerAndBull/TABAnimated#166]
### 请看贴图

* [x] I have read the [Documentation](https://github.com/tigerAndBull/TABAnimated/tree/master/Documents)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/TABAnimated/issues) and found none

### Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           iOS 
 Platform Version        9.0
 TABAnimated Version    2.5.0
 Xcode Version           12.4

### 请看图
![image](https://user-images.githubusercontent.com/29776690/128108728-0b1a73bb-2e2a-4376-a604-b53ea3723fa3.png)

**Comment by Aynnor** [comment]
我不知道这是Crash在哪里

**Comment by tigerAndBull** [comment]
这不是崩溃



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Aynnor ***@***.***&gt;
发送时间: 2021年8月4日 09:46
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] Crash 原因我不知道是什么 (#166)





 
请看贴图
  
 I have read the Documentation 

 I have searched for a similar issue in the project and found none 
 
Issue Info
    Info Value 
    Platform Name           iOS  
  Platform Version        14.0+  
  TABAnimated Version    2.5.0  
  Xcode Version           12.4  
   
请看图
