### ISSUE TITLE
UICollectionViewDelegateFlowLayout方法不回掉

### ISSUE THREAD

**Issue by riluoxiyanghuanghun** [tigerAndBull/TABAnimated#167]
使用了TABAnimated下面这个方法不走
- (UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout insetForSectionAtIndex:(NSInteger)section

**Comment by tigerAndBull** [comment]
2.6.0 fixed
