### ISSUE TITLE
(swift用不了这个api) collectionView.fzdTabAnimated.adjustBlock = { sender in       }

### ISSUE THREAD

**Issue by LoSenTrad** [tigerAndBull/TABAnimated#169]
(swift用不了这个api) collectionView.fzdTabAnimated.adjustBlock = { sender in       }

**Comment by tigerAndBull** [comment]
readme有写怎么用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LoSenTrad ***@***.***&gt;
发送时间: 2021年8月23日 23:37
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[tigerAndBull/TABAnimated] (swift用不了这个api) collectionView.fzdTabAnimated.adjustBlock = { sender in       } (#169)

**Comment by LoSenTrad** [comment]
大神 回复这么迅速 谢谢哈
