### ISSUE TITLE
-[UIView retain]: message sent to deallocated instance 0x7fb03cad5d60

### ISSUE THREAD

**Issue by ShaochongDu** [tigerAndBull/TABAnimated#174]
使用mj下拉刷新几次，就闪退，不知什么原因导致

![image](https://user-images.githubusercontent.com/16948310/134614306-06fd061b-7fca-400b-b844-f957b3cffcd2.png)

**Comment by tigerAndBull** [comment]
> 使用mj下拉刷新几次，就闪退，不知什么原因导致
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/16948310/134614306-06fd061b-7fca-400b-b844-f957b3cffcd2.png)
> 
> 

你的控制视图已经被释放了，骨架屏期间请保证控制视图一直存在

**Comment by ShaochongDu** [comment]
我测试了下，控制器没有被释放

**Comment by tigerAndBull** [comment]
> 我测试了下，控制器没有被释放

是控制视图，不是控制器

**Comment by ShaochongDu** [comment]
视图也没有释放，这是一个footerview：self.tableView.tableFooterView = self.footerView;

**Comment by tigerAndBull** [comment]
> 视图也没有释放，这是一个footerview：self.tableView.tableFooterView = self.footerView;

你自己的图里，已经被回收了

**Comment by ShaochongDu** [comment]
能提供个思路吗，我检查下

**Comment by tigerAndBull** [comment]
> 能提供个思路吗，我检查下

在这个函数调用前打个断点，看一下controlView是否为空

**Comment by ShaochongDu** [comment]
在TABAnimatedProductImpl这个类中，- (void)_productBackgroundLayerWithView:(UIView *)view needReset:(BOOL)needReset方法调用打印self->_controlView貌似就访问不了了，我看定义的是__unsafe_unretained

![image](https://user-images.githubusercontent.com/16948310/134623635-d7039031-5cbc-4f9b-9d1c-d1b752fc03f1.png)

什么情况导致的呢，我没有发现那个地方会释放掉这个footerview啊

**Comment by tigerAndBull** [comment]
> 在TABAnimatedProductImpl这个类中，- (void)_productBackgroundLayerWithView:(UIView *)view needReset:(BOOL)needReset方法调用打印self->_controlView貌似就访问不了了，我看定义的是__unsafe_unretained
> 
> ![image](https://user-images.githubusercontent.com/16948310/134623635-d7039031-5cbc-4f9b-9d1c-d1b752fc03f1.png)
> 
> 什么情况导致的呢，我没有发现那个地方会释放掉这个footerview啊

你这个就代表被释放了，是一个僵尸对象，应该是被系统回收了。
这里修饰没有用weak，如果用weak的话，应该可以解决崩溃问题，但是骨架屏的话应该还是没有，你可以试试改成weak

**Comment by ShaochongDu** [comment]
改成weak就可以了，但是下边这种情况是什么原因呢，文字变的不匹配，图片也是

![image](https://user-images.githubusercontent.com/16948310/134626068-070bfb1c-c4b1-4c44-afbb-0d954a7e794b.png)

**Comment by tigerAndBull** [comment]
2.6.3 fixed. If there are still problems, please open it again.
