### ISSUE TITLE
tableHeaderView.tabAnimated.adjustBlock  不起作用

### ISSUE THREAD

**Issue by Huzepei** [tigerAndBull/TABAnimated#184]
self.tableview.tabAnimated.showTableHeaderView = YES;
self.tableview.tableHeaderView.tabAnimated.adjustBlock

这两句不起作用，我的是多section多cell， 都可以控制，但是设置tableviewHeader，设置无效

**Comment by tigerAndBull** [comment]
tableView.tabAnimated.tabHeadViewAnimated

**Comment by 1knight520** [comment]
> 

nice
