### ISSUE TITLE
作者大佬你好， 在collectionView里面有几个cell 需要用到骨架 有几个不需要，没办法区分

### ISSUE THREAD

**Issue by guoqianglaien** [tigerAndBull/TABAnimated#190]
collectionView.tabAnimated 里设置需要需要骨架cell， 那么没有设置骨架的cell就会在显示骨架的时候消失
collectionView.tabAnimated 里设置所有cell都需要骨架， 那么单独开启tab_startAnimation(withSection: 0) 会使 collectionview 所有设置了骨架cell都显示骨架动画
我想要collectionview里面部分cell有骨架的动画

**Comment by tigerAndBull** [comment]
使用其他初始化方法指定row
