### ISSUE TITLE
completion问题

### ISSUE THREAD

**Issue by Coder-Star** [tigerAndBull/TABAnimated#193]
### New Issue Checklist

这个位置建议也执行一下completion闭包，否则依赖于闭包返回结果的逻辑就会出现问题

![image](https://user-images.githubusercontent.com/29835618/150456796-edb4aa50-ae9f-45db-8659-c0590df3f260.png)

**Comment by tigerAndBull** [comment]
理论上这里应该加断言，后来去掉了，未启动不应该走到这个方法里，否则认为使用逻辑有问题

**Comment by Coder-Star** [comment]
> 理论上这里应该加断言，后来去掉了，未启动不应该走到这个方法里，否则认为使用逻辑有问题

**Comment by Coder-Star** [comment]
> 理论上这里应该加断言，后来去掉了，未启动不应该走到这个方法里，否则认为使用逻辑有问题

```swift
func doSomthing() {
   tableView.tab_startAnimation(withDelayTime: 0.2) { [weak self] in
            guard let self = self else { return }
            self.getData()
        }
}
```

比如这种情况，调用`doSomthing`多次，比如第一次的动画还未执行完毕，就会导致后面的调用闭包内的逻辑不会执行
