### ISSUE TITLE
作者是否考虑使用 lottie-ios 做进一步优化?

### ISSUE THREAD

**Issue by xiaohange** [tigerAndBull/TABAnimated#2]

**Comment by tigerAndBull** [comment]
已经进行了更新！

**Comment by xiaohange** [comment]
@tigerAndBull 今天测了一下, xib 创建的cell, 在awakeFromNib里设置loadStyle并未起到作用, 请问该如何修改? 你的qq上面好像是错误的, 搜不到.

**Comment by tigerAndBull** [comment]
hey，您好，
您说明的问题 github和简书都已经进行了更新～
感谢您的建议




------------------ 原始邮件 ------------------
发件人: "HanJunqiang"<notifications@github.com>;
发送时间: 2018年10月7日(星期天) 晚上7:40
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 作者是否考虑使用 lottie-ios 做进一步优化? (#2)




@tigerAndBull 今天测了一下, xib 创建的cell, 在awakeFromNib里设置loadStyle并未起到作用, 请问该如何修改? 你的qq上面好像是错误的, 搜不到.

**Comment by xiaohange** [comment]
@tigerAndBull 你的QQ搜不到, xib在我测试的时候始终不显示

**Comment by tigerAndBull** [comment]
是最新的代码吗？
加我wx吧，18305177052


------------------ 原始邮件 ------------------
发件人: "HanJunqiang"<notifications@github.com>;
发送时间: 2018年10月8日(星期一) 下午3:47
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 作者是否考虑使用 lottie-ios 做进一步优化? (#2)




@tigerAndBull 你的QQ搜不到, xib在我测试的时候始终不显示
