### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by hms040717007** [tigerAndBull/TABAnimated#20]
(1)是否可加设置圆角属性?
(2)是否可选渐变方向?
(3)是否可有消失回调?
demo-功能体现不是很独立,不利于新手使用

**Comment by tigerAndBull** [comment]
> (1)是否可加设置圆角属性?
> (2)是否可选渐变方向?
> (3)是否可有消失回调?
> demo-功能体现不是很独立,不利于新手使用

你好，收到您的建议，
1.目前一直在优化骨架逻辑，以便更佳的性能和更方便的使用，圆角在考虑范围内，会在下次加上
2.渐变方向可能不太会添加，因为闪光灯动画有去除的可能
3.消失回调没有必要
4.demo后续会规整
5.有更多想法，加群交流。

**Comment by tigerAndBull** [comment]
> (1)是否可加设置圆角属性?
> (2)是否可选渐变方向?
> (3)是否可有消失回调?
> demo-功能体现不是很独立,不利于新手使用

此issue中的前三条已经实现，
因为demo工作量较大，短期内不会进行大版本改动
谢谢建议！
