### ISSUE TITLE
TABAnimatedInjectionIIIHelper移除的建议

### ISSUE THREAD

**Issue by Jentlezhi** [tigerAndBull/TABAnimated#201]
TABAnimatedInjectionIIIHelper类的+load方法给控制器的injected添加了具体的实现viewDidLoad，injected方法本身会导致在RAC框架下使用InjectionIII频繁崩溃，建议作者给个开关，让用户自行集成InjectionIII。

**Comment by tigerAndBull** [comment]
master 已修改 将InjectionIII移至demo
