### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by zerocc2014** [tigerAndBull/TABAnimated#207]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/16301538/188373293-22137a2c-54b0-43ce-b9d5-caa4bbe6a5b6.png">

**Comment by zerocc2014** [comment]
自测没法复现，上线后太可怕了崩溃率！

**Comment by tigerAndBull** [comment]
能找到场景吗，这里走的是消息转发到你的代理方法
