### ISSUE TITLE
关于深色主题app闪白问题

### ISSUE THREAD

**Issue by dq3398509** [tigerAndBull/TABAnimated#208]
https://www.jianshu.com/p/06166f128483

    在appdelegate中添加这段代码
    if (@available(iOS 14.0, *)) {
        UIBackgroundConfiguration *bgconfig = [UIBackgroundConfiguration listPlainCellConfiguration];
        bgconfig.backgroundColor = UIColor.clearColor;
        [UITableViewCell appearance].backgroundConfiguration = bgconfig;
    }

**Comment by tigerAndBull** [comment]
已沟通，使用clearColor解决
