### ISSUE TITLE
背景颜色如何修改

### ISSUE THREAD

**Issue by xiaoxiaoxiao2019** [tigerAndBull/TABAnimated#21]
RT 背景颜色如何修改  默认白色 我黑色想用

**Comment by tigerAndBull** [comment]
> RT 背景颜色如何修改 默认白色 我黑色想用

你好，近几天发版本会进行更改，如果想快速解决，加一下群。

**Comment by tigerAndBull** [comment]
> RT 背景颜色如何修改 默认白色 我黑色想用

你好，2.0.3已经解决了。
