### ISSUE TITLE
tab_stopPullLoading 分页情况下，请求第二页返回空数据的时候，动画不会消失

### ISSUE THREAD

**Issue by 1knight520** [tigerAndBull/TABAnimated#211]
有个情况咨询下
tab_stopPullLoading 分页情况下，请求第二页返回空数据的时候，动画不会消失，只能用tab_stopPullLoadingNoMoreData。
还有个情况：第一页，比如数据只有2条，加载更多的时候，cell骨架显示在表的底部，而不是接在2条cell后。

**Comment by tigerAndBull** [comment]
第一个是符合预期的。
第二个的话，是bug，我有时间处理下。

**Comment by tigerAndBull** [comment]
需要告知框架没有更多数据，不然的话，骨架屏会一直存在。

**Comment by tigerAndBull** [comment]
master 已修改

**Comment by 1knight520** [comment]
OK 辛苦辛苦

**Comment by 1knight520** [comment]
> 

怎么告知框架没有更多数据呢 我之前做法是没数据的时候tab_stopPullLoadingNoMoreData，然后刷新的时候tab_resetPullLoadingState，但是后面继续加载更多就会加载不了了

**Comment by 1knight520** [comment]
用tab_stopPullLoadingNoMoreData之后，刷新tab_resetPullLoadingState重置加载下拉刷新状态，再加载更多会加载不了，该怎么处理呢

**Comment by 1knight520** [comment]
是不是可以这样 加载更多，没数据的时候执行
 [self.tableView tab_stopPullLoading];
[self.tableView tab_endAnimation];
return;
这样加载更多没数据的时候,底部就不会有加载更多的骨架动画了
