### ISSUE TITLE
TABComponentManager animationN 报错

### ISSUE THREAD

**Issue by ml2720101** [tigerAndBull/TABAnimated#212]
TABComponentManager animationN 提示找不到对应变量 然后崩溃了

**Comment by tigerAndBull** [comment]
> TABComponentManager animationN 提示找不到对应变量 然后崩溃了

说明变量名不对/不存在， 局部变量无法捕获变量名

**Comment by ml2720101** [comment]
我按照demo的写法
<img width="653" alt="image" src="https://user-images.githubusercontent.com/14347031/195488112-a8399cfa-eedc-4e9d-ba51-1711f2d0eb7f.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/14347031/195488189-9842637e-06e9-4ecb-8daa-e928d85d72ea.png">

**Comment by tigerAndBull** [comment]
> 

tag在视图上能呈现backView变量名吗

**Comment by ml2720101** [comment]
不能

**Comment by ml2720101** [comment]
为啥有的能捕获有的不能呢

**Comment by tigerAndBull** [comment]
> 为啥有的能捕获有的不能呢

有优化策略，如果是毫无意义的底图，会被忽略掉。背景色等参数可以使用其他策略。
