### ISSUE TITLE
阿语该如何适配？

### ISSUE THREAD

**Issue by fuchenxi** [tigerAndBull/TABAnimated#216]

**Comment by tigerAndBull** [comment]
提供下具体的场景

**Comment by fuchenxi** [comment]
https://user-images.githubusercontent.com/24308071/219997233-8807f8bb-259c-4248-a062-b654ebd25dae.mp4
这是我在阿拉伯语言（RTL）中进行的测试，动画方向应该是从 右往左 变化

**Comment by fuchenxi** [comment]
阿语布局是其他语言的镜像布局，所有的交互和动画都应镜像翻转

**Comment by tigerAndBull** [comment]
> 阿语布局是其他语言的镜像布局，所有的交互和动画都应镜像翻转

如果只是动画，可以自己重写动画
