### ISSUE TITLE
dome 中的 UITableView示例, 点击 cell, 显示异常

### ISSUE THREAD

**Issue by moonclock** [tigerAndBull/TABAnimated#22]
dome 中的 UITableView示例, 点击 cell, 显示异常, 如图所示:
![图片](https://user-images.githubusercontent.com/12515349/57357892-ab106900-71a6-11e9-9176-6297b87e9fcb.png)

**Comment by tigerAndBull** [comment]
> dome 中的 UITableView示例, 点击 cell, 显示异常, 如图所示:
> ![图片](https://user-images.githubusercontent.com/12515349/57357892-ab106900-71a6-11e9-9176-6297b87e9fcb.png)

收到了，前几天我在测试使用中发现了这个问题，是因为某个地方代码失误造成的，
下个版本会进行修复，抱歉。

**Comment by moonclock** [comment]
> > dome 中的 UITableView示例, 点击 cell, 显示异常, 如图所示:
> > ![图片](https://user-images.githubusercontent.com/12515349/57357892-ab106900-71a6-11e9-9176-6297b87e9fcb.png)
> 
> 收到了，前几天我在测试使用中发现了这个问题，是因为某个地方代码失误造成的，
> 下个版本会进行修复，抱歉。

反应超级快, 哈哈, 给作者大大的好评

**Comment by tigerAndBull** [comment]
没有没有，我收到邮件了，最近也没啥事，也正在处理这个框架的其他需求。




------------------ 原始邮件 ------------------
发件人: "moonclock"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午3:41
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/TABAnimated] dome 中的 UITableView示例, 点击 cell, 显示异常 (#22)



  
dome 中的 UITableView示例, 点击 cell, 显示异常, 如图所示:
 
  
收到了，前几天我在测试使用中发现了这个问题，是因为某个地方代码失误造成的，
 下个版本会进行修复，抱歉。
  
反应超级快, 哈哈, 给作者大大的好评

**Comment by tigerAndBull** [comment]
你可以加群，我告诉你如何快速解决这个问题，也可以等下个版本进行集成。
因为新项目用UICollectionView比较多，所以UITableView部分地方没有测试到。




------------------ 原始邮件 ------------------
发件人: "moonclock"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午3:41
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/TABAnimated] dome 中的 UITableView示例, 点击 cell, 显示异常 (#22)



  
dome 中的 UITableView示例, 点击 cell, 显示异常, 如图所示:
 
  
收到了，前几天我在测试使用中发现了这个问题，是因为某个地方代码失误造成的，
 下个版本会进行修复，抱歉。
  
反应超级快, 哈哈, 给作者大大的好评
