### ISSUE TITLE
偶现crash

### ISSUE THREAD

**Issue by 78084367** [tigerAndBull/TABAnimated#222]
一、业务场景：列表使用骨架屏，第一页数据加载失败时或无数据时，停止骨架屏动画，偶现crash

二、使用示例：
1、骨架屏配置
<img width="752" alt="image" src="https://user-images.githubusercontent.com/11691487/233531904-a3eb8dba-8748-4049-9db2-086bfa73c9fe.png">
2、发起网络请求，触发骨架屏动画
<img width="831" alt="image" src="https://user-images.githubusercontent.com/11691487/233531968-c3b5668b-cdc7-4bf6-afea-596d02e588a7.png">
3、请求结束配置modelArr，并停止骨架屏
<img width="971" alt="image" src="https://user-images.githubusercontent.com/11691487/233532949-7c1948d0-436c-4ce5-8d06-9e3b61abb885.png">
<img width="933" alt="image" src="https://user-images.githubusercontent.com/11691487/233533081-2665480e-32b2-499d-b672-ae9d533bdfd7.png">
<img width="568" alt="image" src="https://user-images.githubusercontent.com/11691487/233532130-1c3e8c2e-5fc0-4861-b191-0114d5c22a89.png">

三、偶发crash信息参考：
<img width="1897" alt="image" src="https://user-images.githubusercontent.com/11691487/233531318-37ccead0-0333-47f2-b5ab-d2c24c4a0939.png">
UICollectionView和UITableView均有此问题，偶现

四、其他说明：
1、列表数据modelArr使用get懒加载
2、获取第一页时，若数据网络异常会是modelArr = nil；若第一页无数据，及modelArr.count = 0。
3、未使用骨架屏时，刷新列表（UITableView和UICollectionView）均无问题，因为numberOfXXXInSection都会返回0，不会触发cellForXXXAtIndexPath，也不会数组越界crash

五、希望作者分析下该库的健壮性

六、最后：感谢作者分享优异的工具库供大家使用，希望作者越来越好

**Comment by 78084367** [comment]
我在Demo SectionsCollectionViewController类中，将获取数据的数组调整后，也会报相同的错误，示例如下
1、获取数据后，数据依然是空
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/11691487/233824364-af8474d7-4402-4664-a558-415b9c1612e5.png">
2、Cell获取该数组对应索引的数据模型
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/11691487/233824438-d47e3b54-051e-4050-9ad7-60b3e174e9ce.png">
3、Crash
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/11691487/233824495-fedecb70-cc46-496d-8e2d-5d2b6df1a87b.png">

**Comment by 78084367** [comment]
这个问题是数组越界问题，场景是某列表接口返回数组为空数组，该列表应该是无数据状态。
但该库hook交换了代理的方法，某些节点该库依然会调用cellForRowAtIndexPath / cellForItemAtIndexPath，但是此时如果业务方列表中Array为空，Array[indexPath.row]就越界触发Crash了，这不是业务方的问题。

此库这块设计的不太合理，因为没数据时（modelArray.count=0），如果不集成此库，系统本身都不会触发cellForXXXAtIndexPath

目前为了避免此问题，可以在cell赋值时，判断下当前Array.count是否大于IndexPath
如下
<img width="482" alt="image" src="https://user-images.githubusercontent.com/11691487/233826149-2c15adad-90d3-44c3-ae5a-fe33d81255ae.png">

但是这种被迫判断的代码很不理想

希望作者整体考量下，看看怎么优化此场景问题，十分感谢~

**Comment by zhuxiaod** [comment]
我也遇到了这个问题

**Comment by tongxiaobo** [comment]
我也遇到相同的问题，看源码是hook里numberOfSections方法，结算骨架动画后状态没有设置成end，导致没有触发被交换的方法

**Comment by tigerAndBull** [comment]
感谢反馈 2.6.6 fixed @tongxiaobo @zhuxiaod @78084367
