### ISSUE TITLE
app内切换黑夜模式

### ISSUE THREAD

**Issue by nba88719840** [tigerAndBull/TABAnimated#224]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/6261850/236974866-1de7cd8c-7180-45ea-8df8-f70324ce8fc2.png">
大神们有没有遇到过 app内自定义的黑夜模式，重新设置颜色骨架部分颜色还是之前的 ，初始化的时候是对的，是没有映射完/或者需要重置？

**Comment by tigerAndBull** [comment]
需要跟随app内的暗黑模式参数决定是哪种模式。

**Comment by nba88719840** [comment]
https://user-images.githubusercontent.com/6261850/237849126-19c8ed3f-42f7-48ae-9b94-4afb88e00f8e.png
demo 强制暗黑背景色无效

**Comment by tigerAndBull** [comment]
> https://user-images.githubusercontent.com/6261850/237849126-19c8ed3f-42f7-48ae-9b94-4afb88e00f8e.png demo 强制暗黑背景色无效

优先响应用户设置的颜色哈，你设置了全局黄色和蓝色

**Comment by tigerAndBull** [comment]
> 我也发现这个问题了，咋设置呢

[TABAnimated sharedAnimated].darkModeType = TABAnimatedDarkModeForceDark;

**Comment by nba88719840** [comment]
> > https://user-images.githubusercontent.com/6261850/237849126-19c8ed3f-42f7-48ae-9b94-4afb88e00f8e.png demo 强制暗黑背景色无效
> 
> 优先响应用户设置的颜色哈，你设置了全局黄色和蓝色

常规一套颜色 黑暗一套颜色，有什么问题吗 ？ 那我要白色模式 动画黄色，黑色模式动画绿色怎么设置呢？

**Comment by tigerAndBull** [comment]
有方法设置 请看文档


------------------ 原始邮件 ------------------
发件人: Zhao Wei ***@***.***&gt;
发送时间: 2023年5月17日 13:39
收件人: tigerAndBull/TABAnimated ***@***.***&gt;
抄送: tigerAndBull ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [tigerAndBull/TABAnimated] app内切换黑夜模式 (Issue #224)





   
https://user-images.githubusercontent.com/6261850/237849126-19c8ed3f-42f7-48ae-9b94-4afb88e00f8e.png demo 强制暗黑背景色无效
  
优先响应用户设置的颜色哈，你设置了全局黄色和蓝色
  
常规一套颜色 黑暗一套颜色，有什么问题吗 ？ 那我要白色模式 动画黄色，黑色模式动画绿色怎么设置呢？

**Comment by yangguanghei** [comment]
> TABAnimatedDarkModeForceDark

感觉说的应该是这个问题：https://github.com/yangguanghei/TABAnimated

**Comment by yangguanghei** [comment]
> <img alt="image" width="1032" src="https://user-images.githubusercontent.com/6261850/236974866-1de7cd8c-7180-45ea-8df8-f70324ce8fc2.png">
> 
> 大神们有没有遇到过 app内自定义的黑夜模式，重新设置颜色骨架部分颜色还是之前的 ，初始化的时候是对的，是没有映射完/或者需要重置？

感觉说的应该是这个问题：https://github.com/yangguanghei/TABAnimated

**Comment by tigerAndBull** [comment]
2.6.6 fixed 感谢反馈 @yangguanghei @nba88719840 @geekdmm0xff
