### ISSUE TITLE
2.6.5 直接引用报错

### ISSUE THREAD

**Issue by fanlilinSaber** [tigerAndBull/TABAnimated#226]
TABCacheManager.h
- (void)cacheProduction:(TABAnimatedProduction *)production
            tabAnimated:(TABViewAnimated *)tabAnimated;

xx/Pods/TABAnimated/TABAnimatedDemo/TABAnimated/Cache/TABAnimatedCacheManager.h:42:26 Expected a type

TABViewAnimated 没有声明或者引用

**Comment by tigerAndBull** [comment]
重新拉下
