### ISSUE TITLE
如果数据是分开的，但是在加载之前想先加载骨架屏，那个高度怎么设置呢

### ISSUE THREAD

**Issue by stupidchou** [tigerAndBull/TABAnimated#227]
![image](https://github.com/tigerAndBull/TABAnimated/assets/17778075/1464440d-cc10-4f94-a79c-3b10b91efd6a)
比如我这个页面，每个模块是不同的接口，那我想先展示骨架屏，但是我对应的模块有可能会返回没有数据，这个时候我的高度要怎么处理呢，我看你demo里面都是有数据的处理，如果返回的数据为空，我的高度如何去重制呢

**Comment by tigerAndBull** [comment]
高度设置固定值，骨架屏自动填充数据并映射，但是也会不准，这个时候需要设置高度微调
