### ISSUE TITLE
UICollectionView的cell用xib的话会崩

### ISSUE THREAD

**Issue by QiuDaniel** [tigerAndBull/TABAnimated#23]
rt

**Comment by tigerAndBull** [comment]
附件发来，没试过




------------------ 原始邮件 ------------------
发件人: "QiuDaniel"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 下午2:08
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] UICollectionView的cell用xib的话会崩 (#23)




rt

**Comment by tigerAndBull** [comment]
> rt

2.0.8已解决

**Comment by tigerAndBull** [comment]
还有一个注意点，不要在这里写死。

**Comment by tigerAndBull** [comment]
还有一个注意点，不要在这里写死。
![Screen Shot 2019-08-18 at 2 51 13 PM](https://user-images.githubusercontent.com/28705454/63221190-0e5b5f80-c1c8-11e9-94a8-fd294f2833c1.png)
