### ISSUE TITLE
无法通过 TABComponentManager.backgroundComponent 设置 tableViewCell 的背景色

### ISSUE THREAD

**Issue by zhuangyz** [tigerAndBull/TABAnimated#238]
### New Issue Checklist

* [ ] I have read the [Documentation](https://github.com/tigerAndBull/TABAnimated/tree/master/Documents)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/TABAnimated/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 17.6
 TABAnimated Version      | 2.6.6
 Xcode Version           | Xcode 15.2
 Repro rate              | all the time (100%)
 Repro with our demo prj | 
 Demo project link       | 

无法通过 TABComponentManager.backgroundComponent 设置 cell 的背景色，代码如下：

<img width="1001" alt="截屏2024-09-25 14 26 05" src="https://github.com/user-attachments/assets/3fa31b50-52e1-4fde-ae66-8000d62836dc">

搜索 backgroundComponent 发现 TABAnimated 库的代码只定义了该属性，没有其他地方引用到它
<img width="339" alt="截屏2024-09-25 14 20 30" src="https://github.com/user-attachments/assets/60bc7c82-5db7-450a-8bb9-a54854931641">

**Comment by tigerAndBull** [comment]
用链式语法设置是有问题。
可以用_tableView.tabAnimated.animatedBackgroundColor = UIColor.redColor;这种方式设置 @zhuangyz
