### ISSUE TITLE
tableView 的 tableHeaderView 没用

### ISSUE THREAD

**Issue by smile659974981** [tigerAndBull/TABAnimated#25]
我只想在tableview的tableHeaderView中使用，但是设置上去无用
在viewDidLoadl里我写了如下代码：
    self.tableView.tableHeaderView.tabAnimated = TABViewAnimated.new;
    [self.tableView.tableHeaderView tab_startAnimation];
但是并没有用，要怎么做才能在 tableView 的 tableHeaderView 中使用

**Comment by tigerAndBull** [comment]
你好，刚刚我对你的问题进行了排查, 这个问题和框架本身有关。
框架对于控制开关动画的控制视图本身不会被加入到动画组，它的所有subViews才会加入到动画组。
所以在当前版本下，你的headView的subViews才会有动画。
当然，这样的做法，对于headView是不合理的，后续会加入对headView的适配，
当前你需要做的是，在你当前使用方式的基础之上，将你当前headView，外层嵌套一个UIView，作为控制视图。
最后，谢谢你的提问。




------------------ 原始邮件 ------------------
发件人: "王志杰"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 下午4:50
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] tableView 的 tableHeaderView 没用 (#25)




我只想在tableview的tableHeaderView中使用，但是设置上去无用
 在viewDidLoadl里我写了如下代码：
 self.tableView.tableHeaderView.tabAnimated = TABViewAnimated.new;
 [self.tableView.tableHeaderView tab_startAnimation];
 但是并没有用，要怎么做才能在 tableView 的 tableHeaderView 中使用

**Comment by smile659974981** [comment]
好的，谢谢你的回答

**Comment by tigerAndBull** [comment]
> 我只想在tableview的tableHeaderView中使用，但是设置上去无用
> 在viewDidLoadl里我写了如下代码：
> self.tableView.tableHeaderView.tabAnimated = TABViewAnimated.new;
> [self.tableView.tableHeaderView tab_startAnimation];
> 但是并没有用，要怎么做才能在 tableView 的 tableHeaderView 中使用

最近在做头视图的适配，请问你的视图层级是怎样的？

**Comment by tigerAndBull** [comment]
> 好的，谢谢你的回答

2.0.8已解决

**Comment by lccdl** [comment]
第一次集成，用的版本v2.4.8版本，也遇到了相同的问题，按照文档直接设置tableViewHeader 的 `tabAnimated.adjustBlock `按照这个方法发现调整没有效果：

![image](https://user-images.githubusercontent.com/21123219/98783910-42f2b100-2435-11eb-8bd2-6ec2a90c2cea.png)

打断点才发现设置的时候tableViewHeader的tabAnimated 为空，并没有设置上。
于是在调整之前，实例了一个TABViewAnimated 对象并设置到tableViewHeader中之后解决问题

```
        _tableView.tabAnimated.showTableHeaderView = YES;
        view.tabAnimated = [TABViewAnimated new];
        view.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
            NSLog(@">>>>>>%@",manager.animations);
            manager.animation(0).down(3).height(20);
        };
        _tableView.tableHeaderView = view;
```
还有一个问题，就是不知道为什么，批量移除动画的时候会中断言，告诉我要单个获取下标动画实例，这样就导致移除一些动画的代码量变多，我不知道是不是因为是我设置的方式有问题，代码如下：
```
        _tableView.tabAnimated.showTableHeaderView = YES;
        _tableView.tabAnimated.canLoadAgain = YES;
        _tableView.tableHeaderView.tabAnimated = [TABViewAnimated new];
         _tableView.tableHeaderView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
            manager.animation(15).height(30);
            manager.animation(9).remove();
            manager.animation(22).remove();
            manager.animation(24).remove();
            manager.animation(25).remove();
            manager.animation(28).remove();
            manager.animation(30).remove();
            manager.animation(31).remove();
            manager.animation(32).remove();
            manager.animation(34).remove();
            manager.animation(18).remove();
            manager.animation(19).remove();
            manager.animation(7).up(30);
            //以下会中断言提醒
            //manager.animationsWithIndexs(19,23,18).remove();
        };
    
         _tableView.tableHeaderView = self.headerView;
```
![image](https://user-images.githubusercontent.com/21123219/98784677-6ec26680-2436-11eb-98f7-5b679e596fff.png)

**Comment by tigerAndBull** [comment]
@lccdl 
1. 当tableHeaderView无效时，你的做法是对的。
但是正常case应该是有效的，我猜测是因为框架在主动new的时候，你的tableHeaderView并不存在，或者new完成之后又被重新覆盖了。
2. 这个断言是2.4.8新增的，有点不靠谱，当index超过数组中最后一个元素时，也会走到这个断言
