### ISSUE TITLE
UITableView 中自适应高度的情况

### ISSUE THREAD

**Issue by janicezhw** [tigerAndBull/TABAnimated#26]
我看Demo中使用场景都是在 固定cell高度的情况，estimatedRowHeight = 0;

不知道是否可以在自适应高度的cell情况使用。 

感谢！

**Comment by tigerAndBull** [comment]
你好，动画的高度与cell是否是自适应高度无关，
您可以尽情尝试，如有问题，会给予解决。




------------------ 原始邮件 ------------------
发件人: "janicezhw"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 下午5:55
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] UITableView 中自适应高度的情况 (#26)




我看Demo中使用场景都是在 固定cell高度的情况，estimatedRowHeight = 0;
 
不知道是否可以在自适应高度的cell情况使用。
 
感谢！

**Comment by tigerAndBull** [comment]
> 我看Demo中使用场景都是在 固定cell高度的情况，estimatedRowHeight = 0;
> 
> 不知道是否可以在自适应高度的cell情况使用。
> 
> 感谢！

自适应高度的情况不可以，需要下个版本迭代🌝

**Comment by tigerAndBull** [comment]
> 我看Demo中使用场景都是在 固定cell高度的情况，estimatedRowHeight = 0;
> 
> 不知道是否可以在自适应高度的cell情况使用。
> 
> 感谢！

能否提供一个demo？

**Comment by janicezhw** [comment]
@

> > 我看Demo中使用场景都是在 固定cell高度的情况，estimatedRowHeight = 0;
> > 不知道是否可以在自适应高度的cell情况使用。
> > 感谢！
> 
> 能否提供一个demo？

我直接在demo中写了一个类，自适应cell高度的TableView。 
运行起来效果有问题：骨架遮罩会有重叠问题，并且会穿透显示出"testtesttest"类似这样的文字，并且高度好像也有些问题。
附件解压直接放入demo中即可查看。

[TestLayoutTableViewController.zip](https://github.com/tigerAndBull/TABAnimated/files/3219177/TestLayoutTableViewController.zip)

**Comment by tigerAndBull** [comment]
好的，谢谢反馈，后续版本排查处理。




------------------ 原始邮件 ------------------
发件人: "janicezhw"<notifications@github.com>;
发送时间: 2019年5月25日(星期六) 下午2:41
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] UITableView 中自适应高度的情况 (#26)




@
   
我看Demo中使用场景都是在 固定cell高度的情况，estimatedRowHeight = 0;
 不知道是否可以在自适应高度的cell情况使用。
 感谢！
  
能否提供一个demo？
  
我直接在demo中写了一个类，自适应cell高度的TableView。
 运行起来效果有问题：骨架遮罩会有重叠问题，并且会穿透显示出"testtesttest"类似这样的文字，并且高度好像也有些问题。
 附件解压直接放入demo中即可查看。
 
TestLayoutTableViewController.zip

**Comment by tigerAndBull** [comment]
> @
> 
> > > 我看Demo中使用场景都是在 固定cell高度的情况，estimatedRowHeight = 0;
> > > 不知道是否可以在自适应高度的cell情况使用。
> > > 感谢！
> > 
> > 
> > 能否提供一个demo？
> 
> 我直接在demo中写了一个类，自适应cell高度的TableView。
> 运行起来效果有问题：骨架遮罩会有重叠问题，并且会穿透显示出"testtesttest"类似这样的文字，并且高度好像也有些问题。
> 附件解压直接放入demo中即可查看。
> 
> [TestLayoutTableViewController.zip](https://github.com/tigerAndBull/TABAnimated/files/3219177/TestLayoutTableViewController.zip)
> ![7277675D-A150-447F-8D97-0C6712E7BC9E](https://user-images.githubusercontent.com/5327563/58365770-8680f480-7efb-11e9-87f6-aeb2bf05c606.png)

你好，目前UITableView的自适应高度已经适配好了，是否可以提供UICollectionView的demo？

**Comment by tigerAndBull** [comment]
多个版本前已做处理，没有反馈，默认已修正。
