### ISSUE TITLE
在10系统上无效？？

### ISSUE THREAD

**Issue by guuuJIe** [tigerAndBull/TABAnimated#27]
在10系统上无效？？

**Comment by guuuJIe** [comment]
可能是版本问题，不好意思

**Comment by tigerAndBull** [comment]
你好，在很早的版本之前没有适配10系统，请确认现在版本是否真的无效？




------------------ 原始邮件 ------------------
发件人: "guuuJIe"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 下午4:51
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 在10系统上无效？？ (#27)




可能是版本问题，不好意思

**Comment by guuuJIe** [comment]
有效

**Comment by tigerAndBull** [comment]
好的




------------------ 原始邮件 ------------------
发件人: "guuuJIe"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 下午5:43
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 在10系统上无效？？ (#27)




有效
