### ISSUE TITLE
为啥我的项目里面用的时候不起作用

### ISSUE THREAD

**Issue by cctvbtv123456** [tigerAndBull/TABAnimated#28]

**Comment by tigerAndBull** [comment]
> _No description provided._

有中文文档，请认真集成。

**Comment by cctvbtv123456** [comment]
我尝试了很多遍，在新创建的项目里面是有动画，但是在我公司项目里面就是没有动画(奇诡的是我打debug图层上了一下cell是存在的)，代码逻辑一模一样，

**Comment by tigerAndBull** [comment]
确认是否初始化了

**Comment by cctvbtv123456** [comment]
不好意思，今天敲的代码太多了，没初始化，尴尬了

**Comment by tigerAndBull** [comment]
> 不好意思，今天敲的代码太多了，没初始化，尴尬了

好的。

**Comment by cctvbtv123456** [comment]
我这边有个建议，TABComponentLayer这个文件中的#pragma mark - 链式语法下面的left、right、up、down、width、height这些名字希望加一个前缀 例如  tab_left、tab_right、.....，这样写不会和别的CALayer分类文件有冲突，我项目里面有这个问题，个人建议价格前缀，比较好，防冲突

**Comment by tigerAndBull** [comment]
是的，有人提过类似的问题，后续版本考虑改掉。
原来是为了简洁度。。。。




------------------ 原始邮件 ------------------
发件人: "cctvbtv123456"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 晚上9:52
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 为啥我的项目里面用的时候不起作用 (#28)




我这边有个建议，TABComponentLayer这个文件中的#pragma mark - 链式语法下面的left、right、up、down、width、height这些名字希望加一个前缀 例如  tab_left、tab_right、.....，这样写不会和别的CALayer分类文件有冲突，我项目里面有这个问题，个人建议价格前缀，比较好，防冲突
