### ISSUE TITLE
重写了UICollectionView可能会有影响项目里原有的CollectionView啊

### ISSUE THREAD

**Issue by liuzhao** [tigerAndBull/TABAnimated#29]
比如这个“UICollectionView+TABAnimated.h”

**Comment by tigerAndBull** [comment]
你好，请提供具体封装了什么。


------------------ 原始邮件 ------------------
发件人: "liuzhao"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 下午3:56
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] 重写了UICollectionView可能会有影响项目里原有的CollectionView啊 (#29)




比如这个“UICollectionView+TABAnimated.h”

**Comment by tigerAndBull** [comment]
> 比如这个“UICollectionView+TABAnimated.h”

[TABAnimated.zip](https://github.com/tigerAndBull/TABAnimated/files/3300062/TABAnimated.zip)
请配合尝试用这个即将发布的测试版本，如果长时间不回复或者已经使用了其他方案，会暂时将这个问题挂起。

**Comment by tigerAndBull** [comment]
看到这里的小伙伴们注意：
想必看到这里的，不论是UITableView还是UICollectionView代理方法都出现了混乱。也就是题意所言。
这个问题的原因是：将delegate或者dataSource方法封装在UITableView/UICollectionView的子类，那么意味着该方法的IMP地址对于所有UITableView和UICollectionView是唯一的，即归类对象所有。
所以基于目前的框架原理，是不可行的，也就是无法使用TABAnimated。

而方法混乱，这个在很早的版本就解决了，所以这个解释不知道是否符合题主的场景？
后续有人发现类似的问题，可以直接提issues给我。

**Comment by tigerAndBull** [comment]
> 看到这里的小伙伴们注意：
> 想必看到这里的，不论是UITableView还是UICollectionView代理方法都出现了混乱。也就是题意所言。
> 这个问题的原因是：将delegate或者dataSource方法封装在UITableView/UICollectionView的子类，那么意味着该方法的IMP地址对于所有UITableView和UICollectionView是唯一的，即归类对象所有。
> 所以基于目前的框架原理，是不可行的，也就是无法使用TABAnimated。
> 
> 而方法混乱，这个在很早的版本就解决了，所以这个解释不知道是否符合题主的场景？
> 后续有人发现类似的问题，可以直接提issues给我。

纠正：此类问题不会在版本中再发生，但是`将delegate或者dataSource方法封装在UITableView/UICollectionView的子类`的这种情况，会被TABAnimated排除在外，即无法使用。

**Comment by tigerAndBull** [comment]
> 比如这个“UICollectionView+TABAnimated.h”

影响原有UICollectionView是因为底层hook了代理方法。
