### ISSUE TITLE
怎么跟你博客上不一致。而且pod install 成功跟api很多不一致。

### ISSUE THREAD

**Issue by CoderYangFeiLong** [tigerAndBull/TABAnimated#30]

**Comment by tigerAndBull** [comment]
你好，我刚刚确认了一下，没问题呀，具体能提高给我吗？


------------------ 原始邮件 ------------------
发件人: "杨飞龙"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午2:49
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] 怎么跟你博客上不一致。而且pod install 成功跟api很多不一致。 (#30)

**Comment by CoderYangFeiLong** [comment]
指定版本号。
