### ISSUE TITLE
强烈希望作者适配动态高度tablieview

### ISSUE THREAD

**Issue by bullerliu** [tigerAndBull/TABAnimated#31]

**Comment by tigerAndBull** [comment]
你好，目前正在寻找比较的解决方案。

**Comment by bullerliu** [comment]
好的，希望你框架越来越成熟！

**Comment by tigerAndBull** [comment]
> 好的，希望你框架越来越成熟！

你好，目前UITableView的自适应高度已经适配好了，是否可以提供UICollectionView的自适应demo？

**Comment by bullerliu** [comment]
你把代码传上去，我们项目开始全部用你这套框架！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: tigerAndBull <notifications@github.com>
发送时间: 2019年6月20日 17:59
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com>
抄送: bullerliu <2511290702@qq.com>, Author <author@noreply.github.com>
主题: 回复：[tigerAndBull/TABAnimated] 强烈希望作者适配动态高度tablieview (#31)



 
好的，希望你框架越来越成熟！
  
你好，目前UITableView的自适应高度已经适配好了，是否可以提供UICollectionView的自适应demo？

**Comment by tigerAndBull** [comment]
> 你把代码传上去，我们项目开始全部用你这套框架！ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: tigerAndBull <notifications@github.com> 发送时间: 2019年6月20日 17:59 收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com> 抄送: bullerliu <2511290702@qq.com>, Author <author@noreply.github.com> 主题: 回复：[tigerAndBull/TABAnimated] 强烈希望作者适配动态高度tablieview (#31) 好的，希望你框架越来越成熟！ 你好，目前UITableView的自适应高度已经适配好了，是否可以提供UICollectionView的自适应demo？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

呃呃，进群领测试版😎

**Comment by tigerAndBull** [comment]
最新发现还是有问题，2.1.8已经修复，望知晓。
