### ISSUE TITLE
导入框架后,没有用到动画功能崩溃

### ISSUE THREAD

**Issue by wangleios** [tigerAndBull/TABAnimated#32]
- (NSInteger)tab_tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section 崩溃在这个方法里

**Comment by tigerAndBull** [comment]
> * (NSInteger)tab_tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section 崩溃在这个方法里

排查一下工程中是否交换了+load方法

**Comment by wangleios** [comment]
有别的第三方也交换了load方法.这种情况只能是删掉其中一个吗

**Comment by tigerAndBull** [comment]
> 有别的第三方也交换了load方法.这种情况只能是删掉其中一个吗

工程中是否存在UITalbeView的子类？

**Comment by wangleios** [comment]
有的,

**Comment by tigerAndBull** [comment]
> 有的,

在tableView的子类中 self.delegate = self?

**Comment by wangleios** [comment]
self.delegate = self这个断言我记得你之前已经去掉了  我导入的是一个tableview的空视图第三方,里面也是在load交换了tableview的代理方法

**Comment by tigerAndBull** [comment]
> self.delegate = self这个断言我记得你之前已经去掉了 我导入的是一个tableview的空视图第三方,里面也是在load交换了tableview的代理方法

是否可以将其提供给我呢？我看是否能解决。原则上交换多次，需要确保IMP指针的指向性必须是对的，
你这边崩溃的原因，初步判断应该是交换了父类的方法，稍后我会发给你一个测试版本。

**Comment by wangleios** [comment]
pod 'LYEmptyView'    这个,麻烦了

**Comment by tigerAndBull** [comment]
[TABAnimated.zip](https://github.com/tigerAndBull/TABAnimated/files/3300001/TABAnimated.zip)
这是一个即将发布的测试版本，我不确定是否能解决你的问题。

**Comment by tigerAndBull** [comment]
如果不能，回复我，后续会根据你提供的第三方进行分析。

**Comment by wangleios** [comment]
好的,我稍后试一下

**Comment by wangleios** [comment]
你好,我刚才试了一下,没有解决这个问题,我先暂时把那个去了,看后续有没有好的方案吧

**Comment by tigerAndBull** [comment]
> 你好,我刚才试了一下,没有解决这个问题,我先暂时把那个去了,看后续有没有好的方案吧

那应该是多次交换的问题，不要报太大期望哦。

**Comment by tigerAndBull** [comment]
那应该是多次交换的问题，不要报太大期望哦。不过有一个方案，你可以将`LYEmptyView `私有化，即不用方法交换进行封装，也可以将`TABAnimated`私有化，不使用方法进行封装。

**Comment by wangleios** [comment]
好的,我有时间试试,谢谢大佬回复

**Comment by tigerAndBull** [comment]
没事，因为发给您的测试版，解决了一个难点，极大提高了集成的速度，并将提供了比较好的集成方案，所以急着发布，你的问题在这个版本不做处理了。------------------ 原始邮件 ------------------
发件人: "wangleios"<notifications@github.com>
发送时间: 2019年6月18日(星期二) 下午2:32
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 导入框架后,没有用到动画功能崩溃 (#32)



好的,我有时间试试,谢谢大佬回复
 
&mdash;

**Comment by tigerAndBull** [comment]
> 好的,我有时间试试,谢谢大佬回复

你好，我查看了`LYEmptyView `的源码，并不会和我的库产生冲突哦，还有其他原因导致吗？子类到底是怎么封装的呢？

**Comment by wangleios** [comment]
哦哦，最近在赶项目，有可能是代码问题导致的崩溃，我忙完这一阵单独弄个demo看看是什么问题导致的


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: tigerAndBull <notifications@github.com>
发送时间: 2019年6月20日 12:06
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com>
抄送: wangleios <1160902483@qq.com>, Author <author@noreply.github.com>
主题: 回复：[tigerAndBull/TABAnimated] 导入框架后,没有用到动画功能崩溃 (#32)



 
好的,我有时间试试,谢谢大佬回复
  
你好，我查看了LYEmptyView 的源码，并不会和我的库产生冲突哦，还有其他原因导致吗？子类到底是怎么封装的呢？

**Comment by VincentChow** [comment]
已确认与QMUI发生冲突，当使用QMUIScrollAnimator设置属性scrollview时，会执行scrollView.delegate = self;

**Comment by tigerAndBull** [comment]
麻烦您github上提一个issue，有时间我看看怎么处理。------------------ 原始邮件 ------------------
发件人: "Vincent Chow"<notifications@github.com>
发送时间: 2019年7月23日(星期二) 下午4:15
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 导入框架后,没有用到动画功能崩溃 (#32)



已确认与QMUI发生冲突，当使用QMUIScrollAnimator设置属性scrollview时，会执行scrollView.delegate = self;
 
&mdash;

**Comment by tigerAndBull** [comment]
没有仔细看哈，不是邮件，我收到了------------------ 原始邮件 ------------------
发件人: "Vincent Chow"<notifications@github.com>
发送时间: 2019年7月23日(星期二) 下午4:15
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 导入框架后,没有用到动画功能崩溃 (#32)



已确认与QMUI发生冲突，当使用QMUIScrollAnimator设置属性scrollview时，会执行scrollView.delegate = self;
 
&mdash;

**Comment by tigerAndBull** [comment]
> 已确认与QMUI发生冲突，当使用QMUIScrollAnimator设置属性scrollview时，会执行scrollView.delegate = self;

你有测试demo吧？可以把具体情况提供一下，麻烦了。

**Comment by tigerAndBull** [comment]
> scrollView

最新代码取消hook setDelegate方法，应该会解决与QMUI的冲突

**Comment by hurricane3807** [comment]
你好。你们似乎最新版本又把这个问题改回去了，似乎又出现了这个冲突问题

**Comment by tigerAndBull** [comment]
> 你好。你们似乎最新版本又把这个问题改回去了，似乎又出现了这个冲突问题

冲突问题提供demo哈，也没有改回去的，把demo发给我，我来看看。

**Comment by tigerAndBull** [comment]
> * (NSInteger)tab_tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section 崩溃在这个方法里

最近我写了一个版本，取消了AOP，不知道是否能参与测试？

**Comment by tigerAndBull** [comment]
> 你好。你们似乎最新版本又把这个问题改回去了，似乎又出现了这个冲突问题


最近我写了一个版本，取消了AOP，不知道是否能参与测试？

**Comment by tigerAndBull** [comment]
v2.5.2已适配第三方库，如QMUI，RxSwift.
