### ISSUE TITLE
storyboard怎么使用？

### ISSUE THREAD

**Issue by Gosling-Dong** [tigerAndBull/TABAnimated#34]
tableview.tabAnimated = [TABTableAnimated animatedWithCellClass:[TestAnimateTableViewCell class] cellHeight:100];
    
    tableview.tabAnimated.categoryBlock = ^(UIView * _Nonnull view) {
        view.animation(1).down(3).height(12).toShortAnimation();
        view.animation(2).height(12).width(110).toLongAnimation();
        view.animation(3).down(-5).height(12);
    };

不能用于storyboard

**Comment by tigerAndBull** [comment]
确定了xib创建UITableView，注意不是UITableViewCell，无法加载动画库，原因是不走setDelegate方法， 测试其他任何方式均可以 不知道你说的是否和这种情况一致？------------------ 原始邮件 ------------------
发件人: "Gosling-Dong"<notifications@github.com>
发送时间: 2019年7月4日(星期四) 下午4:08
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] storyboard怎么使用？ (#34)



tableview.tabAnimated = [TABTableAnimated animatedWithCellClass:[TestAnimateTableViewCell class] cellHeight:100];
 tableview.tabAnimated.categoryBlock = ^(UIView * _Nonnull view) {     view.animation(1).down(3).height(12).toShortAnimation();     view.animation(2).height(12).width(110).toLongAnimation();     view.animation(3).down(-5).height(12); };  
不能用于storyboard
 
&mdash;

**Comment by Gosling-Dong** [comment]
我用storyboard创建的UITableView   ; UITableViewCell也是在storyboard上的 这样的创建方式是不是无法加载动画库？

**Comment by tigerAndBull** [comment]
是的，这个是已确定的。 ------------------ 原始邮件 ------------------
发件人: "Gosling-Dong"<notifications@github.com>
发送时间: 2019年7月4日(星期四) 下午4:18
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] storyboard怎么使用？ (#34)



我用storyboard创建的UITableView   ; UITableViewCell也是在storyboard上的 这样的创建方式是不是无法加载动画库？
 
&mdash;

**Comment by Gosling-Dong** [comment]
好的 多谢解答

**Comment by tigerAndBull** [comment]
> 好的 多谢解答

2.0.0.20190919_beta 版本已经适配了这种情况，目前没有发布2.0.0正式版，只可以在github上下载
