### ISSUE TITLE
会有一条分割线在上面怎么解决

### ISSUE THREAD

**Issue by xuhuaping** [tigerAndBull/TABAnimated#35]
![image](https://user-images.githubusercontent.com/18001988/60691876-633b6300-9f05-11e9-8d35-8780efb0575e.png)

**Comment by tigerAndBull** [comment]
开启角标，查看角标是几，将其remove掉。------------------ 原始邮件 ------------------
发件人: "xuhuaping"<notifications@github.com>
发送时间: 2019年7月5日(星期五) 上午9:15
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] 会有一条分割线在上面怎么解决 (#35)




 
&mdash;

**Comment by xuhuaping** [comment]
好的 谢谢

**Comment by tigerAndBull** [comment]
最新版已经修复了问题，不需要在remove，望知晓
