### ISSUE TITLE
tableView中 ,我不想显示tableHeaderView ,只想显示cell,请问下有什么好的方法解决吗

### ISSUE THREAD

**Issue by xuhuaping** [tigerAndBull/TABAnimated#36]

**Comment by tigerAndBull** [comment]
目前没有此属性，本人使用UITableView很少。------------------ 原始邮件 ------------------
发件人: "xuhuaping"<notifications@github.com>
发送时间: 2019年7月5日(星期五) 上午10:36
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] tableView中 ,我不想显示tableHeaderView ,只想显示cell,请问下有什么好的方法解决吗 (#36)


 
&mdash;

**Comment by xuhuaping** [comment]
大佬都是用什么作列表

**Comment by tigerAndBull** [comment]
2.1.5已修正
