### ISSUE TITLE
界面会显示tab_testtesttest.......这样的字符

### ISSUE THREAD

**Issue by xuhuaping** [tigerAndBull/TABAnimated#37]

**Comment by tigerAndBull** [comment]
请提供使用版本号，应用场景。------------------ 原始邮件 ------------------
发件人: "xuhuaping"<notifications@github.com>
发送时间: 2019年7月5日(星期五) 上午10:58
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] 界面会显示tab_testtesttest.......这样的字符 (#37)


 
&mdash;

**Comment by xuhuaping** [comment]
最新版本, 出现在tableHeaderView里面 ,我把view里面的都删了,还是有那些字符，cell正常

**Comment by tigerAndBull** [comment]
是开始动画的瞬间有字，还是结束动画后有字？------------------ 原始邮件 ------------------
发件人: "xuhuaping"<notifications@github.com>
发送时间: 2019年7月5日(星期五) 中午11:19
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 界面会显示tab_testtesttest.......这样的字符 (#37)



最新版本, 出现在tableHeaderView里面 ,我把view里面的都删了,还是有那些字符，cell正常
 
&mdash;

**Comment by tigerAndBull** [comment]
> 最新版本, 出现在tableHeaderView里面 ,我把view里面的都删了,还是有那些字符，cell正常

你提的两个问题，
其中，现在UITableViewHeaderView不会默认启动，通过设置showTableHeaderView可以更改。
字的问题，我猜测你是说结束动画后有字？这属于bug，我做了修改。

[TABAnimated.zip](https://github.com/tigerAndBull/TABAnimated/files/3361026/TABAnimated.zip)

**Comment by xuhuaping** [comment]
好的 我试试看

**Comment by tigerAndBull** [comment]
> 好的 我试试看

记得反馈。

**Comment by tigerAndBull** [comment]
> 最新版本, 出现在tableHeaderView里面 ,我把view里面的都删了,还是有那些字符，cell正常

2.1.5已修正。
