### ISSUE TITLE
用的2.1.7版本 不知道为什么tab_endAnimationEaseOut停止动画失效  tableview上重叠两个Cell,但是demo为什么没有问题 不知道原因

### ISSUE THREAD

**Issue by huohongxu** [tigerAndBull/TABAnimated#39]

**Comment by tigerAndBull** [comment]
能提供一个复现的demo吗

**Comment by huohongxu** [comment]
可以   demo发到哪里

**Comment by tigerAndBull** [comment]
回复可以添加附件------------------ 原始邮件 ------------------
发件人: "huohongxu"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 中午12:45
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 用的2.1.7版本 不知道为什么tab_endAnimationEaseOut停止动画失效  tableview上重叠两个Cell,但是demo为什么没有问题 不知道原因 (#39)



可以   demo发到哪里
 
&mdash;

**Comment by huohongxu** [comment]
已发

**Comment by tigerAndBull** [comment]
> 已发

如果希望最快解决问题，就使用2.1.3稳定版本，不过少了一些新的api。

**Comment by tigerAndBull** [comment]
> 已发

2.1.8已经解决，望知晓
