### ISSUE TITLE
和WMPageController有冲突

### ISSUE THREAD

**Issue by iotjin** [tigerAndBull/TABAnimated#41]
切换用WMPageController库写的顶部标题或者滑动手势切换页面，  #import "UITableView+TABAnimated.h"这个文件里面的529行报错
![image](https://user-images.githubusercontent.com/9895575/63483258-5f23ce80-c4ce-11e9-9060-589e25539eba.png)

**Comment by tigerAndBull** [comment]
> 切换用WMPageController库写的顶部标题或者滑动手势切换页面， #import "UITableView+TABAnimated.h"这个文件里面的529行报错
> ![image](https://user-images.githubusercontent.com/9895575/63483258-5f23ce80-c4ce-11e9-9060-589e25539eba.png)

野指针，看看是不是循环引用导致的，或者你提供具体使用demo给我

**Comment by iotjin** [comment]
[TEST222.zip](https://github.com/tigerAndBull/TABAnimated/files/3577311/TEST222.zip)
前段时间一直没空,早上我抽出来个小demo,我之前写的demo中使用WMPageController的地方并没有调用TABAnimated,我是偶然发现点击那个功能的切换按钮会使项目崩溃,错误定位是图上位置,没加入TABAnimated之前不会报错, 你可以看一下TwoVC,把注释的代码放开,就不会报错,但是按照我压缩包现在的程序就会报错

**Comment by tigerAndBull** [comment]
> [TEST222.zip](https://github.com/tigerAndBull/TABAnimated/files/3577311/TEST222.zip)
> 前段时间一直没空,早上我抽出来个小demo,我之前写的demo中使用WMPageController的地方并没有调用TABAnimated,我是偶然发现点击那个功能的切换按钮会使项目崩溃,错误定位是图上位置,没加入TABAnimated之前不会报错, 你可以看一下TwoVC,把注释的代码放开,就不会报错,但是按照我压缩包现在的程序就会报错

代码我看了，你自己循环引用了
![Screen Shot 2019-09-05 at 11 57 12 AM](https://user-images.githubusercontent.com/28705454/64310860-7b4a6400-cfd4-11e9-818b-6363e860992f.png)

**Comment by iotjin** [comment]
我给你发的代码,是我在OneVC里添加了开始动画的代码,之前发的的报错,我只导入了TABAnimated,并没有在功能里调用,然后点击标题切换界面就崩了。我把TABAnimated先从项目中去掉,再点击是没有问题的,我看了一下控制器也都释放了,是不是我通过twoVC继承OneVC这种方式有问题?

**Comment by tigerAndBull** [comment]
我给你截图了，你在初始化里的使用了self指针------------------ 原始邮件 ------------------
发件人: "iotjin"<notifications@github.com>
发送时间: 2019年9月6日(星期五) 下午2:26
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 和WMPageController有冲突 (#41)



我给你发的代码,是我在OneVC里添加了开始动画的代码,之前发的的报错,我只导入了TABAnimated,并没有在功能里调用,然后点击标题切换界面就崩了。我把TABAnimated先从项目中去掉,再点击是没有问题的,我看了一下控制器也都释放了,是不是我通过twoVC继承OneVC这种方式有问题?
 
&mdash;
