### ISSUE TITLE
tableView上拉刷新时会出现上移

### ISSUE THREAD

**Issue by xiaopohaiwx** [tigerAndBull/TABAnimated#43]
tableView关闭预估高度，正常上拉刷新时过渡平滑，但是加上骨架后上拉刷新后会出现上移的问题，不知道是我写的问题还是什么
Demo:  https://github.com/xiaopohaiwx/AnimatedDemo.git

**Comment by tigerAndBull** [comment]
> tableView关闭预估高度，正常上拉刷新时过渡平滑，但是加上骨架后上拉刷新后会出现上移的问题，不知道是我写的问题还是什么
> Demo: https://github.com/xiaopohaiwx/AnimatedDemo.git

MJRefresh的调整+TABAnimated的reloadData造成，你没有下拉刷新的时候，不要调用红色部分的代码
![CD8F8210-FD64-451B-A46E-D84E0EA80E9D](https://user-images.githubusercontent.com/28705454/65237880-19c6e100-db0e-11e9-8b91-e1d2f488c401.png)

**Comment by xiaopohaiwx** [comment]
> > tableView关闭预估高度，正常上拉刷新时过渡平滑，但是加上骨架后上拉刷新后会出现上移的问题，不知道是我写的问题还是什么
> > Demo: https://github.com/xiaopohaiwx/AnimatedDemo.git
> 
> MJRefresh的调整+TABAnimated的reloadData造成，你没有下拉刷新的时候，不要调用红色部分的代码
> ![CD8F8210-FD64-451B-A46E-D84E0EA80E9D](https://user-images.githubusercontent.com/28705454/65237880-19c6e100-db0e-11e9-8b91-e1d2f488c401.png)



> > tableView关闭预估高度，正常上拉刷新时过渡平滑，但是加上骨架后上拉刷新后会出现上移的问题，不知道是我写的问题还是什么
> > Demo: https://github.com/xiaopohaiwx/AnimatedDemo.git
> 
> MJRefresh的调整+TABAnimated的reloadData造成，你没有下拉刷新的时候，不要调用红色部分的代码
> ![CD8F8210-FD64-451B-A46E-D84E0EA80E9D](https://user-images.githubusercontent.com/28705454/65237880-19c6e100-db0e-11e9-8b91-e1d2f488c401.png)

感谢
