### ISSUE TITLE
Carthage 支持

### ISSUE THREAD

**Issue by qcasxy** [tigerAndBull/TABAnimated#44]
不知到作者能否提供一下对Carthage依赖管理的支持

**Comment by tigerAndBull** [comment]
> 不知到作者能否提供一下对Carthage依赖管理的支持

已经添加，但没有将实时预览工具库放入其中。

**Comment by qcasxy** [comment]
好的 谢谢 我先拉下来试下

**Comment by qcasxy** [comment]
这个包可能有点问题，我加载到项目里运行之后报下面这个错误：

> dyld: Library not loaded: @rpath/TABAnimated.framework/TABAnimated
> Referenced from: /private/var/containers/Bundle/Application/B2DA90EF-35DC-46D1-957A-592C29F7C091/QCSwiftProject Dev.app/QCSwiftProject Dev
>   Reason: image not found

我参照网上的方法修改后第一次运行没问题，但是第二次开始还是会出现同样的问题
参考1: [https://www.jianshu.com/p/9aecbdb8ab05](https://www.jianshu.com/p/9aecbdb8ab05)
参考2: [https://www.jianshu.com/p/8005a1ba59e9](https://www.jianshu.com/p/8005a1ba59e9)

**Comment by tigerAndBull** [comment]
> 这个包可能有点问题，我加载到项目里运行之后报下面这个错误：
> 
> > dyld: Library not loaded: @rpath/TABAnimated.framework/TABAnimated
> > Referenced from: /private/var/containers/Bundle/Application/B2DA90EF-35DC-46D1-957A-592C29F7C091/QCSwiftProject Dev.app/QCSwiftProject Dev
> > Reason: image not found
> 
> 我参照网上的方法修改后第一次运行没问题，但是第二次开始还是会出现同样的问题
> 参考1: https://www.jianshu.com/p/9aecbdb8ab05
> 参考2: https://www.jianshu.com/p/8005a1ba59e9

我拉到测试工程中没有问题，你确认一下呢？没怎么用这个管理包。

**Comment by tigerAndBull** [comment]
> 这个包可能有点问题，我加载到项目里运行之后报下面这个错误：
> 
> > dyld: Library not loaded: @rpath/TABAnimated.framework/TABAnimated
> > Referenced from: /private/var/containers/Bundle/Application/B2DA90EF-35DC-46D1-957A-592C29F7C091/QCSwiftProject Dev.app/QCSwiftProject Dev
> > Reason: image not found
> 
> 我参照网上的方法修改后第一次运行没问题，但是第二次开始还是会出现同样的问题
> 参考1: https://www.jianshu.com/p/9aecbdb8ab05
> 参考2: https://www.jianshu.com/p/8005a1ba59e9

这是我的测试工程
[TestProject.zip](https://github.com/tigerAndBull/TABAnimated/files/3661019/TestProject.zip)
