### ISSUE TITLE
针对tableView的SectionHeaderView似乎是没有效果呢

### ISSUE THREAD

**Issue by jniosdeveloper** [tigerAndBull/TABAnimated#47]
我设置了继承自UITableViewHeaderFooterView的headerView，但是没有看见效果，是不支持？

**Comment by jniosdeveloper** [comment]
就是在TableNormalViewController.m中，我新增了下面的代码：
```
-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section{
    TestTableHeaderFooterView *headerView = [tableView dequeueReusableHeaderFooterViewWithIdentifier:@"TestTableHeaderFooterView"];
    return headerView;
}
-(CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section{
    return 100;
}
-(UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section{
    return UIView.new;
}
```
并且在tableView的懒加载中打开了（[_tableView.tabAnimated addHeaderViewClass:[TestTableHeaderFooterView class] viewHeight:100];）的注释，并新增 （[_tableView registerClass:TestTableHeaderFooterView.class forHeaderFooterViewReuseIdentifier:@"TestTableHeaderFooterView"];）去注册headerFooterView，然后运行查看没有发现这个HeaderFooterView有啥动画效果呢 
![Uploading QQ20191010-173416@2x.png…]()

**Comment by tigerAndBull** [comment]
> 就是在TableNormalViewController.m中，我新增了下面的代码：
> 
> ```
> -(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section{
>     TestTableHeaderFooterView *headerView = [tableView dequeueReusableHeaderFooterViewWithIdentifier:@"TestTableHeaderFooterView"];
>     return headerView;
> }
> -(CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section{
>     return 100;
> }
> -(UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section{
>     return UIView.new;
> }
> ```
> 
> 并且在tableView的懒加载中打开了（[_tableView.tabAnimated addHeaderViewClass:[TestTableHeaderFooterView class] viewHeight:100];）的注释，并新增 （[_tableView registerClass:TestTableHeaderFooterView.class forHeaderFooterViewReuseIdentifier:@"TestTableHeaderFooterView"];）去注册headerFooterView，然后运行查看没有发现这个HeaderFooterView有啥动画效果呢 ，我的效果无法截图，我试试能不能邮件给你
> TestTableHeaderFooterView.m里面设置了背景颜色为红色：
> 
> ```
> {
>         self.backgroundView = ({
>         UIView * view = [[UIView alloc] initWithFrame:self.bounds];
>         view.backgroundColor = UIColor.redColor;
>         view;
>         });
>     }
> ```

github可以发附加，拖进来。

**Comment by jniosdeveloper** [comment]
<img width="414" alt="QQ20191010-174547@2x" src="https://user-images.githubusercontent.com/21004617/66558248-d21ffc00-eb85-11e9-9e44-f239550debe4.png">

**Comment by tigerAndBull** [comment]
> 这个是我改后的效果图，改的代码就是上面我提到的那些，中间红色的部分就是工程留下的HeaderFooterView，我设置了一个红色
> <img alt="QQ20191010-174547@2x" width="414" src="https://user-images.githubusercontent.com/21004617/66558248-d21ffc00-eb85-11e9-9e44-f239550debe4.png">

发附件。

**Comment by jniosdeveloper** [comment]
[AnimatedDemo.zip](https://github.com/tigerAndBull/TABAnimated/files/3711862/AnimatedDemo.zip)

**Comment by tigerAndBull** [comment]
> [AnimatedDemo.zip](https://github.com/tigerAndBull/TABAnimated/files/3711862/AnimatedDemo.zip)

最近github速度上不来，demo下载太慢了，你是方法用错了！
请用下面这个
`- (void)addHeaderViewClass:(__nonnull Class)headerViewClass
                viewHeight:(CGFloat)viewHeight
                 toSection:(NSInteger)section`

**Comment by zhuleiRedTea** [comment]
我试了方法换了`- (void)addHeaderViewClass:(__nonnull Class)headerViewClass viewHeight:(CGFloat)viewHeight toSection:(NSInteger)section`还是没有动画效果啊.是不是不支持组头动画
