### ISSUE TITLE
随机弹出"实时预览"页面

### ISSUE THREAD

**Issue by chenchaohui6666** [tigerAndBull/TABAnimated#48]
大佬，使用这个框架会随机弹出"实时预览"页面
![EC48571426B1BE5CA338AD1BBFCC30E4](https://user-images.githubusercontent.com/48901808/66725919-a2644300-ee68-11e9-9857-4aa60b6cd4f3.png)，请问是什么情况？怎么处理？

**Comment by chenchaohui6666** [comment]
已解决：
将下面这段代码注释掉就行：
#ifdef DEBUG
    // 骨架屏core部分不依赖reveal工具
    // reveal工具依赖骨架屏core，实时预览效果，无需编译
    // 请务必放在debug环境下
    [[TABAnimatedBall shared] install];
#endif

**Comment by tigerAndBull** [comment]
> 大佬，使用这个框架会随机弹出"实时预览"页面
> ![EC48571426B1BE5CA338AD1BBFCC30E4](https://user-images.githubusercontent.com/48901808/66725919-a2644300-ee68-11e9-9857-4aa60b6cd4f3.png)，请问是什么情况？怎么处理？

点击悬浮球就弹出了，不是随机的。
注释就不会启动悬浮球了。
这个工具不影响框架本身的逻辑，随便你～
