### ISSUE TITLE
大概率偶发出现位置错乱

### ISSUE THREAD

**Issue by WeiCY** [tigerAndBull/TABAnimated#51]

**Comment by WeiCY** [comment]
在我使用的过程中，我是一个弹出框view，在使用中有时候显示正常，有时候就会错乱。
我就想咨询一下整体的使用情况。
1.序号这个是如何排序的？是根据加入顺序吗？
2.为什么我只添加了十几个控件，却显示出20+的序号？
3.这个向左向右偏移是如何判断的  是否可以不写  不写会根据什么显示  如果需要写  是不是需要吧每个控件都设置一遍

**Comment by tigerAndBull** [comment]
> 在我使用的过程中，我是一个弹出框view，在使用中有时候显示正常，有时候就会错乱。
> 我就想咨询一下整体的使用情况。
> 1.序号这个是如何排序的？是根据加入顺序吗？
> 2.为什么我只添加了十几个控件，却显示出20+的序号？
> 3.这个向左向右偏移是如何判断的 是否可以不写 不写会根据什么显示 如果需要写 是不是需要吧每个控件都设置一遍

1. 集成需要阅读文档成本
2. 有时候错乱的问题，需要提供复现demo。
其他问题请阅读文档，目前都是没有遇到的，或者加上demo带过来。
