### ISSUE TITLE
设置按钮placeholder后能不能改变当前骨架的背景颜色

### ISSUE THREAD

**Issue by WeiCY** [tigerAndBull/TABAnimated#52]
能否只关闭某一个子视图的骨架或者改变某一个视图骨架的颜色

**Comment by WeiCY** [comment]
就是我一个关闭按钮  不想让他有背景色 且不想让他整个图片填充在关闭按钮区域内

**Comment by tigerAndBull** [comment]
> 就是我一个view上有一个关闭按钮 在使用了骨架后 关闭按钮也会变成骨架 我不想让他变成骨架 或者不想让他有背景色 且不想让他整个图片填充在关闭按钮区域内 能不能实现？

这个最好使用穿透，未开放api。
可以用placeholder取代，通过CALayer的mode切换图片mode。
