### ISSUE TITLE
能否在加载完成后再次加载骨架屏

### ISSUE THREAD

**Issue by WeiCY** [tigerAndBull/TABAnimated#53]
如题，我在一个view上使用了您的骨架屏，点击按钮会弹出含有骨架屏的view，第一次点击会出现骨架。再点击另一个按钮，弹出视图不会再次加载骨架屏。我已经把canLoadAgain设置为yes。还是不行。请问有没有方法可以让他再次开启骨架屏

**Comment by tigerAndBull** [comment]
> 如题，我在一个view上使用了您的骨架屏，点击按钮会弹出含有骨架屏的view，第一次点击会出现骨架。再点击另一个按钮，弹出视图不会再次加载骨架屏。我已经把canLoadAgain设置为yes。还是不行。请问有没有方法可以让他再次开启骨架屏

就是按照此属性进行多次加载，请提供属性失效的demo。

**Comment by WeiCY** [comment]
链接: https://pan.baidu.com/s/1DNN6m4Si_i2SAfiD6Tk4Pg 提取码: k33h 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by tigerAndBull** [comment]
> 您好，我对demo进行了修改，您请看下。
> 链接: https://pan.baidu.com/s/1YMwA9j7uNiroCVz9iWRjgg 提取码: wsn2 复制这段内容后打开百度网盘手机App，操作更方便哦

因为我的某个疏忽导致，你把附件里的这个拿来临时使用，改动不大，就加了一行代码。

[tabAnimatedDemo.zip](https://github.com/tigerAndBull/TABAnimated/files/3788961/tabAnimatedDemo.zip)

**Comment by tigerAndBull** [comment]
> 您好，我对demo进行了修改，您请看下。
> 链接: https://pan.baidu.com/s/1YMwA9j7uNiroCVz9iWRjgg 提取码: wsn2 复制这段内容后打开百度网盘手机App，操作更方便哦

v2.2.5，修复了此问题，已发布。
