### ISSUE TITLE
Error use tableView registerNib

### ISSUE THREAD

**Issue by ofEver** [tigerAndBull/TABAnimated#54]
[self.tableView registerNib:[UINib nibWithNibName:@"XX" bundle:nil] forCellReuseIdentifier:@"XX"];

self.tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[XX class]];

log:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'cell reuse indentifier in nib (XIBTableViewCell) does not match the identifier used to register the nib (tab_XIBTableViewCell)'

**Comment by tigerAndBull** [comment]
delete your `register code`.




------------------ Original ------------------

**Comment by ofEver** [comment]
> delete your `register code`.
> […](#)
> ------------------ Original ------------------ From: "ofEver";<notifications@github.com>; Send time: Thursday, Nov 7, 2019 8:03 PM To: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>; Cc: "Subscribed"<subscribed@noreply.github.com>; Subject: [tigerAndBull/TABAnimated] Error use tableView registerNib (#54) [self.tableView registerNib:[UINib nibWithNibName:@"XX" bundle:nil] forCellReuseIdentifier:@"XX"]; self.tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[XX class]]; log: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'cell reuse indentifier in nib (XIBTableViewCell) does not match the identifier used to register the nib (tab_XIBTableViewCell)' — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

it working correctly when i delete xib identifier.Thanks
