### ISSUE TITLE
我pod版本是2.1.4版本，会报这个错

### ISSUE THREAD

**Issue by weqeo** [tigerAndBull/TABAnimated#56]
```
    // 新回调
    tableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
        manager.animation(1).down(3).height(12);
        manager.animation(2).height(12).width(110);
        manager.animation(3).down(-5).height(12);
    };
```
上面这句，TABComponentManager类在库里面没有，adjustBlock这个block也没有找到

**Comment by weqeo** [comment]
我更新到2.2.1版本后，这个错误就没了～

**Comment by tigerAndBull** [comment]
> ```
>     // 新回调
>     tableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
>         manager.animation(1).down(3).height(12);
>         manager.animation(2).height(12).width(110);
>         manager.animation(3).down(-5).height(12);
>     };
> ```
> 
> 上面这句，TABComponentManager类在库里面没有，adjustBlock这个block也没有找到

部分老版本在发布时，存在一些问题，并没有移除掉。
用2.2.x版本不会出现此类问题。
