### ISSUE TITLE
iOS13里面自定义的View会多遍历出来一个子View

### ISSUE THREAD

**Issue by iamlay** [tigerAndBull/TABAnimated#57]
在iOS13中，父View使用TABAnimated，有时候加载的时候会多遍历出来一个子View

**Comment by tigerAndBull** [comment]
> 在iOS13中，父View使用TABAnimated，有时候加载的时候会多遍历出来一个子View

可以提供一下复现demo，一般self.view不作为控制视图哈～

**Comment by tigerAndBull** [comment]
> 在iOS13中，父View使用TABAnimated，有时候加载的时候会多遍历出来一个子View

您也可以查看视图层，截图我康康

**Comment by iamlay** [comment]
![截屏2019-11-18下午7 51 45](https://user-images.githubusercontent.com/15210476/69050657-79be0300-0a3d-11ea-958c-6d6858d6af4e.png)
![截屏2019-11-18下午7 52 41](https://user-images.githubusercontent.com/15210476/69050658-7a569980-0a3d-11ea-9ae8-2db1c5443422.png)
![截屏2019-11-18下午7 53 38](https://user-images.githubusercontent.com/15210476/69050659-7a569980-0a3d-11ea-95a3-71015c7899c2.png)
![WechatIMG113](https://user-images.githubusercontent.com/15210476/69050660-7aef3000-0a3d-11ea-9672-82b79a6ed0a1.jpeg)

**Comment by tigerAndBull** [comment]
搜索框用没有意义哦，把控制视图改为表格，再做相应处理～

**Comment by iamlay** [comment]
搜索框是作为UIView的一个子View，并不是控制视图～

**Comment by iamlay** [comment]
但是在iOS13之前的系统确实没有这个黑色的控件

**Comment by tigerAndBull** [comment]
对的，你理解错了，框架只需要一个控制视图，你搜索框也用上了～
然后，初步判断，这个黑色部分，是被框架误认为嵌套视图，然后把你这个部分透明话了～




------------------ Original ------------------
