### ISSUE TITLE
能不能加一个配置，设置自己手动刷新tableview和collectionview

### ISSUE THREAD

**Issue by jolincheng** [tigerAndBull/TABAnimated#58]
我这边请求封装了结束刷新的回调，不管是请求成功还是失败，或者没有网络，都会走这个结束刷新的回调，现在调用了tab_endAnimation,内部就会判断是collectionview，tableview就会调用reloaddata，我现在是想弄一个配置，设置自己手动刷新，然后结束动画我放在我的结束刷新回调，reload我自己放在请求成功的回调

**Comment by tigerAndBull** [comment]
> 我这边请求封装了结束刷新的回调，不管是请求成功还是失败，或者没有网络，都会走这个结束刷新的回调，现在调用了tab_endAnimation,内部就会判断是collectionview，tableview就会调用reloaddata，我现在是想弄一个配置，设置自己手动刷新，然后结束动画我放在我的结束刷新回调，reload我自己放在请求成功的回调

你自己暂时先解决一下，我考虑下个版本加不加～

**Comment by dangyuhua** [comment]
这个需求不错，很多地方都需要用到

**Comment by tigerAndBull** [comment]
> 这个需求不错，很多地方都需要用到

目前你只能源码依赖下，自己加个参数控制了。
也可以给我提pr。

**Comment by dushihao** [comment]
现在这个配置属性已经有了么🙂
