### ISSUE TITLE
通过xib创建cell时, xib中有多个cell会引起崩溃

### ISSUE THREAD

**Issue by Creeeeper** [tigerAndBull/TABAnimated#60]
此问题目前有解决方法吗 有的话烦请告知 谢谢

**Comment by Creeeeper** [comment]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'invalid nib registered for identifier (tab_DBProductCenterCell) - nib must contain exactly one top level object which must be a UITableViewCell instance'

**Comment by Creeeeper** [comment]
<img width="202" alt="WX20191121-184956@2x" src="https://user-images.githubusercontent.com/26081633/69331533-e4ff1380-0c8f-11ea-87a2-891f36c7ecf9.png">

**Comment by tigerAndBull** [comment]
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'invalid nib registered for identifier (tab_DBProductCenterCell) - nib must contain exactly one top level object which must be a UITableViewCell instance'

问题重复，看一下这个issue
https://github.com/tigerAndBull/TABAnimated/issues/54

**Comment by Creeeeper** [comment]
> > ***由于未捕获的异常“ NSInternalInconsistencyException”而终止应用程序，原因：“为标识符注册的无效笔尖（tab_DBProductCenterCell）-笔尖必须仅包含一个顶级对象，该对象必须是UITableViewCell实例”
> 
> 有解决方案，问题重复，看一下这个问题。
> [＃54](https://github.com/tigerAndBull/TABAnimated/issues/54)

并不是重复问题, #54问题并没有在xib中创建多个cell,  所以他的答案不适用于我的问题, 麻烦再次查看, 谢谢

**Comment by tigerAndBull** [comment]
和多cell无关，xib不允许使用多个identitier，是同一问题哈------------------ 原始邮件 ------------------
发件人: "Creeeeper"<notifications@github.com>
发送时间: 2019年11月22日(星期五) 上午9:24
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] 通过xib创建cell时, xib中有多个cell会引起崩溃 (#60)


  
***由于未捕获的异常“ NSInternalInconsistencyException”而终止应用程序，原因：“为标识符注册的无效笔尖（tab_DBProductCenterCell）-笔尖必须仅包含一个顶级对象，该对象必须是UITableViewCell实例”
  
有解决方案，问题重复，看一下这个问题。
 ＃54
  
并不是重复问题, #54问题并没有在xib中创建多个cell,  所以他的答案不适用于我的问题, 麻烦再次查看, 谢谢
 
&mdash;

**Comment by Toothpick2012** [comment]
如果在xib页面中设置了identifier，则必须与代码中的identifier保持一致。否则崩溃，提示：（reason: 'cell reuse indentifier in nib (XXCellX) does not match the identifier used to register the nib (XXCell)'）。
所以不能在使用该库情况下，又在xib中设置identifier，因为TABAnimated会注册tab_XXCell的identifier

**Comment by tigerAndBull** [comment]
是的，需要删除原有id&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: toothpick <notifications@github.com&gt;
发送时间: 2020年11月30日 15:55
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 通过xib创建cell时, xib中有多个cell会引起崩溃 (#60)

**Comment by tigerAndBull** [comment]
已发现xib的子视图宽度和父视图相等的bug，2.5.8已修复。
