### ISSUE TITLE
pod指定版本报错

### ISSUE THREAD

**Issue by HyBLF** [tigerAndBull/TABAnimated#62]
None of your spec sources contain a spec satisfying the dependency: `TABAnimated (= 2.2.1)`.

**Comment by tigerAndBull** [comment]
> None of your spec sources contain a spec satisfying the dependency: `TABAnimated (= 2.2.1)`.

请尝试更新pod，更新索引。可以确定有这个版本。

**Comment by HyBLF** [comment]
谢谢，可以了
