### ISSUE TITLE
你好  在这里崩溃是什么原因

### ISSUE THREAD

**Issue by xuhuaping** [tigerAndBull/TABAnimated#63]
<img width="774" alt="截屏2019-11-29上午9 11 16" src="https://user-images.githubusercontent.com/18001988/69837135-4f174a00-1288-11ea-8dbd-1fb21eb37684.png">

**Comment by tigerAndBull** [comment]
下标溢出，可以通过全局属性debug环境下开始角标提醒。


------------------ 原始邮件 ------------------
发件人: xuhuaping <notifications@github.com&gt;
发送时间: 2019年11月29日 09:12
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 你好  在这里崩溃是什么原因 (#63)

**Comment by xuhuaping** [comment]
> 下标溢出，可以通过分段属性debug环境下开始角标提醒。
> […](#)
> ------------------原始邮件------------------发件人：xuhuaping <notifications@github.com> 发送时间：2019年11月29日09:12收件人：tigerAndBull / TABAnimated <TABAnimated@noreply.github.com> 抄送：已订阅<subscribed@noreply.github.com> 主题：回复：[tigerAndBull / TABAnimated]你好在这里崩溃是什么原因（[＃63](https://github.com/tigerAndBull/TABAnimated/issues/63)）—您收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

不是每次都会崩溃 
<img width="684" alt="截屏2019-12-03上午8 29 54" src="https://user-images.githubusercontent.com/18001988/70006158-17214700-15a7-11ea-92ec-81bbe094768a.png">

**Comment by tigerAndBull** [comment]
确认是否和系统滚动条有关？可以发复现demo给我。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xuhuaping <notifications@github.com&gt;
发送时间: 2019年12月3日 14:28
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 你好  在这里崩溃是什么原因 (#63)



 
下标溢出，可以通过分段属性debug环境下开始角标提醒。
 …
 ------------------原始邮件------------------发件人：xuhuaping notifications@github.com 发送时间：2019年11月29日09:12收件人：tigerAndBull / TABAnimated TABAnimated@noreply.github.com 抄送：已订阅subscribed@noreply.github.com 主题：回复：[tigerAndBull / TABAnimated]你好在这里崩溃是什么原因（＃63）—您收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。
  
不是每次都会崩溃
