### ISSUE TITLE
swift 中如何自定义 adjustBlock 

### ISSUE THREAD

**Issue by YTSmile** [tigerAndBull/TABAnimated#64]
_tableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
    manager.animation(1).down(3).radius(12);
    manager.animation(2).height(12).width(110);
    manager.animation(3).down(-5).height(12);
};
swift 中 manager 找不到这些 animation，down 方法 。。。。请大神指点一下

**Comment by tigerAndBull** [comment]
> _tableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
> manager.animation(1).down(3).radius(12);
> manager.animation(2).height(12).width(110);
> manager.animation(3).down(-5).height(12);
> };
> swift 中 manager 找不到这些 animation，down 方法 。。。。请大神指点一下

tableView.tabAnimated?.adjustBlock = { manager in
        manager.animation()?(1)?.down()(3)?.radius()(12)
        manager.animation()?(2)?.height()(12)?.width()(110)
        manager.animation()?(3)?.down()(-5)?.height()(12)
}

**Comment by Istroot** [comment]
想请教下开发者 Swift 里 animations 怎么用，还有  animationWithIndexs 好像在 Swift 里无法访问...

**Comment by FirstDKS521** [comment]
> 想请教下开发者 Swift 里 animations 怎么用，还有 animationWithIndexs 好像在 Swift 里无法访问...

请问这个是怎么处理的，有什么方法是可以支持的吗
