### ISSUE TITLE
UITableViewCell中如果底部加了一个bottomView，上面的子控件部分不显示

### ISSUE THREAD

**Issue by lumianie** [tigerAndBull/TABAnimated#65]
cell布局如图
![image](https://user-images.githubusercontent.com/15768042/70894674-7875fb00-2028-11ea-8fbf-1fd975c91cd4.png)
现在渲染完成后效果部分UI没显示出来
![11576488442_ pic](https://user-images.githubusercontent.com/15768042/70895234-85471e80-2029-11ea-8ba7-d714e7d7a020.jpg)

**Comment by tigerAndBull** [comment]
先看一下是否用了预处理回调？------------------ 原始邮件 ------------------
发件人: "lumianie"<notifications@github.com>
发送时间: 2019年12月16日(星期一) 下午5:28
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tigerAndBull/TABAnimated] UITableViewCell中如果底部加了一个bottomView，上面的子控件部分不显示 (#65)



cell布局如图
 
 现在渲染完成后效果部分UI没显示出来
 
 
&mdash;

**Comment by lumianie** [comment]
我是用的默认布局方式，没有使用预处理回调
tableView.tabAnimated = TABTableAnimated(cellClass: MineCollectionHospitalCell.self)
tableView.tabAnimated?.animatedSectionCount = 5

**Comment by lumianie** [comment]
bottomView我加了圆角和阴影，项目中凡是这种结构的bottomView内部子控件都只能渲染少部分

**Comment by tigerAndBull** [comment]
提供个demo，我给您看一下------------------ 原始邮件 ------------------
发件人: "lumianie"<notifications@github.com>
发送时间: 2019年12月16日(星期一) 下午5:34
收件人: "tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com>;
抄送: "tigerAndBull"<1429299849@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tigerAndBull/TABAnimated] UITableViewCell中如果底部加了一个bottomView，上面的子控件部分不显示 (#65)



bottomView我加了圆角和阴影，项目中凡是这种结构的bottomView内部子控&#x4EF6;都只能渲染少部分
 
&mdash;

**Comment by lumianie** [comment]
你好，麻烦看一下
[demo.zip](https://github.com/tigerAndBull/TABAnimated/files/3972536/demo.zip)

**Comment by luyun** [comment]
请问下这个问题最后是怎么解决的

**Comment by lumianie** [comment]
> 请问下这个问题最后是怎么解决的

猜测可能是阴影或者圆角影响了，把botomView去掉了就好了
