### ISSUE TITLE
呼吸灯动画在第二次显示时失去动画效果

### ISSUE THREAD

**Issue by devcxm** [tigerAndBull/TABAnimated#67]
首先很感谢作者开源这么好的库，在集成过程中遇到以下问题：

TABViewSuperAnimationTypeBinAnimation第二次显示会失去动画效果，其它类型的动画不会。

附Demo

[TABAnimatedDemo.zip](https://github.com/tigerAndBull/TABAnimated/files/3997476/TABAnimatedDemo.zip)

**Comment by tigerAndBull** [comment]
> 首先很感谢作者开源这么好的库，在集成过程中遇到以下问题：
> 
> TABViewSuperAnimationTypeBinAnimation第二次显示会失去动画效果，其它类型的动画不会。
> 
> 附Demo
> 
> [TABAnimatedDemo.zip](https://github.com/tigerAndBull/TABAnimated/files/3997476/TABAnimatedDemo.zip)

v2.2.6已经修复，请确认～

**Comment by devcxm** [comment]
测试OK没问题
