### ISSUE TITLE
设置颜色没有起作用

### ISSUE THREAD

**Issue by wushengdeluoye** [tigerAndBull/TABAnimated#70]
manager.animation(0).color(bottomColor); 这样设置不生效

**Comment by tigerAndBull** [comment]
先确定下标0是你需要的下标，
不行的话，提供具体场景，最好附上demo。




------------------ Original ------------------

**Comment by wushengdeluoye** [comment]
[TABText.zip](https://github.com/tigerAndBull/TABAnimated/files/4080150/TABText.zip)

上面是demo设置后无效，麻烦帮忙看下吧
        _s_TableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
            UIColor *bottomColor = [UIColor orangeColor];
            manager.animation(0).color(bottomColor);
            manager.animatedBackgroundColor = [UIColor grayColor];
        };

**Comment by wushengdeluoye** [comment]
[TABText.zip](https://github.com/tigerAndBull/TABAnimated/files/4080154/TABText.zip)
 
上面是demo 设置颜色后无效，麻烦帮忙看下吧
        _s_TableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
            UIColor *bottomColor = [UIColor orangeColor];
            manager.animation(0).color(bottomColor);
            manager.animatedBackgroundColor = [UIColor grayColor];
        };

**Comment by tigerAndBull** [comment]
> [TABText.zip](https://github.com/tigerAndBull/TABAnimated/files/4080154/TABText.zip)
> 
> 上面是demo 设置颜色后无效，麻烦帮忙看下吧
> _s_TableView.tabAnimated.adjustBlock = ^(TABComponentManager * _Nonnull manager) {
> UIColor *bottomColor = [UIColor orangeColor];
> manager.animation(0).color(bottomColor);
> manager.animatedBackgroundColor = [UIColor grayColor];
> };

这个问题，是因为0被加入了闪光灯的动画组，你的意思是0作为背景，可以调别的颜色是吧？

**Comment by wushengdeluoye** [comment]
对是的，想让0作为背景，调成别的颜色

**Comment by tigerAndBull** [comment]
> 对是的，想让0作为背景，调成别的颜色

你手头的版本只能将0 remove一下了，但是0就不会展示了。
原则上可以将0的闪光灯移除，然后就可以改颜色了，
但是这个版本没有这个api，需要改动源码。

**Comment by wushengdeluoye** [comment]
好的，多谢解答！

**Comment by tigerAndBull** [comment]
该问题解决方案：调整闪光灯动画的亮度和变色值
