### ISSUE TITLE
瀑布流 UICollectionView 不能显示出来

### ISSUE THREAD

**Issue by mafaming** [tigerAndBull/TABAnimated#71]
1、瀑布流 UICollectionView 不能显示出来
2、非瀑布流 UICollectionView 可以正常显示
3、不能把公司项目代码共享，所以创建了个demo ，麻烦帮看下为什么不能正常显示，非常感谢.

[testDemo](https://github.com/mafaming/TABAnimatedDemo.git)

**Comment by tigerAndBull** [comment]
AOP切向的原UICollectionViewFlowLayout的代理方法，您项目中瀑布流使用的是私有代理方法，即切入的方法不一致，所以没有效果。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mafaming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 下午3:44
收件人:&nbsp;"tigerAndBull/TABAnimated"<TABAnimated@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tigerAndBull/TABAnimated] 瀑布流 UICollectionView 不能显示出来 (#71)




1、瀑布流 UICollectionView 不能显示出来
 2、非瀑布流 UICollectionView 可以正常显示
 3、不能把公司项目代码共享，所以创建了个demo ，麻烦帮看下为什么不能正常显示，非常感谢.
 
testDemo

**Comment by mafaming** [comment]
收到，谢谢，我想想其他办法处理

**Comment by Limghi** [comment]
解决了吗？

**Comment by weizhangCoder** [comment]
有没有瀑布流的解决办法

**Comment by tigerAndBull** [comment]
这是新的瀑布流方案，还未发布，你可以看一下这个demo，能满足预期不
[TABAnimatedDemo-master.zip](https://github.com/tigerAndBull/TABAnimated/files/5727780/TABAnimatedDemo-master.zip)

@mafaming @Limghi @weizhangCoder

**Comment by tigerAndBull** [comment]
2.5.1已支持
