### ISSUE TITLE
求个思路

### ISSUE THREAD

**Issue by GrapeFruitJun** [tigerAndBull/TABAnimated#73]
无序路径,做路径动画,怎么保证动画层方向跟随路径方向,求大神能提供思路,有点类似滴滴上地图上的小汽车,直角和弧度路径怎么处理,求思路

**Comment by tigerAndBull** [comment]
> 无序路径,做路径动画,怎么保证动画层方向跟随路径方向,求大神能提供思路,有点类似滴滴上地图上的小汽车,直角和弧度路径怎么处理,求思路

keyPath为position，同时根据你目标路径设置为CAKeyframeAnimation的path即可。不知道是不是我理解你的需求有误？

**Comment by GrapeFruitJun** [comment]
谢谢，刚找到了 CAKeyframeAnimation的属性rotationMode可以处理




    


在2020年02月21日 00:32，tigerAndBull 写道： 
无序路径,做路径动画,怎么保证动画层方向跟随路径方向,求大神能提供思路,有点类似滴滴上地图上的小汽车,直角和弧度路径怎么处理,求思路

keyPath为position，同时根据你目标路径设置为CAKeyframeAnimation的path即可。不知道是不是我理解你的需求有误？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tigerAndBull/TABAnimated/issues/73?email_source=notifications\u0026email_token=AD47HBEI3JBANCX4XAWCXJLRD2WDTA5CNFSM4KYSBUZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMPAJMI#issuecomment-589169841",
"url": "https://github.com/tigerAndBull/TABAnimated/issues/73?email_source=notifications\u0026email_token=AD47HBEI3JBANCX4XAWCXJLRD2WDTA5CNFSM4KYSBUZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMPAJMI#issuecomment-589169841",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
