### ISSUE TITLE
大佬，uitableview numberOfSectionsInTableView>1,只显示第一个section，咋回事呢？

### ISSUE THREAD

**Issue by ieliwb** [tigerAndBull/TABAnimated#74]
TABAnimated全局性的？部分控制器tableview不使用怎么设置呢？谢谢

**Comment by ieliwb** [comment]
我看demo可以，是不是不能继承UITableViewController，tableView自己生成？

**Comment by tigerAndBull** [comment]
1. 只显示第一个section，与你使用的正确性有关
2. 它的配置信息是全局性的，不影响不使用的UITableView
3. 不能，控制视图只能是UIView及其子类
