### ISSUE TITLE
在UItableviewcell中添加一个view，，然后view中的subview就没办法显示

### ISSUE THREAD

**Issue by luyun** [tigerAndBull/TABAnimated#76]
在UItableviewcell中添加一个view，，然后view中的subview就没办法显示

**Comment by luyun** [comment]
![Simulator Screen Shot - iPhone 8 - 2020-03-16 at 11 17 02](https://user-images.githubusercontent.com/2156081/76720854-fa390a00-6778-11ea-9af4-91b1f61e9236.png)

**Comment by tigerAndBull** [comment]
开启角标，找到view的index，将其通过异步回调移除即可

**Comment by luyun** [comment]
移除后就不显示了，我需要他正常的显示出来，有什么方法吗？

**Comment by tigerAndBull** [comment]
移除了还要显示，请明确你的需求，再来提问。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luyun <notifications@github.com&gt;
发送时间: 2020年4月10日 13:39
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 在UItableviewcell中添加一个view，，然后view中的subview就没办法显示 (#76)





 
移除后就不显示了，我需要他正常的显示出来，有什么方法吗？

**Comment by luyun** [comment]
我需要的是显示，但是显示出来就会出现上面图片的问题，，给您提问，您给的答案是移除

**Comment by tigerAndBull** [comment]
你可能理解有问题，我有时间看下


------------------ 原始邮件 ------------------
发件人: luyun <notifications@github.com&gt;
发送时间: 2020年4月13日 13:03
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 在UItableviewcell中添加一个view，，然后view中的subview就没办法显示 (#76)





 
我需要的是显示，但是显示出来就会出现上面图片的问题，，给您提问，您给的答案是移除

**Comment by luyun** [comment]
好的，谢谢
