### ISSUE TITLE
cell中增加view ，view中的subview显示错误

### ISSUE THREAD

**Issue by luyun** [tigerAndBull/TABAnimated#78]
请问现在是不支持cell中增加uiview的显示方式吗

**Comment by tigerAndBull** [comment]
支持




------------------ 原始邮件 ------------------
发件人: luyun <notifications@github.com&gt;
发送时间: 2020年4月10日 16:17
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] cell中增加view ，view中的subview显示错误 (#78)





 
请问现在是不支持cell中增加uiview的显示方式吗

**Comment by luyun** [comment]
目前看到的还是乱的，如果单纯的删除view，那么cell中样式又会不对

**Comment by tigerAndBull** [comment]
> 目前看到的还是乱的，如果单纯的删除view，那么cell中样式又会不对

使用有误，请阅读文档

**Comment by luyun** [comment]
[SkeletonViewDemo.zip](https://github.com/tigerAndBull/TABAnimated/files/4467856/SkeletonViewDemo.zip)
能帮忙看看为什么cell中添加了view，，view上的subview全部不显示吗？

**Comment by tigerAndBull** [comment]
`tableview.tabAnimated?.adjustBlock = { manager in
            manager.animation()?(0)?.remove()()
            manager.animation()?(3)?.remove()()
        }`
卡片视图参考demo

**Comment by 1knight520** [comment]
![image](https://user-images.githubusercontent.com/23653418/190099998-f462b2b7-561f-42d9-a881-e35390619004.png)
![image](https://user-images.githubusercontent.com/23653418/190100073-8e34a28a-54cd-4cf1-9f02-c9032ebb153d.png)
为啥cell里面自定义的底部bgView 骨架屏的时候不显示0  反而typeImageV才是0

**Comment by tigerAndBull** [comment]
> ![image](https://user-images.githubusercontent.com/23653418/190099998-f462b2b7-561f-42d9-a881-e35390619004.png) ![image](https://user-images.githubusercontent.com/23653418/190100073-8e34a28a-54cd-4cf1-9f02-c9032ebb153d.png) 为啥cell里面自定义的底部bgView 骨架屏的时候不显示0 反而typeImageV才是0

animation(@"bgView").height(x).color(UIColor.redColor);
试下有对应元素吗

**Comment by 1knight520** [comment]
> 
![image](https://user-images.githubusercontent.com/23653418/190105734-73b1c1c0-97a5-49a1-be2b-4c34ae8abfe3.png)
![image](https://user-images.githubusercontent.com/23653418/190105898-340e0b2a-5a02-4edd-8167-aeb32b3ffca0.png)
貌似没找到 但是有一个模块的cell也是这样的布局  里面的自定义bgview骨架屏却可以显示 我特意看了 写法好像是一样 一脸懵 哭了😭

**Comment by tigerAndBull** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/23653418/190105734-73b1c1c0-97a5-49a1-be2b-4c34ae8abfe3.png) ![image](https://user-images.githubusercontent.com/23653418/190105898-340e0b2a-5a02-4edd-8167-aeb32b3ffca0.png) 貌似没找到 但是有一个模块的cell也是这样的布局 里面的自定义bgview骨架屏却可以显示 我特意看了 写法好像是一样 一脸懵 哭了😭

能提供复现demo吗

**Comment by 1knight520** [comment]
不好搞复现demo[破涕为笑]  我再试试 如果后面不行 再搞demo麻烦你 谢谢了
