### ISSUE TITLE
大佬，间歇性出现一排排 testtesttesttesttesttesttesttest是什么情况呢？

### ISSUE THREAD

**Issue by ieliwb** [tigerAndBull/TABAnimated#79]
RT，谢谢

**Comment by tigerAndBull** [comment]
提供给我具体场景



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ieliwb <notifications@github.com&gt;
发送时间: 2020年4月10日 18:23
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 大佬，间歇性出现一排排 testtesttesttesttesttesttesttest是什么情况呢？ (#79)





 
RT，谢谢

**Comment by ieliwb** [comment]
AppDelegate里面:
    [[TABAnimated sharedAnimated] initWithShimmerAnimated];



    self.tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[ItemByStandardCell class] cellHeight:157];
    [self.tableView tab_startAnimation];

就这样调用的，出现的概率太频繁了，不是每次必现的

**Comment by tigerAndBull** [comment]
不能作为依据。


------------------ 原始邮件 ------------------
发件人: ieliwb <notifications@github.com&gt;
发送时间: 2020年4月16日 23:50
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 大佬，间歇性出现一排排 testtesttesttesttesttesttesttest是什么情况呢？ (#79)





 
AppDelegate里面:
 [[TABAnimated sharedAnimated] initWithShimmerAnimated];
 self.tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[ItemByStandardCell class] cellHeight:157]; [self.tableView tab_startAnimation];  
就这样调用的，出现的概率太频繁了，不是每次必现的

**Comment by tigerAndBull** [comment]
> AppDelegate里面:
> [[TABAnimated sharedAnimated] initWithShimmerAnimated];
> 
> ```
> self.tableView.tabAnimated = [TABTableAnimated animatedWithCellClass:[ItemByStandardCell class] cellHeight:157];
> [self.tableView tab_startAnimation];
> ```
> 
> 就这样调用的，出现的概率太频繁了，不是每次必现的

v2.2.6已经修复，请确认～

**Comment by tigerAndBull** [comment]
v2.3.0已发布，请确认是否还存在问题
