### ISSUE TITLE
Using TABAdjustBlock  in swift

### ISSUE THREAD

**Issue by marcojusto** [tigerAndBull/TABAnimated#80]
Hey, first of all congratulations on such a well put and complete library. I'm having an issue adapting this library to my current project in swift. Mainly with the translation below:

Current objc code
```
- (TABAdjustBlock) animationsForCell
{
    return ^(TABComponentManager * manager) {
        dispatch_async(dispatch_get_main_queue(), ^{
            manager.animation(0).remove();
            manager.animation(1).remove();
            manager.animation(2).width(110).toLongAnimation();
            manager.animation(4).remove();
            manager.animation(3).down(-5).height(12);
            manager.animation(5).down(3).toLongAnimation();
        });
    };
}
```
Desired swift translation

```
    func animationForEventCell() -> TABAdjustBlock {
        let block: TABAdjustBlock = { manager in
            manager.animation() // can't set it, doesn't allow params
       }
        return block
    }

```

Any pointers, or any help you can give me regarding this particular piece? thanks!

**Comment by tigerAndBull** [comment]
> Hey, first of all congratulations on such a well put and complete library. I'm having an issue adapting this library to my current project in swift. Mainly with the translation below:
> 
> Current objc code
> 
> ```
> - (TABAdjustBlock) animationsForCell
> {
>     return ^(TABComponentManager * manager) {
>         dispatch_async(dispatch_get_main_queue(), ^{
>             manager.animation(0).remove();
>             manager.animation(1).remove();
>             manager.animation(2).width(110).toLongAnimation();
>             manager.animation(4).remove();
>             manager.animation(3).down(-5).height(12);
>             manager.animation(5).down(3).toLongAnimation();
>         });
>     };
> }
> ```
> 
> Desired swift translation
> 
> ```
>     func animationForEventCell() -> TABAdjustBlock {
>         let block: TABAdjustBlock = { manager in
>             manager.animation() // can't set it, doesn't allow params
>        }
>         return block
>     }
> ```
> 
> Any pointers, or any help you can give me regarding this particular piece? thanks!

See #64 .

**Comment by marcojusto** [comment]
thanks a lot! ✌️
