### ISSUE TITLE
openAnimationTag的tag是根据什么排序的？

### ISSUE THREAD

**Issue by fuchenxi** [tigerAndBull/TABAnimated#81]

**Comment by tigerAndBull** [comment]
[动画元素下标问题](https://github.com/tigerAndBull/TABAnimated/blob/master/Documents/%E5%8A%A8%E7%94%BB%E5%85%83%E7%B4%A0%E4%B8%8B%E6%A0%87%E9%97%AE%E9%A2%98.md)
