### ISSUE TITLE
关于自定义动画下标Tag的想法

### ISSUE THREAD

**Issue by devcxm** [tigerAndBull/TABAnimated#82]
关于动画下标的问题，可不可以给UIView添加一个关联属性（如`tab_animationTag`）让开发者自定义Tag，因为如果是通过调试查看Tag会有两个问题：1、修改UI层级后原有Tag操作完全错乱了；2、我的Cell子视图在不同系统出现了下标不一致的问题，如下图

iOS 10.3(左iPhone 5s) 和 iOS 13.4(右iPhone 11)
![2020-04-26 10 38 20](https://user-images.githubusercontent.com/8568955/80296216-9d833300-87ab-11ea-8495-cf0cd434d5c8.gif)

**Comment by tigerAndBull** [comment]
> 关于动画下标的问题，可不可以给UIView添加一个关联属性（如`tab_animationTag`）让开发者自定义Tag，因为如果是通过调试查看Tag会有两个问题：1、修改UI层级后原有Tag操作完全错乱了；2、我的Cell子视图在不同系统出现了下标不一致的问题，如下图
> 
> iOS 10.3(左iPhone 5s) 和 iOS 13.4(右iPhone 11)
> ![2020-04-26 10 38 20](https://user-images.githubusercontent.com/8568955/80296216-9d833300-87ab-11ea-8495-cf0cd434d5c8.gif)

不同系统不一致我暂且认定为一种bug，你可以提供具体代码，做修复。

**Comment by tigerAndBull** [comment]
把你的上一个issue #67 ，现版本的结果反馈给我，已经修复了你就可以把它关闭。

**Comment by devcxm** [comment]
我知道这是一个bug，但是如果可以让开发者自定义Tag的话，这个bug就可以很轻松的避开了。具体代码我有时间的时候新建一个Demo工程看能不能复现，另外，我更倾向于自定义Tag的实现方法，开发者自定义Tag，TABAnimated去获取自定义Tag。

**Comment by tigerAndBull** [comment]
> 我知道这是一个bug，但是如果可以让开发者自定义Tag的话，这个bug就可以很轻松的避开了。具体代码我有时间的时候新建一个Demo工程看能不能复现，另外，我更倾向于自定义Tag的实现方法，开发者自定义Tag，TABAnimated去获取自定义Tag。

可以开放相关接口，但它的优先级会比较低，因为我在进行一次重构。

**Comment by tigerAndBull** [comment]
> > 我知道这是一个bug，但是如果可以让开发者自定义Tag的话，这个bug就可以很轻松的避开了。具体代码我有时间的时候新建一个Demo工程看能不能复现，另外，我更倾向于自定义Tag的实现方法，开发者自定义Tag，TABAnimated去获取自定义Tag。
> 
> 可以开放相关接口，但它的优先级会比较低，因为我在进行一次重构。

关于这个版本不一致的问题，你可以具体提供demo给我，下一个修复版本会首先处理这个问题。

**Comment by devcxm** [comment]
@tigerAndBull 

我知道什么情况下会出现下标出错的问题，给TableVieCell设置右箭头`self.accessoryType = UITableViewCellAccessoryDisclosureIndicator;`后，`accessoryView`在不同系统的下标就会不一致。

我测试的模拟器：iPhone 5s(10.3.1) 和 iPhone 11(13.4)

[TABAnimatedDemo#82.zip](https://github.com/tigerAndBull/TABAnimated/files/4534749/TABAnimatedDemo.82.zip)

**Comment by devcxm** [comment]
新Demo中的TableViewCell使用自动布局，所以在iOS 10和iOS 11动画骨架、右箭头大小位置跟实际相差比较大，因此在项目中我想通过下标移除右剪头的动画
```
manager.animation(5).remove();
```

**Comment by tigerAndBull** [comment]
@devcxm

**Comment by tigerAndBull** [comment]
这个问题现在有解决方案了，
提供了新的接口animationN(x), 可以通过变量名获取元素。

**Comment by devcxm** [comment]
转flutter了😂
