### ISSUE TITLE
当切换显示样式时 样式还是保留之前的样式

### ISSUE THREAD

**Issue by YYDreams** [tigerAndBull/TABAnimated#83]
![图片](https://user-images.githubusercontent.com/15007334/81521790-d65e0300-937a-11ea-89b4-d0963dd655d0.png)

**Comment by tigerAndBull** [comment]
@YYDreams 
按照你的场景，需要在初始化方法里绑定不同的cell（图中红框代码）

![image](https://user-images.githubusercontent.com/28705454/81522415-1b833480-937d-11ea-9404-0e4f40460d61.png)

**Comment by YYDreams** [comment]
是同一个cell啊

**Comment by YYDreams** [comment]
在154行的时候 你看看图片

**Comment by tigerAndBull** [comment]
> 是同一个cell啊

是的，但是你没有在初始化方法里对视图的逻辑进行区分，你在这个地方进行逻辑区分是无效的。

**Comment by tigerAndBull** [comment]
@YYDreams 
你必须保证self.viewModel.isGrid生效的同时，cell里的视图也跟随变化，这样才会展示不同的内容。

**Comment by YYDreams** [comment]
我觉得没问题啊 就是这个判断的吖  每次加载中的时候 判断吖 
![图片](https://user-images.githubusercontent.com/15007334/81555783-bf8bd080-93bb-11ea-984d-27a258853589.png)

**Comment by tigerAndBull** [comment]
@YYDreams 
你可以打个断点看一下，是否走到这里了，正常情况下，不会出现显示不出来的情况。
框架在这个地方没有特殊的逻辑判断。

**Comment by YYDreams** [comment]
走了吖 你可以看第一张图啊 我打了个断点在那里 但是却显示上面160行的样式

**Comment by tigerAndBull** [comment]
173走没走



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: flower <notifications@github.com&gt;
发送时间: 2020年5月11日 19:20
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 当切换显示样式时 样式还是保留之前的样式 (#83)





 
走了吖 你可以看第一张图啊 我打了个断点在那里 但是却显示上面160行的样式

**Comment by YYDreams** [comment]
173里面没走 为嘛里面的block不会走呢

**Comment by tigerAndBull** [comment]
self.viewModel.isGird


------------------ 原始邮件 ------------------
发件人: flower <notifications@github.com&gt;
发送时间: 2020年5月12日 09:41
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 当切换显示样式时 样式还是保留之前的样式 (#83)





 
173里面没走 为嘛里面的block不会走呢

**Comment by tigerAndBull** [comment]
@YYDreams 
如果你还有问题需要提供更多信息，如果解决了就关闭issue。
