### ISSUE TITLE
RXSwift,取消AOP的版本哪里可以参与测试？

### ISSUE THREAD

**Issue by Marcusias** [tigerAndBull/TABAnimated#85]
使用了 #40  中的FullScreenDemo， collectionview 依旧有问题 ，尝试修改TABCollectionAnimated 目前还没处理好

**Comment by tigerAndBull** [comment]
带有AOP版本的正在进行新一轮优化，所以最近么有时间。
去掉AOP，部分场景是没有办法实现的，所以就需要另起炉灶，不过只需要修改AOP部分。

**Comment by tigerAndBull** [comment]
v2.5.2已适配第三方库，如QMUI，RxSwift.

**Comment by Marcusias** [comment]
> v2.5.2已适配第三方库，如QMUI，RxSwift.

使用2.5.4  依旧不行
demo 见：
https://github.com/tigerAndBull/TABAnimated/issues/40#issuecomment-824717431
