### ISSUE TITLE
默认的伸缩动画为啥没了？demo里也是没有，文档上有个class动画但是也没有效果

### ISSUE THREAD

**Issue by gongxinle** [tigerAndBull/TABAnimated#88]
RT。

**Comment by tigerAndBull** [comment]
> RT。

demo有的，不过四种动画进行了拆分，不可混用，混用无效。

**Comment by tigerAndBull** [comment]
新版本2.3.0做了处理。

**Comment by gongxinle** [comment]
ok 那我再看下 谢啦~

**Comment by gongxinle** [comment]
// 骨架层
    TABAnimationTypeOnlySkeleton = 0,
    
    // 骨架层 + 呼吸灯动画
    TABAnimationTypeBinAnimation,
    
    // 骨架层 + 闪光灯
    TABAnimationTypeShimmer,
    
    // 骨架层 + 豆瓣下坠动画
    TABAnimationTypeDrop,
    
    // 骨架层 + 自定义动画
    TABAnimationTypeCustom
你说的是这几种吗？我昨天下载的版本 在demo里点了所有的页面 都没有伸缩动画

**Comment by tigerAndBull** [comment]
TABAnimationTypeOnlySkeleton就是带有伸缩动画的

**Comment by gongxinle** [comment]
我用的11.5的xcode 系统是最新的。我测试的但section单cell 不带tableHeaderView那个视图 特意用了延迟加载的那个api 延迟4秒 但是真的没有动画呀

**Comment by tigerAndBull** [comment]
后面没有加()吧，toLongAnimation()

**Comment by gongxinle** [comment]
toLongAnimation()这个还需要手动调用吗？我用demo跑一遍也是没有动画的，或者你用demo跑一遍试试？

**Comment by tigerAndBull** [comment]
？描述清除，或者你附上demo，我这边没有任何问题

**Comment by tigerAndBull** [comment]
不需要手动调用，怎么来的动画？

**Comment by gongxinle** [comment]
尴尬了啊  我还以为是自动的，原来还需要在adjustBlock里面去调用 感谢感谢~
