### ISSUE TITLE
在ios9.3.3系统上第二次启动APP会崩溃

### ISSUE THREAD

**Issue by npzlxph0415** [tigerAndBull/TABAnimated#90]
-[__NSCFString new]: unrecognized selector sent to instance 0x14809a470
(null)
((
    0 CoreFoundation 0x0000000183e1adc8 <redacted> + 148
    1 libobjc.A.dylib 0x000000018347ff80 objc_exception_throw + 56
    2 Foundation 0x0000000184794704 <redacted> + 0
    3 Foundation 0x00000001847948bc <redacted> + 440
    4 Foundation 0x00000001847633b8 <redacted> + 2996
    5 Foundation 0x000000018476274c <redacted> + 304
    6 Foundation 0x00000001847c4918 <redacted> + 160
    7 winekar24th 0x0000000100459608 +[TABAnimatedDocumentMethod getCacheData:targetClass:] + 256
    8 winekar24th 0x000000010033a460 -[TABAnimatedCacheManager _loadDataToMemory:] + 1708
    9 Foundation 0x00000001847f002c <redacted> + 340
    10 CoreFoundation 0x0000000183dd109c <redacted> + 24
    11 CoreFoundation 0x0000000183dd0b30 <redacted> + 540
    12 CoreFoundation 0x0000000183dce830 <redacted> + 724
    13 CoreFoundation 0x0000000183cf8c50 CFRunLoopRunSpecific + 384
    14 Foundation 0x0000000184708cfc <redacted> + 308
    15 Foundation 0x000000018475e030 <redacted> + 88
    16 winekar24th 0x00000001003384e4 +[TABAnimatedCacheManager updateThreadMain:] + 328
    17 Foundation 0x00000001847efe4c <redacted> + 1000
    18 libsystem_pthread.dylib 0x0000000183a7fb28 <redacted> + 156
    19 libsystem_pthread.dylib 0x0000000183a7fa8c <redacted> + 0
    20 libsystem_pthread.dylib 0x0000000183a7d028 thread_start + 4
)

**Comment by tigerAndBull** [comment]
这是2.3.0更新后出现的问题，请尽快升级成2.4.0

**Comment by tigerAndBull** [comment]
升级后记得反馈最新进展。

**Comment by npzlxph0415** [comment]
升级后ok了
