### ISSUE TITLE
Firebase 统计上的崩溃比较多，怎么优化下？

### ISSUE THREAD

**Issue by mafaming** [tigerAndBull/TABAnimated#92]
![image](https://user-images.githubusercontent.com/11641379/85943737-8526c480-b964-11ea-9168-7ef5787f07d0.png)

**Comment by tigerAndBull** [comment]
用最新版本，这是iOS 10.0的安全性问题。

**Comment by mafaming** [comment]
![image](https://user-images.githubusercontent.com/11641379/85945276-45190f00-b96f-11ea-8d44-683f85debc40.png)
![image](https://user-images.githubusercontent.com/11641379/85945328-9e813e00-b96f-11ea-86e9-f6622212ee26.png)

App 5.1.2 版本就是用的2.3.0，但是还是有崩溃。

**Comment by tigerAndBull** [comment]
用2.4.x



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mafaming <notifications@github.com&gt;
发送时间: 2020年6月28日 18:46
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] Firebase 统计上的崩溃比较多，怎么优化下？ (#92)





 

 
 
App 5.1.2 版本就是用的2.3.0，但是还是有崩溃。

**Comment by mafaming** [comment]
好的，我再更新下，印象中是上周才更新的2.3.0   😆

**Comment by tigerAndBull** [comment]
就因为这个问题，赶紧更新了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mafaming <notifications@github.com&gt;
发送时间: 2020年6月28日 18:53
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] Firebase 统计上的崩溃比较多，怎么优化下？ (#92)





 
好的，我再更新下，印象中是上周才更新的2.3.0   😆

**Comment by mafaming** [comment]
![image](https://user-images.githubusercontent.com/11641379/87133663-39600d80-c2ca-11ea-9409-92d2d97dadf4.png)

使用2.4.2 版本上线一段时间，看统计还有一些崩溃，能查下吗？

**Comment by tigerAndBull** [comment]
是没升级吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mafaming <notifications@github.com&gt;
发送时间: 2020年7月10日 16:28
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] Firebase 统计上的崩溃比较多，怎么优化下？ (#92)





 

 
使用2.4.2 版本上线一段时间，看统计还有一些崩溃，能查下吗？

**Comment by mafaming** [comment]
你说的升级指的是什么？

**Comment by tigerAndBull** [comment]
> 你说的升级指的是什么？

你提供更具体的Log我看看

**Comment by mafaming** [comment]
我不知道怎么找更具体的日志 ， 只有这些Firebase 统计上的

Crashed: com.tigerAndBull.TABAnimated.updateThread
0  libobjc.A.dylib                0x1957bbc68 objc_retain + 8
1  MojiPop                        0x100bb4ac0 -[TABAnimatedCacheManager _loadDataToMemory:] + 259 (TABAnimatedCacheManager.m:259)
2  Foundation                     0x195e84d6c __NSThreadPerformPerform + 188
3  CoreFoundation                 0x195a07af4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
4  CoreFoundation                 0x195a07a48 __CFRunLoopDoSource0 + 84
5  CoreFoundation                 0x195a07198 __CFRunLoopDoSources0 + 196
6  CoreFoundation                 0x195a01f38 __CFRunLoopRun + 796
7  CoreFoundation                 0x195a018f4 CFRunLoopRunSpecific + 480
8  Foundation                     0x195d4ab18 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
9  Foundation                     0x195d859ec -[NSRunLoop(NSRunLoop) run] + 92
10 MojiPop                        0x100bb3620 +[TABAnimatedCacheManager updateThreadMain:] + 66 (TABAnimatedCacheManager.m:66)
11 Foundation                     0x195e84c10 __NSThread__start__ + 864
12 libsystem_pthread.dylib        0x1957918fc _pthread_start + 168
13 libsystem_pthread.dylib        0x1957999d4 thread_start + 8

![image](https://user-images.githubusercontent.com/11641379/87141850-471b9000-c2d6-11ea-8f04-75728e05ed52.png)

**Comment by guo846773272** [comment]
> ![image](https://user-images.githubusercontent.com/11641379/87133663-39600d80-c2ca-11ea-9409-92d2d97dadf4.png)
> 
> 使用2.4.2 版本上线一段时间，看统计还有一些崩溃，能查下吗？

这个问题怎么解决的呢，大佬，求助。我在firebase碰到了同样的问题

**Comment by tigerAndBull** [comment]
> > ![image](https://user-images.githubusercontent.com/11641379/87133663-39600d80-c2ca-11ea-9409-92d2d97dadf4.png)
> > 使用2.4.2 版本上线一段时间，看统计还有一些崩溃，能查下吗？
> 
> 这个问题怎么解决的呢，大佬，求助。我在firebase碰到了同样的问题

关闭缓存，并且升级到最新

**Comment by tigerAndBull** [comment]
你升级过吗？升级后的用户还存在问题？

**Comment by guo846773272** [comment]
> 你升级过吗？升级后的用户还存在问题？

目前在2.4.5版本，还没有升级，大佬说的关闭缓存可以详细点吗，，，

**Comment by tigerAndBull** [comment]
你先说清楚，你是从哪个版本升级到哪个版本，仍存在崩溃问题

**Comment by tigerAndBull** [comment]
你先确定一下，这些崩溃的用户，有没有升级你们app的新版本

**Comment by guo846773272** [comment]
> 你先说清楚，你是从哪个版本升级到哪个版本，仍存在崩溃问题

此次发现崩溃的版本是2.4.5，之前也有崩溃，但是不能确定版本是多少啦、

**Comment by tigerAndBull** [comment]
是这样的，如果用户不升级app，就还会崩溃。
你看数量有所减少吗？

**Comment by guo846773272** [comment]
> 是这样的，如果用户不升级app，就还会崩溃。
> 你看数量有所减少吗？

大佬，我的APP使用的骨架屏的版本是2.4.5，现在有crash存在，我应该怎么解决呐，升级到2.5.0在调用一下清理缓存的closeCache方法吗？

**Comment by tigerAndBull** [comment]
你现在自己手机里的，还是会crash吗？

**Comment by tigerAndBull** [comment]
> > 是这样的，如果用户不升级app，就还会崩溃。
> > 你看数量有所减少吗？
> 
> 大佬，我的APP使用的骨架屏的版本是2.4.5，现在有crash存在，我应该怎么解决呐，升级到2.5.0在调用一下清理缓存的closeCache方法吗？

如果2.4.5还有，升到2.5.0也不会解决

**Comment by tigerAndBull** [comment]
可以加我微信，配合你查一下这个问题

**Comment by guo846773272** [comment]
> 可以加我微信，配合你查一下这个问题

么有找到大佬的微信，这个是我的微信 130-2751-6166

**Comment by tigerAndBull** [comment]
readme

**Comment by tigerAndBull** [comment]
这个是说TABAnimated开启的线程在 mach_msg_trap暂停中，并不是崩溃。
你需要查看具体崩溃的地方，和TABAnimated无关。
```
 com.tigerAndBull.TABAnimated.updateThread
0  libsystem_kernel.dylib         0x2215a8d0 mach_msg_trap + 20
1  libsystem_kernel.dylib         0x2215a6d5 mach_msg + 40
2  CoreFoundation                 0x224a5ac5 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x224a3e4d __CFRunLoopRun + 1036
4  CoreFoundation                 0x223f3229 CFRunLoopRunSpecific + 520
5  CoreFoundation                 0x223f3015 CFRunLoopRunInMode + 108
6  Foundation                     0x22c3c045 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 268
7  Foundation                     0x22c8aa4d -[NSRunLoop(NSRunLoop) run] + 80
8  banggood                       0x4d0ad9 +[TABAnimatedCacheManager updateThreadMain:] + 74 (TABAnimatedCacheManager.m:74)
9  Foundation                     0x22d0d4a5 __NSThread__start__ + 1148
10 libsystem_pthread.dylib        0x2221785b _pthread_body + 138
11 libsystem_pthread.dylib        0x222177cf _pthread_start + 110
12 libsystem_pthread.dylib        0x22215724 thread_start + 8
```
