### ISSUE TITLE
用户出现崩溃问题

### ISSUE THREAD

**Issue by jiangyanshuang** [tigerAndBull/TABAnimated#93]
- TABAnimated (2.2.6):
    - TABAnimated/Core (= 2.2.6)
    - TABAnimated/Reveal (= 2.2.6)
  - TABAnimated/Core (2.2.6)
  - TABAnimated/Reveal (2.2.6):
    - TABAnimated/Core

*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (TABAnimatedProduction) for key (root); the class may be defined in source code or a library that is not linked (null)

iPhone 7  ios 10.3.2
iPhone 6  ios 9.1

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | iOS 9.1、iOS 10.3.2
 TABAnimated Version      | 2.2.6
 Xcode Version           | Xcode 11.4
 Repro rate              | 影响用户10人  累计崩溃次数174次
 Repro with our demo prj | no
 Demo project link       | https://apps.apple.com/cn/app/%E7%9C%81%E7%8C%AB%E9%97%AA%E5%BA%97/id1458314243

### Issue Description and Steps

*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (TABAnimatedProduction) for key (root); the class may be defined in source code or a library that is not linked (null)

**Comment by tigerAndBull** [comment]
#92 请看这个issue
