### ISSUE TITLE
卡片式的在TableView用，如何设置呢

### ISSUE THREAD

**Issue by deepindo** [tigerAndBull/TABAnimated#95]
卡片式的在TableView用，如何设置呢，下载当前的demo里面只有collectionView才有，且动画和readme中不太一样。

**Comment by tigerAndBull** [comment]
> 卡片式的在TableView用，如何设置呢，下载当前的demo里面只有collectionView才有，且动画和readme中不太一样。

不需要设置，会自动识别，demo中UITableView和UICollectionView的卡片式都有

**Comment by tigerAndBull** [comment]
> 卡片式的在TableView用，如何设置呢，下载当前的demo里面只有collectionView才有，且动画和readme中不太一样。

可以把你卡片布局方式提供一下。
