### ISSUE TITLE
Xcode 12 beta 

### ISSUE THREAD

**Issue by laurivers** [tigerAndBull/TABAnimated#96]
### New Issue Checklist

* 

- [x] I have read the [Documentation](https://github.com/tigerAndBull/TABAnimated/tree/master/Documents)

* [x] I have searched for a similar issue in the [project](https://github.com/rs/TABAnimated/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 TABAnimated Version     2.4.5
 Xcode Version          Xcode 12 beta (1, 2, 3)
 Repro rate             100%
 Repro with our demo prj  yes

### Issue Description and Steps

使用 Xcode 12  beta (1, 2, 3) 均出现的问题. 
[TABTableAnimated animatedWithCellClass:CustomCell.class cellHeight:80];
~~此处指定的 cell height 未成功设置,导致 custom cell 中的 view 等可能会在骨架图时位置显示不正确. 最常见的就是超出 cell 范围.~~
重新用 Xcode 11.5 和 Xcode 12.0 运行了 demo 对比发现, 不是 cell 高度的问题,而是 cell 的背景出现了灰色(不确定是 cell.self 还是 cell.contentView).

下图为 demo 中的 “单section多cell 指定 row 配置动画” 在不同 Xcode 运行后的截图对比.

Xcode 11.5
![Xcode 11 5](https://user-images.githubusercontent.com/861317/88358037-06c11500-cda0-11ea-9318-42eb734c75ad.png)

Xcode 12.0 
![Xcode 12](https://user-images.githubusercontent.com/861317/88358045-0de82300-cda0-11ea-96f5-49b536b09a6f.png)

**Comment by tigerAndBull** [comment]
高度未成功设置？那么最上层盖住的灰色是什么？是你的自定义视图view生成的吗？

**Comment by laurivers** [comment]
这个是 demo 在 Xcode 12.0 上运行的效果,可以看出来左侧的圆形 view 已经超出了 cell 的高度, 但是在 Xcode 11.4 上这个地方是正常的.

**Comment by tigerAndBull** [comment]
> 这个是 demo 在 Xcode 12.0 上运行的效果,可以看出来左侧的圆形 view 已经超出了 cell 的高度, 但是在 Xcode 11.5 上这个地方是正常的.

这个高度问题，是animatedHeightCoefficient这个参数导致的，你可以设置为1.0

**Comment by laurivers** [comment]
@tigerAndBull 不好意思 今天用 Xcode 11.5 和 Xcode 12 重新对比确认是 cell 背景也被画了骨架的原因, 可以看一下上面我对 demo 的两个截图.

**Comment by laurivers** [comment]
做了一个 workaround, 提了 pr, #97

**Comment by tigerAndBull** [comment]
我今天有时间看下，非常感谢你的支持！



发自我的iPhone


------------------ Original ------------------

**Comment by tigerAndBull** [comment]
明确此问题的答案，请看 #97
