### ISSUE TITLE
能创建定死的Skeleton吗，因为cell是复杂的feed流，所以高度不确定，用自动生成的Skeleton动画会乱掉。

### ISSUE THREAD

**Issue by jianmu297** [tigerAndBull/TABAnimated#98]

**Comment by tigerAndBull** [comment]
可以，传固定高度就定死了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jianmuX <notifications@github.com&gt;
发送时间: 2020年7月30日 16:44
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 能创建定死的Skeleton吗，因为cell是复杂的feed流，所以高度不确定，用自动生成的Skeleton动画会乱掉。 (#98)

**Comment by yj9294** [comment]
self.view.tableView.tabAnimated = [TABTableAnimated animatedInRowModeWithCellClassArray:@[ODProfileInfoCell.class, ODProfileAboutMeCell.class, ODProfilePhotoCell.class, ODProfileFirstIdeaCell.class, ODProfileDetailCell.class, ODProfileAboutCell.class] cellHeightArray:@[@100, @90, @80, @60, @10, @20]];
这样无效，骨架仍然乱码，骨架乱码没事 ，主要是动画结束后我的自动布局被取消了？现在 每个行高定死了成44 默认高度，每个cell都被压死了成44，不是我设定的cellheight，急求帮助 谢谢

**Comment by yj9294** [comment]
self.view.tableView.tabAnimated = [TABTableAnimated animatedInRowModeWithCellClassArray:@[ODProfileInfoCell.class, ODProfileAboutMeCell.class, ODProfilePhotoCell.class, ODProfileFirstIdeaCell.class, ODProfileDetailCell.class, ODProfileAboutCell.class] cellHeightArray:@[@100, @90, @80, @60, @10, @20]];
这样无效，骨架仍然乱码，骨架乱码没事 ，主要是动画结束后我的自动布局被取消了？现在 每个行高定死了成44 默认高度，每个cell都被压死了成44，不是我设定的cellheight，急求帮助 谢谢

**Comment by tigerAndBull** [comment]
> ```
> self.view.tableView.tabAnimated = [TABTableAnimated animatedInRowModeWithCellClassArray:@[ODProfileInfoCell.class, ODProfileAboutMeCell.class, ODProfilePhotoCell.class, ODProfileFirstIdeaCell.class, ODProfileDetailCell.class, ODProfileAboutCell.class] cellHeightArray:@[@100, @90, @80, @60, @10, @20]];
> ```
> 
> 这样无效，骨架仍然乱码，骨架乱码没事 ，主要是动画结束后我的自动布局被取消了？现在 每个行高定死了成44 默认高度，每个cell都被压死了成44，不是我设定的cellheight，急求帮助 谢谢

提供demo

**Comment by jianmu297** [comment]
> […](#)
emmmmm, 我是想能否实现最简单的 像somo那种写死，而不是根据cell内视图生成的动画。。。。。。

**Comment by tigerAndBull** [comment]
> > […](#)
> > emmmmm, 我是想能否实现最简单的 像somo那种写死，而不是根据cell内视图生成的动画。。。。。。

初始化的时候，不是必须要绑定自己用的cell，可以是自己重写的一个cell

**Comment by fanyuexiang** [comment]
> > > […](#)
> > > emmmmm, 我是想能否实现最简单的 像somo那种写死，而不是根据cell内视图生成的动画。。。。。。
> 
> 初始化的时候，不是必须要绑定自己用的cell，可以是自己重写的一个cell

对的 你重新写一个用于骨架屏的cell，布局好，然后初始化tabanimated的 时候 使用这个cell

**Comment by tigerAndBull** [comment]
都可以，初始化方法都可以绑定



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fanyuexiang <notifications@github.com&gt;
发送时间: 2020年8月21日 12:00
收件人: tigerAndBull/TABAnimated <TABAnimated@noreply.github.com&gt;
抄送: tigerAndBull <1429299849@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[tigerAndBull/TABAnimated] 能创建定死的Skeleton吗，因为cell是复杂的feed流，所以高度不确定，用自动生成的Skeleton动画会乱掉。 (#98)





    
…
 emmmmm, 我是想能否实现最简单的 像somo那种写死，而不是根据cell内视图生成的动画。。。。。。
   
初始化的时候，不是必须要绑定自己用的cell，可以是自己重写的一个cell
  
对的 你重新写一个用于骨架屏的cell，布局好，然后初始化tabanimated的 时候 使用这个cell

**Comment by tigerAndBull** [comment]
请提供demo，这只是高度逻辑适配问题。

**Comment by tigerAndBull** [comment]
乱掉的问题是自适应高度的适配问题，需要您提供复现demo
